import { VIDEO_OVERLAY_TEMPLATE_CALLOUT_DEFINITIONS } from './data.callouts.ts';
import { VIDEO_OVERLAY_TEMPLATE_LOWER_THIRD_DEFINITIONS } from './data.lower-thirds.ts';
import { VIDEO_OVERLAY_TEMPLATE_SCENE_REVEAL_DEFINITIONS } from './data.scene-reveals.ts';
import { VIDEO_OVERLAY_TEMPLATE_TITLE_DEFINITIONS } from './data.titles.ts';

const VIDEO_OVERLAY_TEMPLATE_DEFINITIONS = {
  ...VIDEO_OVERLAY_TEMPLATE_LOWER_THIRD_DEFINITIONS,
  ...VIDEO_OVERLAY_TEMPLATE_TITLE_DEFINITIONS,
  ...VIDEO_OVERLAY_TEMPLATE_CALLOUT_DEFINITIONS,
  ...VIDEO_OVERLAY_TEMPLATE_SCENE_REVEAL_DEFINITIONS,
} as const;

const VIDEO_OVERLAY_TEMPLATE_DEFINITION_LIST = Object.values(VIDEO_OVERLAY_TEMPLATE_DEFINITIONS);

export { VIDEO_OVERLAY_TEMPLATE_DEFINITION_LIST, VIDEO_OVERLAY_TEMPLATE_DEFINITIONS };
