export const QA_LABELS_BY_DOMAIN = {
  architecture: new Set([
    'App-core owners',
    'Architecture guardrails',
    'Backup import atomicity',
    'Browser adapters',
    'Canonical facades',
    'Config policy',
    'Contract optionality drift',
    'Contract parser coverage',
    'Dependency boundaries',
    'Design system',
    'Entrypoint wiring',
    'Export artifact boundaries',
    'Heavy runtime imports',
    'i18n',
    'Manifest integrity',
    'Manifest permissions',
    'Messaging',
    'Messaging schema casts',
    'Package boundaries',
    'Root side effects',
    'Runtime listener ownership',
    'Runtime protocol contracts',
    'Runtime response privacy',
    'Runtime topology',
    'Shared style ownership',
    'Shared UI boundaries',
    'Sniptale identity',
    'Target-only paths',
    'UI automation seams',
    'ZIP package profile',
  ]),
  lifecycle: new Set([
    'Destructive async swaps',
    'History detached snapshots',
    'History revision semantics',
    'History transaction lifecycle',
    'Interactive controller ownership',
    'Lifecycle intent loss',
    'Parser snapshot purity',
    'Resource lifecycle pairs',
    'State-machine proof',
    'Storage write patterns',
    'Success/failure asymmetry',
  ]),
  maintainability: new Set([
    'AI limits',
    'Changed-line readability',
    'Detached controller methods',
    'Hot-loop work',
    'Hotspot regression',
    'Interface surfaces',
    'Multi-message transitions',
    'Naming',
    'Read path side effects',
    'Read-safe naming',
    'Resource budget consistency',
    'Root scatter',
    'Returned object surfaces',
  ]),
  security: new Set([
    'Dependency admission',
    'Diagnostic sanitization',
    'Fetch ownership',
    'Network fetch policy',
    'OSS release surface',
    'Secret storage',
    'Security',
    'Sensitive retention',
    'Suppression directives',
  ]),
};
