import {
  DEFAULT_COLOR_ACCENT,
  DEFAULT_COLOR_DANGER,
  DEFAULT_COLOR_INFO,
  DEFAULT_COLOR_SUCCESS,
  DEFAULT_COLOR_TEXT_INVERSE,
  DEFAULT_COLOR_TEXT_PANEL,
  DEFAULT_COLOR_WARNING,
} from '@sniptale/ui/default-colors/constants';

export const CALLOUT_BACKGROUND_PRESETS = [
  DEFAULT_COLOR_TEXT_PANEL,
  '#ffffff',
  DEFAULT_COLOR_DANGER,
  DEFAULT_COLOR_ACCENT,
  DEFAULT_COLOR_WARNING,
  DEFAULT_COLOR_SUCCESS,
  DEFAULT_COLOR_INFO,
];

export const CALLOUT_TEXT_PRESETS = [
  DEFAULT_COLOR_TEXT_INVERSE,
  '#111827',
  DEFAULT_COLOR_DANGER,
  DEFAULT_COLOR_ACCENT,
  DEFAULT_COLOR_SUCCESS,
  DEFAULT_COLOR_INFO,
];
