import {
  PAGE_ACCESS_ALL_SITES_CONTENT_SCRIPT_MATCHES,
  PAGE_ACCESS_ALL_SITES_ORIGIN_PATTERNS,
  PAGE_ACCESS_LEGACY_ALL_SITES_ORIGIN_PATTERNS,
} from '@sniptale/runtime-contracts/messaging/page-access';

export const ALL_SITES_ORIGIN_PATTERNS = PAGE_ACCESS_ALL_SITES_ORIGIN_PATTERNS;
export const ALL_SITES_CONTENT_SCRIPT_MATCHES = PAGE_ACCESS_ALL_SITES_CONTENT_SCRIPT_MATCHES;
export const LEGACY_ALL_SITES_ORIGIN_PATTERNS = PAGE_ACCESS_LEGACY_ALL_SITES_ORIGIN_PATTERNS;
export const PAGE_ACCESS_ALL_SITES_SCRIPT_ID = 'sniptale-page-access-all-sites';
export const PAGE_ACCESS_SITE_SCRIPT_PREFIX = 'sniptale-page-access-site';
