export const COVERAGE_ROLLOUT_EXACT_FILES = {
  coreRuntimeOwners: [
    'apps/extension/src/video-editor/project/selection/model.ts',
    'apps/extension/src/video-editor/runtime/commands/types.ts',
    'apps/extension/src/video-editor/runtime/controller/builders.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/header.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/insertion.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/preview.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/sidebar.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/surface.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/timeline.ts',
    'apps/extension/src/video-editor/runtime/controller/contracts/workspace.ts',
    'apps/extension/src/video-editor/runtime/controller/selected-clip-actions.ts',
    'apps/extension/src/video-editor/runtime/controller/shell.ts',
    'apps/extension/src/video-editor/runtime/controller/workspace/sidebar-placement-actions.ts',
    'apps/extension/src/video-editor/runtime/controller/workspace/sidebar.ts',
    'apps/extension/src/video-editor/runtime/controller/workspace/timeline.ts',
    'apps/extension/src/video-editor/runtime/controller/workspace/types.ts',
    'apps/extension/src/video-editor/runtime/playback/rate-slider.ts',
    'apps/extension/src/video-editor/runtime/session/auto-save.ts',
    'apps/extension/src/video-editor/runtime/session/export-event-route.ts',
    'apps/extension/src/video-editor/runtime/session/playback/index.ts',
    'apps/extension/src/video-editor/runtime/session/playback/nudge.ts',
    'apps/extension/src/video-editor/runtime/session/playback/shortcuts.ts',
    'apps/extension/src/video-editor/runtime/session/playback/state.ts',
    'apps/extension/src/video-editor/runtime/session/timeline-preview-cache.ts',
    'apps/extension/src/video-editor/runtime/session/timeline-preview-plans.ts',
    'apps/extension/src/video-editor/runtime/session/timeline-previews.ts',
    'apps/extension/src/video-editor/runtime/session/types.ts',
    'apps/extension/src/workflows/media-hub-backup/v6/restore-session.ts',
    'apps/extension/src/workflows/media-hub-backup/v6/staging.ts',
  ],
  contentParserExport: [
    'apps/extension/src/content/parser/backends/contracts.ts',
    'apps/extension/src/content/parser/backends/index.ts',
    'apps/extension/src/content/parser/backends/legacy-tree-walker/index.ts',
    'apps/extension/src/content/parser/export-manager/formats/froala.ts',
    'apps/extension/src/content/parser/dom-tree-parser/index.ts',
    'apps/extension/src/content/parser/dom-tree-parser/ai/editable-format.ts',
    'apps/extension/src/content/parser/dom-tree-parser/ai/markdown.ts',
    'apps/extension/src/content/parser/parsers/types.ts',
  ],
  contentHighlighterAndQuickEdit: [
    'apps/extension/src/content/selection/highlighter-runtime/controller.types.ts',
  ],
  contentSelectionAndCapture: [
    'apps/extension/src/content/selection/locker/index.ts',
    'apps/extension/src/content/selection/selection-mode/controller/index.ts',
    'apps/extension/src/content/selection/selection-mode/runtime/composition.ts',
    'apps/extension/src/content/parser/dom-utils/dom-helpers-selectors.ts',
    'apps/extension/src/content/parser/dom-utils/dom-helpers-text.ts',
    'apps/extension/src/content/parser/dom-utils/id-generator.ts',
  ],
};
