import fs from 'node:fs';
import path from 'node:path';

import { repoRoot } from '../../analysis/repository/shared-paths.mjs';
import { isExecutedAsScript } from '../../runtime/process/shared-cli.mjs';

export const CODEQL_PROOF_POLICY_PATH = 'tooling/configs/qa/codeql-proof-reuse.data.json';

function assertStringList(value, label) {
  if (
    !Array.isArray(value) ||
    value.length === 0 ||
    value.some((entry) => typeof entry !== 'string' || entry.length === 0) ||
    new Set(value).size !== value.length
  ) {
    throw new Error(`Malformed CodeQL ${label}.`);
  }
}

function isExcludedSourcePath(relativePath, policy) {
  const segments = relativePath.split('/');
  return (
    segments.some((segment) => policy.excludedDirectoryNames.includes(segment)) ||
    policy.excludedFileMarkers.some((marker) => relativePath.includes(marker))
  );
}

function containsAdmittedSource(root, relativeRoot, policy) {
  const absoluteRoot = path.join(root, relativeRoot);
  if (!fs.existsSync(absoluteRoot) || !fs.statSync(absoluteRoot).isDirectory()) return false;
  const pending = [absoluteRoot];
  while (pending.length > 0) {
    const directory = pending.pop();
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name);
      const relative = path.relative(root, absolute).replaceAll(path.sep, '/');
      if (isExcludedSourcePath(relative, policy)) continue;
      if (entry.isDirectory()) pending.push(absolute);
      else if (policy.sourceExtensions.includes(path.extname(entry.name))) return true;
    }
  }
  return false;
}

function assertSourceRoots(policy, root) {
  const normalized = policy.sourceRoots.map((sourceRoot) => path.posix.normalize(sourceRoot));
  if (
    normalized.some(
      (sourceRoot, index) =>
        sourceRoot !== policy.sourceRoots[index] ||
        sourceRoot === '.' ||
        sourceRoot.startsWith('../') ||
        path.posix.isAbsolute(sourceRoot)
    )
  ) {
    throw new Error('Malformed CodeQL source roots.');
  }
  for (const [index, sourceRoot] of policy.sourceRoots.entries()) {
    const overlaps = policy.sourceRoots.some(
      (candidate, candidateIndex) =>
        candidateIndex !== index && candidate.startsWith(`${sourceRoot}/`)
    );
    if (overlaps) throw new Error(`CodeQL source roots overlap: ${sourceRoot}.`);
    if (!containsAdmittedSource(root, sourceRoot, policy)) {
      throw new Error(`CodeQL source root has no admitted production files: ${sourceRoot}.`);
    }
  }
}

export function readCodeqlProofPolicy(root = repoRoot) {
  const policy = JSON.parse(fs.readFileSync(path.join(root, CODEQL_PROOF_POLICY_PATH), 'utf8'));
  if (
    policy?.schemaVersion !== 1 ||
    policy.artifactKind !== 'sniptale-codeql-proof-reuse-policy' ||
    policy.proofPath !== '.tmp/qa/codeql-proof.json' ||
    policy.sarifPath !== '.tmp/codeql/results.filtered.sarif' ||
    policy.configPath !== 'tooling/configs/qa/codeql-config.yml' ||
    policy.baselinePath !== 'tooling/configs/qa/codeql-baseline.json' ||
    typeof policy.owners !== 'object' ||
    policy.owners === null ||
    typeof policy.owners.artifactSeal !== 'string' ||
    typeof policy.proof !== 'string' ||
    typeof policy.rollback !== 'string' ||
    typeof policy.collisionCheck !== 'string'
  ) {
    throw new Error('Malformed CodeQL proof reuse policy.');
  }
  for (const [label, values] of Object.entries({
    'source roots': policy.sourceRoots,
    'source extensions': policy.sourceExtensions,
    'excluded directory names': policy.excludedDirectoryNames,
    'excluded file markers': policy.excludedFileMarkers,
    'control files': policy.controlFiles,
    consumers: policy.consumers,
  })) {
    assertStringList(values, label);
  }
  assertSourceRoots(policy, root);
  return policy;
}

function ignoredPatterns(policy) {
  return [
    ...policy.excludedDirectoryNames.map((name) => `**/${name}/**`),
    ...policy.excludedFileMarkers.map((marker) => `**/*${marker}*`),
  ];
}

export function generateCodeqlConfig(policy = readCodeqlProofPolicy()) {
  return `${[
    '# Generated by tooling/qa/audits/codeql/config.mjs. Do not edit by hand.',
    'name: sniptale-local-codeql',
    'paths:',
    ...policy.sourceRoots.map((root) => `  - ${root}`),
    'paths-ignore:',
    ...ignoredPatterns(policy).map((pattern) => `  - '${pattern}'`),
    'queries:',
    '  - uses: security-and-quality',
    '',
  ].join('\n')}`;
}

export function assertCodeqlConfigIsFresh(root = repoRoot) {
  const policy = readCodeqlProofPolicy(root);
  const actual = fs.readFileSync(path.join(root, policy.configPath), 'utf8');
  if (actual !== generateCodeqlConfig(policy)) {
    throw new Error(`Generated CodeQL config is stale: ${policy.configPath}`);
  }
}

if (isExecutedAsScript(import.meta.url)) {
  const policy = readCodeqlProofPolicy();
  if (process.argv.includes('--check')) assertCodeqlConfigIsFresh();
  else fs.writeFileSync(path.join(repoRoot, policy.configPath), generateCodeqlConfig(policy));
}
