import type { DesignTokenGroup } from './types';

export const DESIGN_TOKEN_GROUPS: DesignTokenGroup[] = [
  {
    tokenGroupId: 'surface',
    labelRu: 'Поверхности',
    labelEn: 'Surface',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-color-surface-canvas',
      '--sniptale-color-surface-panel',
      '--sniptale-color-surface-overlay',
      '--sniptale-color-surface-input',
      '--sniptale-color-surface-hover',
    ],
  },
  {
    tokenGroupId: 'border',
    labelRu: 'Рамки',
    labelEn: 'Border',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-color-border-subtle',
      '--sniptale-color-border-soft',
      '--sniptale-color-border-strong',
      '--sniptale-color-border-accent-soft',
      '--sniptale-color-border-accent-strong',
    ],
  },
  {
    tokenGroupId: 'text',
    labelRu: 'Текст',
    labelEn: 'Text',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-color-text-primary',
      '--sniptale-color-text-primary-strong',
      '--sniptale-color-text-secondary',
      '--sniptale-color-text-muted',
      '--sniptale-color-text-muted-strong',
      '--sniptale-color-text-dim',
    ],
  },
  {
    tokenGroupId: 'semantic',
    labelRu: 'Семантика и акцент',
    labelEn: 'Semantic and accent',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-color-accent',
      '--sniptale-color-accent-emphasis',
      '--sniptale-color-accent-glow',
      '--sniptale-color-accent-soft',
      '--sniptale-color-accent-soft-strong',
      '--sniptale-color-success',
      '--sniptale-color-success-soft',
      '--sniptale-color-warning',
      '--sniptale-color-warning-soft',
      '--sniptale-color-danger',
      '--sniptale-color-danger-soft',
      '--sniptale-color-info',
    ],
  },
  {
    tokenGroupId: 'layout',
    labelRu: 'Радиусы и elevation',
    labelEn: 'Radius and elevation',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-radius-sm',
      '--sniptale-radius-md',
      '--sniptale-radius-lg',
      '--sniptale-radius-xl',
      '--sniptale-shadow-sm',
      '--sniptale-shadow-floating',
      '--sniptale-shadow-floating-strong',
      '--sniptale-color-shadow-strong',
    ],
  },
  {
    tokenGroupId: 'motion',
    labelRu: 'Motion',
    labelEn: 'Motion',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-duration-fast',
      '--sniptale-duration-normal',
      '--sniptale-motion-spring',
      '--sniptale-motion-smooth',
      '--sniptale-glass-transition',
    ],
  },
  {
    tokenGroupId: 'glass',
    labelRu: 'Dynamic Glass (Level 2)',
    labelEn: 'Dynamic Glass (Level 2)',
    source: '@sniptale/ui/styles/design-tokens',
    items: [
      '--sniptale-color-surface-panel-glass',
      '--sniptale-radius-toolbar-glass',
      '--sniptale-size-toolbar-glass',
      '--sniptale-glass-blur',
      '--sniptale-glass-blur-hover',
      '--sniptale-glass-opacity',
      '--sniptale-glass-opacity-hover',
      '--sniptale-glass-gradient',
    ],
  },
  {
    tokenGroupId: 'component',
    labelRu: 'Компоненты',
    labelEn: 'Component',
    source: '@sniptale/ui/styles/design-tokens',
    items: ['--sniptale-color-toggle-thumb'],
  },
];
