import type { RuntimeStateAuthorityFlow } from './authority-flow-types';

export const CORE_RUNTIME_STATE_AUTHORITY_FLOWS = [
  {
    advisoryState: ['download router pending maps', 'browser downloads API item state'],
    authorityClass: 'durable-job',
    authoritativeState: ['capture job state manager record'],
    cleanupOwnerModule: 'apps/extension/src/background/capture/jobs/reconciliation.ts',
    correlationKeys: ['jobId', 'tabId', 'downloadId', 'runtimeGeneration', 'offscreenGeneration'],
    disposableState: ['capture guard state', 'download terminal timeout handles'],
    flowId: 'capture-download',
    freshnessReplayPolicy: 'job revisions and runtime/offscreen generations reject stale results',
    name: 'capture download job',
    ownerModule: 'apps/extension/src/background/capture/jobs/state-machine.ts',
    proofModules: ['apps/extension/src/background/capture/jobs/state-machine.test.ts'],
    restartBehavior: 'startup reconciliation hydrates and resumes or closes jobs from storage',
    writeFailurePolicy: 'state-machine writes are authoritative; failed transitions do not advance',
  },
  {
    advisoryState: ['archive save response channel'],
    authorityClass: 'transaction-bound',
    authoritativeState: ['staged archive chunk map keyed by archiveSessionId and stagedBlobId'],
    cleanupOwnerModule: 'apps/extension/src/background/capture/popup-export/staged-archives.ts',
    correlationKeys: ['archiveSessionId', 'stagedBlobId', 'tabId'],
    disposableState: ['in-flight archive chunks'],
    flowId: 'popup-export',
    freshnessReplayPolicy:
      'chunk indexes, total byte count, and staged ids reject duplicate/mismatched transfers',
    name: 'popup export staged archive',
    ownerModule: 'apps/extension/src/background/capture/popup-export/staged-archives.ts',
    proofModules: ['apps/extension/src/background/capture/popup-export/staged-archives.test.ts'],
    restartBehavior: 'transaction-bound chunks fail closed after worker restart',
    writeFailurePolicy: 'final save requires complete staged state before side effects',
  },
  {
    advisoryState: ['media-hub save response channel'],
    authorityClass: 'transaction-bound',
    authoritativeState: ['staged package and screenshot blobs', 'media-hub web snapshot record'],
    cleanupOwnerModule:
      'apps/extension/src/background/capture/routing/web-snapshot/staged-blobs.ts',
    correlationKeys: [
      'snapshotSessionId',
      'packageStagedBlobId',
      'screenshotStagedBlobId',
      'tabId',
    ],
    disposableState: ['in-flight package and screenshot chunks'],
    flowId: 'web-snapshot-save',
    freshnessReplayPolicy: 'staged ids and package manifest identity must match payload identity',
    name: 'web snapshot save',
    ownerModule: 'apps/extension/src/background/media-hub/web-snapshot.ts',
    proofModules: [
      'apps/extension/src/background/capture/routing/web-snapshot/staged-blobs.test.ts',
      'apps/extension/src/background/media-hub/web-snapshot-validation.test.ts',
    ],
    restartBehavior: 'missing staged blobs fail before media persistence',
    writeFailurePolicy:
      'media-hub persistence runs only after package, screenshot, and manifest validation',
  },
  {
    advisoryState: ['runtime activation response status'],
    authorityClass: 'durable-persistence',
    authoritativeState: ['page-access tab activation session-storage record'],
    cleanupOwnerModule: 'apps/extension/src/background/runtime/page-access/lifecycle.ts',
    correlationKeys: ['tabId', 'origin'],
    disposableState: ['in-memory activation fallback after session-storage write failure'],
    flowId: 'page-access-activation',
    freshnessReplayPolicy: 'tab lifecycle cleanup removes stale activation state',
    name: 'page access activation',
    ownerModule: 'apps/extension/src/background/storage/page-access/tab-activation.ts',
    proofModules: [
      'apps/extension/src/background/storage/page-access/tab-activation.test.ts',
      'apps/extension/src/background/runtime/page-access/service.test.ts',
      'apps/extension/src/background/runtime/page-access/lifecycle.test.ts',
    ],
    restartBehavior: 'session-storage activation records are authoritative across worker restart',
    writeFailurePolicy:
      'write failure records a bounded in-memory fallback and fails closed on missing authority',
  },
  {
    advisoryState: ['provider request progress', 'metadata-only history rows'],
    authorityClass: 'disposable-capability',
    authoritativeState: ['LLM session token and AI privacy proof'],
    cleanupOwnerModule: 'apps/extension/src/background/ai/llm/session-tokens.ts',
    correlationKeys: ['sessionId', 'tokenId'],
    disposableState: ['one-shot LLM session token'],
    flowId: 'ai-egress-lease',
    freshnessReplayPolicy: 'one-shot tokens are consumed before provider transport',
    name: 'AI egress lease',
    ownerModule: 'apps/extension/src/background/ai/llm/session-tokens.ts',
    proofModules: ['apps/extension/src/background/ai/llm/session-tokens.test.ts'],
    restartBehavior: 'tokens are disposable and callers request a fresh session after restart',
    writeFailurePolicy: 'provider transport does not run without token and privacy proof',
  },
  {
    advisoryState: ['scenario editor UI mirrors'],
    authorityClass: 'runtime-session',
    authoritativeState: ['scenario session maps', 'scenario surface maps'],
    cleanupOwnerModule: 'apps/extension/src/background/scenario/session-service/service/tab.ts',
    correlationKeys: ['tabId', 'projectId', 'revision'],
    disposableState: ['pending in-memory mutation result before persistence'],
    flowId: 'scenario-mutation',
    freshnessReplayPolicy: 'project revisions and tab ids scope scenario state reads and mutations',
    name: 'scenario mutation session state',
    ownerModule: 'apps/extension/src/background/scenario/session-service/persisted-mutation.ts',
    proofModules: [
      'apps/extension/src/background/scenario/session-service/runtime/mutations/persisted.test.ts',
    ],
    restartBehavior: 'hydration reloads persisted session state before mutations',
    writeFailurePolicy:
      'persisted session/surface writes serialize by service core and restore durable maps on failure',
  },
] as const satisfies readonly RuntimeStateAuthorityFlow[];
