import type { RuntimeStateAuthorityFlow } from './authority-flow-types';

export const SUPPORT_RUNTIME_STATE_AUTHORITY_FLOWS = [
  {
    advisoryState: ['diagnostic panel status'],
    authorityClass: 'runtime-session',
    authoritativeState: ['diagnostics active session state', 'sanitized recovery snapshot'],
    cleanupOwnerModule: 'apps/extension/src/background/diagnostics/session.ts',
    correlationKeys: ['diagnosticsSessionId', 'tabId'],
    disposableState: ['active CDP listener handles', 'timer handles'],
    flowId: 'diagnostics-session',
    freshnessReplayPolicy: 'session ids and tab lifecycle close active diagnostic sessions',
    name: 'diagnostics session',
    ownerModule: 'apps/extension/src/background/diagnostics/state.ts',
    proofModules: ['apps/extension/src/background/diagnostics/session.test.ts'],
    restartBehavior:
      'sanitized recovery snapshots are storage-backed; active listeners are transaction-bound',
    writeFailurePolicy:
      'diagnostic persistence sanitizes before retention and fails without session authority',
  },
  {
    advisoryState: ['privacy erasure route response'],
    authorityClass: 'transaction-bound',
    authoritativeState: [
      'serialized privacy erasure application transaction',
      'media lifecycle exclusion held through storage verification',
    ],
    cleanupOwnerModule: 'apps/extension/src/background/application/privacy-erasure/use-case.ts',
    correlationKeys: ['erasure request'],
    disposableState: ['runtime reset side effects'],
    flowId: 'privacy-erasure',
    freshnessReplayPolicy:
      'serialized requests re-run media, diagnostics, runtime, and storage verification in order',
    name: 'privacy erasure',
    ownerModule: 'apps/extension/src/background/application/privacy-erasure/use-case.ts',
    proofModules: [
      'apps/extension/src/background/application/privacy-erasure/use-case.test.ts',
      'apps/extension/src/background/media/lifecycle-gate.test.ts',
      'apps/extension/src/background/media/privacy-erasure/cleanup.test.ts',
    ],
    restartBehavior: [
      'caller reissues interrupted erasure; durable media state is hydrated',
      'and every cleanup phase is idempotently verified before storage deletion',
    ].join(' '),
    writeFailurePolicy:
      'new media starts fail while erasure owns the lifecycle; typed failures short-circuit later destructive phases',
  },
  {
    advisoryState: ['editor open response'],
    authorityClass: 'durable-persistence',
    authoritativeState: ['editor bootstrap retention row'],
    cleanupOwnerModule: 'apps/extension/src/composition/persistence/editor-bootstrap/retention.ts',
    correlationKeys: ['bootstrapId', 'assetId'],
    disposableState: ['one-time editor launch payload'],
    flowId: 'editor-bootstrap',
    freshnessReplayPolicy: 'retained rows are validated and legacy Blob rows are rejected',
    name: 'editor bootstrap retention',
    ownerModule: 'apps/extension/src/composition/persistence/editor-bootstrap/retention.ts',
    proofModules: ['apps/extension/src/composition/persistence/editor-bootstrap/retention.test.ts'],
    restartBehavior: 'retained data-url rows survive restart until cleanup policy removes them',
    writeFailurePolicy: 'invalid or legacy retained rows are rejected instead of repaired on read',
  },
  {
    advisoryState: ['page-style route response'],
    authorityClass: 'durable-persistence',
    authoritativeState: ['page-style rule storage', 'page-style asset storage'],
    cleanupOwnerModule: 'apps/extension/src/composition/persistence/page-style/storage/cleanup.ts',
    correlationKeys: ['ruleId', 'assetId', 'tabId'],
    disposableState: ['content-side object URLs', 'matched rule cache'],
    flowId: 'page-style-runtime',
    freshnessReplayPolicy: 'content runtime matches current tab/page state before applying rules',
    name: 'page-style runtime',
    ownerModule: 'apps/extension/src/content/selection/quick-edit-runtime/page-style/controller.ts',
    proofModules: [
      'apps/extension/src/content/selection/quick-edit-runtime/page-style/controller.test.ts',
      'apps/extension/src/composition/persistence/page-style/storage/index.test.ts',
    ],
    restartBehavior: 'rules and assets are persistent; content-side caches are reconstructible',
    writeFailurePolicy: 'storage owner validates rule and asset writes before runtime application',
  },
  {
    advisoryState: ['recording runtime status broadcast'],
    authorityClass: 'durable-lease',
    authoritativeState: ['video recording control lease'],
    cleanupOwnerModule:
      'apps/extension/src/background/media/video/recording-control-lease/index.ts',
    correlationKeys: ['recordingId', 'tabId', 'leaseId'],
    disposableState: ['offscreen recording command channel'],
    flowId: 'video-recording',
    freshnessReplayPolicy: 'recording controls require current lease ownership',
    name: 'video recording control',
    ownerModule: 'apps/extension/src/background/media/video/recording-control-lease/index.ts',
    proofModules: ['apps/extension/src/background/media/video/recording-control-lease.test.ts'],
    restartBehavior: 'storage-backed lease is hydrated before accepting recording controls',
    writeFailurePolicy: 'recording controls fail without current lease authority',
  },
  {
    advisoryState: ['project export capability tokens', 'offscreen command completion promise'],
    authorityClass: 'durable-job',
    authoritativeState: ['project export active job ledger'],
    cleanupOwnerModule:
      'apps/extension/src/background/media/video/runtime/handlers/export/reconcile.ts',
    correlationKeys: ['jobId', 'projectId', 'ownerDocumentId', 'ownerSenderUrl'],
    disposableState: ['ledger write queue', 'offscreen export command response channel'],
    flowId: 'project-export',
    freshnessReplayPolicy: 'owner-scoped capabilities and ledger status reject stale controls',
    name: 'project export job',
    ownerModule: 'apps/extension/src/composition/persistence/export-ledger/index.ts',
    proofModules: [
      'apps/extension/src/background/media/video/runtime/handlers/export/project-export.capability-reissue.test.ts',
    ],
    restartBehavior: 'export jobs reconcile through the ledger and reissue owner-scoped controls',
    writeFailurePolicy: 'ledger writes own status transitions and failure surfacing',
  },
  {
    advisoryState: ['tracked command promise', 'sendResponse closure'],
    authorityClass: 'runtime-session',
    authoritativeState: ['offscreen idempotency map'],
    cleanupOwnerModule: 'apps/extension/src/offscreen/runtime/idempotency.ts',
    correlationKeys: ['jobId', 'recordingId', 'desktopMediaRequestId', 'capabilityGeneration'],
    disposableState: ['runtime freshness nonce cache', 'rate-limit counters'],
    flowId: 'offscreen-command',
    freshnessReplayPolicy:
      'sender, runtime freshness, command capability, and rate limit are checked before mutation',
    name: 'offscreen side-effect command',
    ownerModule: 'apps/extension/src/offscreen/runtime/idempotency.ts',
    proofModules: ['apps/extension/src/offscreen/runtime/idempotency.test.ts'],
    restartBehavior: 'offscreen idempotency state is bounded in memory and fails closed on restart',
    writeFailurePolicy: 'failed tracked commands remove their key so an authorized retry can run',
  },
] as const satisfies readonly RuntimeStateAuthorityFlow[];
