// policyStateIds: [] - root fields are an immutable EffectV1 validation allowlist.
export const EFFECT_V1_ROOT_KEYS = new Set([
  'assets',
  'clips',
  'controls',
  'controlPresets',
  'defaultControlPresetId',
  'description',
  'duration',
  'id',
  'kind',
  'label',
  'layers',
  'objectLayout',
  'presets',
  'program',
  'scenes',
  'schemaVersion',
  'timeline',
]);
