import { vi } from 'vitest';

export function createInspectorCommandSurfaceActionMocks() {
  return {
    applyGradientPreset: vi.fn(),
    applyImagePatch: vi.fn(),
    clearBackgroundImage: vi.fn(),
    handleBackgroundImageUpload: vi.fn(async () => undefined),
    onApplyFrame: vi.fn(),
    onCloseDocument: vi.fn(),
    onCopyRenderedImage: vi.fn(),
    onExportSession: vi.fn(),
    onImportSession: vi.fn(),
    onOpenImage: vi.fn(),
    onPickBackgroundImage: vi.fn(),
    onResizeCanvas: vi.fn(),
    onResizeImage: vi.fn(),
    onResizeLayer: vi.fn(),
    onSaveImage: vi.fn(async () => undefined),
    onSaveImageAs: vi.fn(async () => undefined),
    onOpenLayerEffects: vi.fn(),
    applyLayerEffect: vi.fn(async () => undefined),
    applyLayerTransformation: vi.fn(async () => undefined),
    previewLayerEffect: vi.fn(),
    previewImagePatch: vi.fn(),
    resetLayerEffectPreview: vi.fn(),
    applyWorkspaceColor: vi.fn(async () => undefined),
    arrangeSelection: vi.fn(),
    removeLayerEffect: vi.fn(),
    saveWorkspaceColorAsDefault: vi.fn(async () => undefined),
    saveShapeAsHighlighterPreset: vi.fn(async () => undefined),
    saveToPreset: vi.fn(async () => undefined),
    setCanvasSizeDraft: vi.fn(),
    setCanvasSizeLocked: vi.fn(),
    setFrameDraft: vi.fn(),
    setImageData: vi.fn(),
    setImageSizeDraft: vi.fn(),
    setImageSizeLocked: vi.fn(),
    setInspector: vi.fn(),
    setLayerEffectsState: vi.fn(),
    setLayerSizeDraft: vi.fn(),
    setLayerSizeLocked: vi.fn(),
    setUniformPadding: vi.fn(),
    syncBrowserFrame: vi.fn(),
    updateLayerEffect: vi.fn(async () => undefined),
    updateWorkspace: vi.fn(),
  };
}
