import type { EditorInspectorCompactCommandContext } from '../command-types';

export type ToolCommandParams = Pick<
  EditorInspectorCompactCommandContext,
  | 'applyImagePatch'
  | 'applyRichShapePatch'
  | 'applyStepPatch'
  | 'arrangeSelection'
  | 'commitPendingSelectionSettings'
  | 'cropReady'
  | 'DimensionInput'
  | 'highlightedTool'
  | 'inspectorToolSettings'
  | 'layerAspectRatio'
  | 'layerSizeDraft'
  | 'layerSizeLocked'
  | 'layerSizeText'
  | 'lineStyleOptions'
  | 'onResizeLayer'
  | 'previewColor'
  | 'previewImagePatch'
  | 'previewStepPatch'
  | 'recentColors'
  | 'richShapeSelection'
  | 'selection'
  | 'shapeFillPalette'
  | 'shapeStrokePalette'
  | 'setLayerSizeDraft'
  | 'setLayerSizeLocked'
  | 'stepAlphabetOptions'
  | 'stepTypeOptions'
  | 'textColorPalette'
  | 'toNumber'
  | 'toolPresetHeader'
  | 'updateColor'
  | 'updateLockedDraft'
>;
