/* Generated by tooling/qa/codeql/generate-ownership.mjs. Do not edit by hand. */
import javascript

predicate isAllowedSecretStorageOwner(File file) {
  file.getRelativePath() =
    [
      "apps/extension/src/composition/persistence/ai-settings/provider-secret-keys.store.ts",
      "apps/extension/src/composition/persistence/ai-settings/provider-secret-protection.store.ts",
      "apps/extension/src/composition/persistence/ai-settings/provider-secrets.migration.ts",
      "apps/extension/src/composition/persistence/ai-settings/provider-secrets.store.ts",
      "apps/extension/src/composition/persistence/ai-settings/secret-protection.store.ts"
    ]
}

predicate isAllowedSensitiveRetentionOwner(File file) {
  file.getRelativePath() = "apps/extension/src/composition/persistence/video-preview-cache/mutations.ts"
}

predicate isAllowedSecretHeaderOwner(File file) {
  file.getRelativePath() = "apps/extension/src/background/ai/llm/transport/request.ts"
}

predicate isAllowedCredentialedFetchOwner(File file) {
  file.getRelativePath() =
    [
      "apps/extension/src/content/parser/dom-tree-parser/froala/index.ts",
      "apps/extension/src/content/parser/export-manager/files/download.ts",
      "apps/extension/src/content/parser/web-snapshot/assets.ts"
    ]
}

predicate isAllowedParserSnapshotBoundaryOwner(File file) {
  file.getRelativePath() =
    [
      "apps/extension/src/content/parser/export-manager-dom-driver.ts",
      "apps/extension/src/content/parser/export-manager/diagnostics/dom-driver.ts",
      "apps/extension/src/content/parser/export-manager/file-modal-utils.ts"
    ]
}

predicate isParserSnapshotSeam(File file) {
  file.getRelativePath().regexpMatch("^apps/extension/src/content/parser/pipelines/.+\\.[cm]?[jt]sx?$")
  or
  file.getRelativePath().regexpMatch("^apps/extension/src/content/parser/export-manager(?:/.+)?\\.[cm]?[jt]sx?$")
}

predicate isStorageWriteCall(CallExpr call, string qualifiedName) {
  exists(PropAccess callee |
    callee = call.getCallee() and
    qualifiedName = callee.getQualifiedName() and
    qualifiedName =
      [
        "chrome.storage.local.set",
        "chrome.storage.sync.set",
        "chrome.storage.session.set",
        "browserStorage.local.set",
        "browserStorage.sync.set",
        "browserStorage.session.set"
      ]
  )
}

predicate isSecretLikeFieldName(string name) {
  name = ["apiKey", "token", "secret", "authorization", "cookie"]
}

predicate isSensitiveRetentionFieldName(string name) {
  name =
    [
      "prompt",
      "markdownData",
      "jsonData",
      "rawResponse",
      "html",
      "innerHtml",
      "outerHtml",
      "cookie",
      "authorization"
    ]
}

predicate hasObjectArgument(CallExpr call, ObjectExpr objectArg) {
  exists(int index |
    index >= 0 and index < call.getNumArgument() and
    objectArg = call.getArgument(index)
  )
}

predicate hasPropertyNamed(ObjectExpr objectExpr, string propertyName, Property property) {
  property = objectExpr.getAProperty() and
  property.getName() = propertyName
}

predicate hasObjectPropertyNamed(ObjectExpr objectExpr, string propertyName, ObjectExpr value) {
  exists(Property property |
    hasPropertyNamed(objectExpr, propertyName, property) and
    value = property.getInit()
  )
}
