import type { ActionRouteContract } from './route-contract-types';

export const TAB_ACTION_ROUTE_CONTRACTS = {
  'capture-privileged-tab-route': {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, capability, or HAR session must match',
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    sideEffects: 'screenshot capture, editor open, staged download, HAR, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
  },
  'gallery-update-capability': {
    acceptedSenderClass: 'owned editor page with asset/document-scoped update lease',
    errorShape: 'gallery update error response',
    freshnessReplayPolicy: 'one-shot gallery update lease binds asset, document, and sender',
    requiredAuthority: 'gallery update capability',
    responseShape: 'gallery asset update response',
    sideEffects: 'persistent gallery asset overwrite',
    transitiveStateOwner: 'media-hub gallery asset owner',
  },
  'gallery-update-capability-issuance': {
    acceptedSenderClass: 'owned editor page requesting scoped gallery update authority',
    errorShape: 'gallery capability issuance error response',
    freshnessReplayPolicy: 'document and asset identity are bound into the issued lease',
    requiredAuthority: 'gallery update capability issuer',
    responseShape: 'gallery update capability grant response',
    sideEffects: 'issues a scoped gallery update lease',
    transitiveStateOwner: 'gallery update capability owner',
  },
  'page-style-privileged-tab-route': {
    acceptedSenderClass: 'owned content tab or extension page routed to an authorized tab',
    errorShape: 'page-style tab route error response',
    freshnessReplayPolicy: 'resolved tab/page state must match before applying or inspecting rules',
    requiredAuthority: 'privileged tab page-style authorization policy',
    responseShape: 'page-style route response',
    sideEffects: 'page-style inspection, rule summary, and storage-backed runtime effects',
    transitiveStateOwner: 'page-style runtime and shared page-style storage owners',
  },
  'popup-export-tab-route-capability': {
    acceptedSenderClass: 'popup or viewer route presenting one-shot tab-route capability',
    errorShape: 'popup export tab route error response',
    freshnessReplayPolicy: 'capability binds tab id, operation, request id, and expiry',
    requiredAuthority: 'popup export tab-route capability',
    responseShape: 'popup export route response',
    sideEffects: 'page parsing, snapshot packaging, media-hub write, export build, or cancellation',
    transitiveStateOwner: 'popup export routing and web snapshot owners',
  },
  'quick-action-privileged-tab-route': {
    acceptedSenderClass: 'owned content tab or extension page routed to an authorized tab',
    errorShape: 'quick-action tab route error response',
    freshnessReplayPolicy: 'trusted local action intent and resolved tab/frame/document must match',
    requiredAuthority: 'privileged tab quick-action authorization policy',
    responseShape: 'quick-action route response',
    sideEffects: 'quick capture or editor action side effects',
    transitiveStateOwner: 'background capture quick-action owner',
  },
  'scenario-privileged-tab-route': {
    acceptedSenderClass: 'active content tab, scenario viewer, or scenario editor owner',
    errorShape: 'scenario route error response',
    freshnessReplayPolicy: 'tab id, project/session identity, and revision freshness scope writes',
    requiredAuthority: 'privileged tab scenario authorization policy',
    responseShape: 'scenario route response',
    sideEffects: 'scenario session, project, capture, editor-open, or event persistence effects',
    transitiveStateOwner: 'background scenario router and scenario session-service owners',
  },
  'tab-mode-privileged-tab-route': {
    acceptedSenderClass: 'owned content tab or extension page routed to an authorized tab',
    errorShape: 'tab-mode route error response',
    freshnessReplayPolicy: 'resolved tab/frame/document state scopes mode toggles and reads',
    requiredAuthority: 'privileged tab mode authorization policy',
    responseShape: 'tab-mode route response',
    sideEffects: 'content overlay mode, viewport, or highlighter runtime changes',
    transitiveStateOwner: 'background tab-mode route owner',
  },
  'video-control-privileged-tab-route': {
    acceptedSenderClass: 'video editor or authorized extension page routed to recording tab',
    errorShape: 'video control route error response',
    freshnessReplayPolicy: 'recording lease, owner tab/document, generation, and TTL must match',
    requiredAuthority: 'privileged tab video-control authorization policy',
    responseShape: 'video recording control response',
    sideEffects:
      'recording start, start cancellation, stop, pause, resume, live settings, and session state updates',
    transitiveStateOwner: 'background video runtime recording owner',
  },
  'video-control-no-tab-route': {
    acceptedSenderClass:
      'popup recording setup sender starting camera-only recording without a tab',
    errorShape: 'video control no-tab route error response',
    freshnessReplayPolicy:
      'capture mode must be CAMERA; active lease controls gate later mutations',
    requiredAuthority: 'video-control no-tab popup authorization policy',
    responseShape: 'video recording control response',
    sideEffects: 'camera recording start without page-access or tab runtime side effects',
    transitiveStateOwner: 'background video runtime recording owner',
  },
  'video-control-camera-recorder-route': {
    acceptedSenderClass: 'registered camera-recorder extension window document',
    errorShape: 'video control camera-recorder route error response',
    freshnessReplayPolicy:
      'camera recorder document id and recording id must match the active launch-token grant',
    requiredAuthority: 'camera-recorder document control authorization policy',
    responseShape: 'video recording control response',
    sideEffects: 'camera window stop, pause, resume, or live microphone settings updates',
    transitiveStateOwner: 'background video runtime recording owner',
  },
  'video-control-owner-no-tab-route': {
    acceptedSenderClass: 'popup recording owner carrying recording control capability',
    errorShape: 'video control owner no-tab route error response',
    freshnessReplayPolicy: 'recording id, control token, owner url, generation, and TTL must match',
    requiredAuthority: 'popup owner no-tab recording control authorization policy',
    responseShape: 'video recording control response',
    sideEffects: 'recording start cancellation, stop, pause, resume, or live settings updates',
    transitiveStateOwner: 'background video runtime recording owner',
  },
} as const satisfies Record<string, ActionRouteContract>;
