import type { LocalizedPair } from './copy';

export const SHARED_PREVIEW_SELECT_OPTIONS = [
  {
    value: 'screen',
    label: ['Экран', 'Screen'],
    description: ['Основной контекст', 'Primary context'],
  },
  {
    value: 'window',
    label: ['Окно', 'Window'],
    description: ['Отдельное окно', 'Separate window'],
  },
] as const;

export const SHARED_PREVIEW_COPY_VALUES = {
  quickSettings: ['Быстрые настройки', 'Quick settings'],
  yes: ['Да', 'Yes'],
  no: ['Нет', 'No'],
  modePalette: ['Палитра режимов', 'Mode palette'],
  full: ['Полный', 'Full'],
  window: ['Окно', 'Window'],
  region: ['Регион', 'Region'],
  sectionPrefix: ['Секция', 'Section'],
  longOptionsStayInside: [
    'Длинный список опций остаётся внутри контейнера.',
    'Long option sets remain inside the container.',
  ],
  spacingAndLabel: ['Отступы и подпись', 'Spacing and label'],
  oneLogicalGroup: ['Одна логическая группа настроек.', 'One logical settings cluster.'],
  defaultSelectAria: ['Пример select', 'Example select'],
  popupFlatSelectAria: ['Пример select popup flat', 'Popup flat select example'],
  popupSelectAria: ['Компактный popup select', 'Compact popup select'],
  portalSelectAria: ['Пример portal select', 'Portal select example'],
  portalNote: [
    'Меню должно рендериться поверх clipping-контейнера.',
    'The menu should render above the clipping container.',
  ],
  smallSelectAria: ['Малый select', 'Small select'],
  mediumSelectAria: ['Средний select', 'Medium select'],
  startRecording: ['Начать запись', 'Start recording'],
  primaryCta: ['Главная CTA', 'Primary CTA'],
  openGallery: ['Открыть галерею', 'Open gallery'],
  secondaryAction: ['Вторичное действие', 'Secondary action'],
  mediaHub: ['Медиа-хаб', 'Media hub'],
  contentNavigation: ['Навигация по контенту', 'Content navigation'],
  catalog: ['Каталог', 'Catalog'],
  github: ['GitHub', 'GitHub'],
  settings: ['Настройки', 'Settings'],
  designSystem: ['Дизайн-система', 'Design system'],
  shellContent: ['Контент shell', 'Shell content'],
  inspectorPanel: ['Панель инспектора', 'Inspector panel'],
  innerFlexColumn: ['Внутренний flex-column контейнер.', 'Inner flex-column container.'],
  header: ['Заголовок', 'Header'],
  back: ['Назад', 'Back'],
  forward: ['Вперёд', 'Forward'],
  contentPortal: ['Портал контента', 'Content portal'],
  shadowRootNote: [
    'Этот визуал рендерится через адаптер в shadow-root.',
    'This surface is rendered through the adapter into a shadow-root.',
  ],
  widthField: ['Ширина', 'Width'],
  heightField: ['Высота', 'Height'],
  decreaseWidth: ['Уменьшить ширину', 'Decrease width'],
  increaseWidth: ['Увеличить ширину', 'Increase width'],
  decreaseHeight: ['Уменьшить высоту', 'Decrease height'],
  increaseHeight: ['Увеличить высоту', 'Increase height'],
  keepAspectRatio: ['Сохранить пропорции', 'Keep aspect ratio'],
  apply: ['Применить', 'Apply'],
  sectionAdapter: ['Section adapter', 'Section adapter'],
  sameVisualContract: [
    'Тот же visual contract внутри content popover.',
    'The same visual contract inside a content popover.',
  ],
  cursor: ['Курсор', 'Cursor'],
  highlight: ['Выделение', 'Highlight'],
  reset: ['Сбросить', 'Reset'],
  close: ['Закрыть', 'Close'],
  expiredTitle: ['Срок действия лицензии истек', 'License expired'],
  expiredMessage: [
    'Обновите доступ, чтобы продолжить работу.',
    'Renew access to continue using the product.',
  ],
} as const satisfies Record<string, LocalizedPair>;
