import type { LocalizedPair } from './copy';

export const PRODUCT_PREVIEW_COPY_KEYS = [
  'modalShellDefaultTitle',
  'modalShellDefaultBody',
  'modalShellCompactTitle',
  'modalShellCompactValue',
  'saveDialogTitle',
  'saveDialogSubtitle',
  'saveDialogFilenameLabel',
  'saveDialogPresetPathsLabel',
  'saveDialogItemTitle',
  'saveDialogNoPresets',
  'saveDialogOtherFolderLabel',
  'saveDialogOtherFolderHint',
  'formTextareaValue',
  'formCheckboxLabel',
  'formKbdLabel',
  'cancel',
  'close',
  'continue',
  'save',
  'run',
  'grid',
  'list',
  'generate',
  'duplicate',
  'template',
  'edit',
  'delete',
  'deleteProject',
  'viewport',
  'nativeSize',
  'documentation',
  'capture',
  'screen',
  'fullArea',
  'currentViewport',
  'active',
  'defaultLabel',
  'autoMode',
  'enabledByDefault',
  'less',
  'more',
  'confirmDeleteTitle',
  'confirmDeleteMessage',
  'confirmDeleteAction',
  'confirmDeletion',
  'infoToast',
  'successToast',
  'warningToast',
  'errorToast',
  'countdownPrefix',
  'countdownSuffix',
  'countdownToast',
] as const;

export const PRODUCT_PREVIEW_COPY_VALUES = {
  modalShellDefaultTitle: ['Основной modal', 'Primary modal'],
  modalShellDefaultBody: ['Большой shell для длинных flows.', 'Large shell for longer flows.'],
  modalShellCompactTitle: ['Компактная форма', 'Compact form'],
  modalShellCompactValue: ['Короткое значение', 'Short value'],
  saveDialogTitle: ['Куда сохранить', 'Where to save'],
  saveDialogSubtitle: [
    'Выбор пресета или системного диалога.',
    'Pick a preset or the system dialog.',
  ],
  saveDialogFilenameLabel: ['Имя файла', 'Filename'],
  saveDialogPresetPathsLabel: ['Пути пресетов', 'Preset paths'],
  saveDialogItemTitle: ['Папка проекта', 'Project folder'],
  saveDialogNoPresets: ['Нет доступных пресетов', 'No presets available'],
  saveDialogOtherFolderLabel: ['Другая папка', 'Other folder'],
  saveDialogOtherFolderHint: ['Открыть системный диалог', 'Open the system dialog'],
  formTextareaValue: ['Длинный текст для form flow.', 'Long-form text for a form flow.'],
  formCheckboxLabel: ['Сохранять автоматически', 'Save automatically'],
  formKbdLabel: ['запустить действие', 'run action'],
  cancel: ['Отмена', 'Cancel'],
  close: ['Закрыть', 'Close'],
  continue: ['Продолжить', 'Continue'],
  save: ['Сохранить', 'Save'],
  run: ['Запустить', 'Run'],
  grid: ['Сетка', 'Grid'],
  list: ['Список', 'List'],
  generate: ['Сгенерировать', 'Generate'],
  duplicate: ['Дублировать', 'Duplicate'],
  template: ['Шаблон', 'Template'],
  edit: ['Редактировать', 'Edit'],
  delete: ['Удалить', 'Delete'],
  deleteProject: ['Удалить проект', 'Delete project'],
  viewport: ['Viewport', 'Viewport'],
  nativeSize: ['Нативный размер', 'Native size'],
  documentation: ['Документация', 'Documentation'],
  capture: ['Захват', 'Capture'],
  screen: ['Экран', 'Screen'],
  fullArea: ['Полная область', 'Full area'],
  currentViewport: ['Текущий viewport', 'Current viewport'],
  active: ['Активно', 'Active'],
  defaultLabel: ['Обычный', 'Default'],
  autoMode: ['Авторежим', 'Auto mode'],
  enabledByDefault: ['Включено по умолчанию', 'Enabled by default'],
  less: ['Меньше', 'Less'],
  more: ['Больше', 'More'],
  confirmDeleteTitle: ['Удалить шаблон?', 'Delete template?'],
  confirmDeleteMessage: ['Действие нельзя отменить.', 'This action cannot be undone.'],
  confirmDeleteAction: ['Удалить', 'Delete'],
  confirmDeletion: ['Подтвердить удаление', 'Confirm deletion'],
  infoToast: ['Информационное сообщение', 'Informational message'],
  successToast: ['Готово', 'Done'],
  warningToast: ['Нужно проверить настройки', 'Settings need attention'],
  errorToast: ['Не удалось экспортировать', 'Export failed'],
  countdownPrefix: ['Старт записи через', 'Recording starts in'],
  countdownSuffix: ['сек.', 'sec.'],
  countdownToast: ['секунды до старта записи', 'seconds until recording starts'],
} as const satisfies Record<(typeof PRODUCT_PREVIEW_COPY_KEYS)[number], LocalizedPair>;
