export const EFFECT_RUNTIME_MESSAGE_KEYS = [
  'assetSelectionRef',
  'controls',
  'documentRef',
  'duration',
  'effectInstanceId',
  'fps',
  'frameIndex',
  'height',
  'inputFrames',
  'kind',
  'progress',
  'protocolVersion',
  'renderHeight',
  'renderWidth',
  'requestId',
  'sequenceId',
  'snapshotId',
  'time',
  'width',
] as const;
