export {
  INSPECTOR_SHELL_COLLAPSED_WIDTH_CLASS as SCENARIO_EDITOR_NAVIGATOR_COLLAPSED_WIDTH_CLASS,
  INSPECTOR_SHELL_EXPANDED_WIDTH_CLASS as SCENARIO_EDITOR_NAVIGATOR_EXPANDED_WIDTH_CLASS,
} from '@sniptale/ui/inspector-shell';
