import type { PolicyStateDescriptor } from './types';
import { MINUTE_MS } from './constants';

export const runtimePolicyStateDescriptors = [
  {
    authorityFamily: 'ai-settings-persistence',
    failClosedOnRestart: false,
    id: 'ai-settings-mutation-queue',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/ai-settings/graph-mutations.ts',
    proofModules: [
      'apps/extension/src/background/ai/settings/mutations.authority.test.ts',
      'apps/extension/src/composition/persistence/ai-settings/graph-mutations.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Durable settings storage remains authoritative across runtime restart;',
      'the new runtime recreates an empty queue and validates the graph before each transition.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'capture-download-job',
    failClosedOnRestart: false,
    id: 'capture-download-jobs',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture/jobs/state-machine.ts',
    proofModules: ['apps/extension/src/background/capture/jobs/state-machine.test.ts'],
    requiresTtl: false,
    restartBehavior: 'Startup reconciliation hydrates and resumes or closes jobs from storage.',
    restartClass: 'durable-lease',
    stateClass: 'job-state',
    storageClass: 'state-manager',
  },
  {
    authorityFamily: 'diagnostics-erasure-authority',
    failClosedOnRestart: false,
    id: 'diagnostics-erasure-exclusion',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/diagnostics/lifecycle-gate.ts',
    proofModules: ['apps/extension/src/background/diagnostics/lifecycle-gate.test.ts'],
    requiresTtl: false,
    restartBehavior: [
      'Diagnostics runtime mutations are discarded with the worker;',
      'recovery reconciles persistent debugger sessions before new mutations are admitted.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'native-ingestion-erasure-authority',
    failClosedOnRestart: false,
    id: 'native-ingestion-erasure-exclusion',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture/native-app/lifecycle-gate.ts',
    proofModules: [
      'apps/extension/src/background/capture/native-app/lifecycle-gate.test.ts',
      'apps/extension/src/background/capture/native-app/controller.lifecycle-gate.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Worker restart discards the native connection and its authority generation;',
      'runtime wiring installs cleanup authority before reconnecting ingestion.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'persistent-data-erasure-authority',
    failClosedOnRestart: false,
    id: 'persistent-data-erasure-lease',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/infrastructure/mutation-barrier.ts',
    proofModules: [
      'apps/extension/src/composition/persistence/infrastructure/mutation-barrier.test.ts',
      'apps/extension/src/composition/persistence/privacy-erasure/cleanup.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'The durable lease rejects cross-context persistence mutations after worker interruption;',
      'a reissued erasure replaces the abandoned lease and expired leases fail open only after TTL.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-local-storage',
    ttlMs: 5 * MINUTE_MS,
  },
  {
    authorityFamily: 'page-access-owner',
    failClosedOnRestart: false,
    id: 'page-access-tab-activation',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/storage/page-access/tab-activation.ts',
    proofModules: [
      'apps/extension/src/background/storage/page-access/tab-activation.test.ts',
      'apps/extension/src/background/runtime/page-access/service.test.ts',
      'apps/extension/src/background/runtime/page-access/lifecycle.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: 'Session-storage activation records are authoritative across worker restart.',
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'video-recording-control',
    failClosedOnRestart: false,
    id: 'video-recording-control-lease',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/media/video/recording-control-lease/index.ts',
    proofModules: ['apps/extension/src/background/media/video/recording-control-lease.test.ts'],
    requiresTtl: true,
    restartBehavior: 'Recording control authority is storage-backed and hydrated before controls.',
    restartClass: 'durable-lease',
    stateClass: 'capability',
    storageClass: 'browser-session-storage',
    ttlMs: 5 * MINUTE_MS,
  },
  {
    authorityFamily: 'video-project-export-ledger',
    failClosedOnRestart: false,
    id: 'project-export-job-ledger',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/export-ledger/write-queue.ts',
    proofModules: [
      'apps/extension/src/composition/persistence/export-ledger/index.test.ts',
      'apps/extension/src/composition/persistence/export-ledger/privacy-erasure.test.ts',
    ],
    requiresTtl: false,
    restartBehavior:
      'Session-storage export job metadata is authoritative and reconciled after worker restart.',
    restartClass: 'durable-lease',
    stateClass: 'job-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'tab-mode-runtime-state',
    failClosedOnRestart: false,
    id: 'tab-mode-runtime-state',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/application/runtime-state/index.ts',
    proofModules: ['apps/extension/src/background/application/runtime-state/index.test.ts'],
    requiresTtl: false,
    restartBehavior: 'Mode maps are reconstructible from content/UI status re-requests.',
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'ai-secret-unlock-authority',
    failClosedOnRestart: false,
    id: 'ai-secret-unlock-requests',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/ai/settings/secret-unlock-route.ts',
    proofModules: [
      'apps/extension/src/background/ai/settings/secret-unlock-route.lifecycle.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Pending unlock request metadata is recovered from session storage;',
      'decrypted key material reports restart-required after restart.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'unlock-request',
    storageClass: 'browser-session-storage',
    ttlMs: 5 * MINUTE_MS,
  },
] as const satisfies readonly PolicyStateDescriptor[];
