import type { PolicyStateDescriptor } from './types';
import { MINUTE_MS } from './constants';
import { VIDEO_POST_RECORD_RESULT_TTL_MS } from '../../storage/video/post-record-result';
import { CAMERA_RECORDER_DOCUMENT_TTL_MS } from '../../storage/video/camera-recorder-grant';

export const runtimePolicyStateDescriptors = [
  {
    authorityFamily: 'annotation-fork-session',
    failClosedOnRestart: false,
    id: 'annotation-fork-sessions',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/annotation-fork-session/route.ts',
    proofModules: [
      'apps/extension/src/background/annotation-fork-session/route.test.ts',
      'apps/extension/src/composition/persistence/content-pin-session/annotation-fork.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Session storage retains the tab-scoped text-free draft and revision across worker restart;',
      'the first authorized top-frame document reconstructs the document binding before mutation.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'ai-settings-persistence',
    failClosedOnRestart: false,
    id: 'ai-settings-mutation-queue',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/ai-settings/graph-mutations.ts',
    proofModules: [
      'apps/extension/src/background/ai/settings/mutations.authority.test.ts',
      'apps/extension/src/composition/persistence/ai-settings/graph-mutations.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Durable settings storage remains authoritative across runtime restart;',
      'the new runtime recreates an empty queue and validates the graph before each transition.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'capture-download-job',
    failClosedOnRestart: false,
    id: 'capture-download-jobs',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture/jobs/state-machine.ts',
    proofModules: ['apps/extension/src/background/capture/jobs/state-machine.test.ts'],
    requiresTtl: false,
    restartBehavior: 'Startup reconciliation hydrates and resumes or closes jobs from storage.',
    restartClass: 'durable-lease',
    stateClass: 'job-state',
    storageClass: 'state-manager',
  },
  {
    authorityFamily: 'gradient-preset-persistence',
    failClosedOnRestart: false,
    id: 'gradient-preset-mutation-queue',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/gradient-presets/index.ts',
    proofModules: [
      'apps/extension/src/composition/persistence/gradient-presets/index.test.ts',
      'apps/extension/src/composition/persistence/infrastructure/mutation-barrier.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Durable sync storage remains authoritative across runtime restart;',
      'the new runtime recreates an empty local ordering queue and re-reads validated storage',
      'under the cross-context mutation barrier before every write.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'capture-surface',
    failClosedOnRestart: false,
    id: 'capture-surface-leases',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture-surface/service.ts',
    proofModules: [
      'apps/extension/src/background/capture-surface/service.leases.test.ts',
      'apps/extension/src/background/capture-surface/service.recovery.test.ts',
      'apps/extension/src/background/capture-surface/screenshot-session.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Session-storage WAL is reconciled before new mutations are admitted;',
      'abandoned leases are restored or remain journaled on retryable platform failure.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'full-page-capture-session',
    failClosedOnRestart: false,
    id: 'full-page-capture-leases',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture/full-page/session-lease.ts',
    proofModules: [
      'apps/extension/src/background/capture/full-page/session-lease.test.ts',
      'apps/extension/src/background/capture/full-page/lifecycle.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Session storage keeps the active job and document binding for startup reconciliation;',
      'new work fails closed behind an unexpired lease and interrupted page state is restored best-effort.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
    ttlMs: 30_000,
  },
  {
    authorityFamily: 'diagnostics-erasure-authority',
    failClosedOnRestart: false,
    id: 'diagnostics-erasure-exclusion',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/diagnostics/lifecycle-gate.ts',
    proofModules: ['apps/extension/src/background/diagnostics/lifecycle-gate.test.ts'],
    requiresTtl: false,
    restartBehavior: [
      'Diagnostics runtime mutations are discarded with the worker;',
      'recovery reconciles persistent debugger sessions before new mutations are admitted.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'native-ingestion-erasure-authority',
    failClosedOnRestart: false,
    id: 'native-ingestion-erasure-exclusion',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/capture/native-app/lifecycle-gate.ts',
    proofModules: [
      'apps/extension/src/background/capture/native-app/lifecycle-gate.test.ts',
      'apps/extension/src/background/capture/native-app/controller.lifecycle-gate.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Worker restart discards the native connection and its authority generation;',
      'runtime wiring installs cleanup authority before reconnecting ingestion.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'persistent-data-erasure-authority',
    failClosedOnRestart: false,
    id: 'persistent-data-erasure-lease',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/infrastructure/mutation-barrier.ts',
    proofModules: [
      'apps/extension/src/composition/persistence/infrastructure/mutation-barrier.test.ts',
      'apps/extension/src/composition/persistence/privacy-erasure/cleanup.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'The durable lease rejects cross-context persistence mutations after worker interruption;',
      'a reissued erasure replaces the abandoned lease and expired leases fail open only after TTL.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-local-storage',
    ttlMs: 5 * MINUTE_MS,
  },
  {
    authorityFamily: 'offscreen-command-capability',
    failClosedOnRestart: false,
    id: 'offscreen-command-capability-generations',
    oneShot: true,
    ownerModule: 'apps/extension/src/offscreen/runtime/idempotency.ts',
    proofModules: [
      'apps/extension/src/offscreen/runtime/idempotency.test.ts',
      'apps/extension/src/offscreen/voice-input/runtime.test.ts',
      'packages/platform/src/security/offscreen-command-capability.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Offscreen document restart terminates its active effects and discards the replay cache;',
      'background retries mint a fresh bound generation while freshness and TTL reject stale commands.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'capability',
    storageClass: 'memory-only',
    ttlMs: 2 * MINUTE_MS,
  },
  {
    authorityFamily: 'offscreen-media-activity',
    failClosedOnRestart: false,
    id: 'offscreen-media-activity-lease',
    oneShot: false,
    ownerModule: 'apps/extension/src/offscreen/media-activity/lease.ts',
    proofModules: [
      'apps/extension/src/offscreen/media-activity/lease.test.ts',
      'apps/extension/src/offscreen/recording/multi-source/index.test.ts',
      'apps/extension/src/offscreen/voice-input/service.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Offscreen document teardown stops document-owned media effects and discards the lease;',
      'a recreated document therefore begins with an authoritative empty activity state.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'page-access-owner',
    failClosedOnRestart: false,
    id: 'page-access-tab-activation',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/storage/page-access/tab-activation.ts',
    proofModules: [
      'apps/extension/src/background/storage/page-access/tab-activation.test.ts',
      'apps/extension/src/background/runtime/page-access/service.test.ts',
      'apps/extension/src/background/runtime/page-access/lifecycle.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: 'Session-storage activation records are authoritative across worker restart.',
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'voice-input-session',
    failClosedOnRestart: false,
    id: 'voice-input-port-session-authority',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/voice-input/coordinator.ts',
    proofModules: [
      'apps/extension/src/background/voice-input/coordinator.test.ts',
      'apps/extension/src/workflows/voice-input/client.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'Service-worker restart disconnects owner Ports and discards worker-local session authority;',
      'a reconnecting client status check stops any orphaned offscreen session.',
      'Offscreen-document restart returns idle state, which retires only the exact observed',
      'background session captured by the status request and notifies its owning Port.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'video-camera-recorder-grant',
    failClosedOnRestart: false,
    id: 'video-camera-recorder-grant',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/storage/video/camera-recorder-grant.ts',
    proofModules: [
      'apps/extension/src/background/storage/video/camera-recorder-grant.test.ts',
      'apps/extension/src/background/media/video/runtime/camera-recorder-control.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/state/recording-state.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Session storage retains the document-bound camera capability across service-worker',
      'restarts; the launch token is consumed on first binding and records the exact sender tab.',
      'A reload may rebind only that tab to its new document without retaining recording identity',
      'or a registration token in page storage and without extending expiry. Result acknowledgement',
      'atomically revokes the matching grant; error/discard cleanup and TTL remain terminal guards. The',
      'worker cache is generation-bound and invalidated when privacy erasure is reserved.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'capability',
    storageClass: 'browser-session-storage',
    ttlMs: CAMERA_RECORDER_DOCUMENT_TTL_MS,
  },
  {
    authorityFamily: 'video-post-record-result',
    failClosedOnRestart: false,
    id: 'video-post-record-results',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/storage/video/post-record-result.ts',
    proofModules: [
      'apps/extension/src/background/storage/video/post-record-result.test.ts',
      'apps/extension/src/background/storage/video/post-record-acknowledgement.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/state/offscreen-lifecycle.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/state/offscreen-lifecycle.saved-replay.test.ts',
      'apps/extension/src/popup/recording/video/setup/index.post-record.test.tsx',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Session storage retains one monotonic staged, ready, or acknowledged result across popup',
      'and service-worker restarts. The complete saved-result lifecycle is admitted through the',
      'media-erasure exclusion, and staged results remain undisclosed until terminal cleanup.',
      'Acknowledgement logically clears only the exact ready result and leaves a bounded tombstone',
      'with an inert exact camera receipt so response-loss retries cannot restore authority or',
      'resurrect a completed user decision.',
    ].join(' '),
    restartClass: 'durable-lease',
    stateClass: 'runtime-state',
    storageClass: 'browser-session-storage',
    ttlMs: VIDEO_POST_RECORD_RESULT_TTL_MS,
  },
  {
    authorityFamily: 'video-recording-control',
    failClosedOnRestart: false,
    id: 'video-recording-control-lease',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/media/video/recording-control-lease/index.ts',
    proofModules: ['apps/extension/src/background/media/video/recording-control-lease.test.ts'],
    requiresTtl: true,
    restartBehavior: 'Recording control authority is storage-backed and hydrated before controls.',
    restartClass: 'durable-lease',
    stateClass: 'capability',
    storageClass: 'browser-session-storage',
    ttlMs: 5 * MINUTE_MS,
  },
  {
    authorityFamily: 'video-capture-surface',
    failClosedOnRestart: false,
    id: 'video-capture-surface-sessions',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/media/video/capture-surface/session-registry.ts',
    proofModules: [
      'apps/extension/src/background/media/video/capture-surface.test.ts',
      'apps/extension/src/background/media/video/runtime/manager/tab-navigation/index.test.ts',
    ],
    requiresTtl: false,
    restartBehavior: [
      'The active recording lease and capture-surface WAL reconstruct the in-memory session;',
      'source commands remain denied until recording, generation, and stream identity match.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'video-project-export-ledger',
    failClosedOnRestart: false,
    id: 'project-export-job-ledger',
    oneShot: false,
    ownerModule: 'apps/extension/src/composition/persistence/export-ledger/write-queue.ts',
    proofModules: [
      'apps/extension/src/composition/persistence/export-ledger/index.test.ts',
      'apps/extension/src/composition/persistence/export-ledger/privacy-erasure.test.ts',
    ],
    requiresTtl: false,
    restartBehavior:
      'Session-storage export job metadata is authoritative and reconciled after worker restart.',
    restartClass: 'durable-lease',
    stateClass: 'job-state',
    storageClass: 'browser-session-storage',
  },
  {
    authorityFamily: 'tab-mode-runtime-state',
    failClosedOnRestart: false,
    id: 'tab-mode-runtime-state',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/application/runtime-state/index.ts',
    proofModules: ['apps/extension/src/background/application/runtime-state/index.test.ts'],
    requiresTtl: false,
    restartBehavior: 'Mode maps are reconstructible from content/UI status re-requests.',
    restartClass: 'reconstructible',
    stateClass: 'runtime-state',
    storageClass: 'memory-only',
  },
  {
    authorityFamily: 'ai-secret-unlock-authority',
    failClosedOnRestart: false,
    id: 'ai-secret-unlock-requests',
    oneShot: false,
    ownerModule: 'apps/extension/src/background/ai/settings/secret-unlock-route.ts',
    proofModules: [
      'apps/extension/src/background/ai/settings/secret-unlock-route.lifecycle.test.ts',
    ],
    requiresTtl: true,
    restartBehavior: [
      'Pending unlock request metadata is recovered from session storage;',
      'decrypted key material reports restart-required after restart.',
    ].join(' '),
    restartClass: 'reconstructible',
    stateClass: 'unlock-request',
    storageClass: 'browser-session-storage',
    ttlMs: 5 * MINUTE_MS,
  },
] as const satisfies readonly PolicyStateDescriptor[];
