export const contextMenuSettingsFixture = {
  captureAction: 'download_default' as const,
  contextMenu: {
    enabled: true,
    showScreenshots: true,
    showVideo: true,
    showExport: true,
    showImageEditor: true,
    showVideoEditor: true,
    showGallery: true,
    showPageLinkCopy: true,
    showWindowResize: true,
    showSettings: true,
  },
  defaultExportPresetId: null,
  defaultImagePresetId: null,
  defaultVideoPresetId: 'preset-default',
  defaultViewportPresetId: 'preset-default',
  imageFormat: 'png' as const,
  imageQuality: 100,
  authenticatedSnapshotAssetsEnabled: true,
  anonymousCrossOriginSnapshotAssetsEnabled: false,
  presets: [],
  saveCapturesToGallery: false,
  viewportPresets: [
    {
      kind: 'user' as const,
      id: 'preset-default',
      name: 'Default',
      target: 'window' as const,
      width: 1440,
      height: 900,
      enabled: true,
      order: 0,
    },
    {
      kind: 'user' as const,
      id: 'preset-alt',
      name: 'Full HD',
      target: 'window' as const,
      width: 1920,
      height: 1080,
      enabled: true,
      order: 0,
    },
  ],
};

export const contextMenuVideoSettingsFixture = {
  autoFadeDelay: 3,
  countdownSeconds: 3,
  interactionDiagnosticsEnabled: false,
  microphoneDeviceId: null,
  microphoneEnabled: false,
  quality: 'HIGH',
  systemAudioEnabled: true,
};

export const contextMenuPopupExportPreferencesFixture = {
  includeBasicLogs: false,
  includeCssDiagnostics: false,
  includeFiles: true,
  includeFullPageScreenshot: false,
  includePageDiagnostics: false,
  includeImages: true,
  includeJson: true,
  includeMarkdown: true,
};
