import { vi } from 'vitest';

export function createMockControllerCoreMethods() {
  return {
    getPublicApiAdapter: vi.fn(),
    applyGridSnap: vi.fn(),
    buildViewportState: vi.fn(),
    syncViewportState: vi.fn(),
    scheduleViewportStateSync: vi.fn(),
    cancelTransientInteraction: vi.fn(() => true),
    startDrawSession: vi.fn(),
    getActiveCropRect: vi.fn(() => null),
    decorateShape: vi.fn(),
    addObject: vi.fn(),
    moveSelection: vi.fn(),
    moveSelectionToEdge: vi.fn(),
    logBrowserFrame: vi.fn(),
    ensureBrowserFrameOnTop: vi.fn(),
    relayoutScene: vi.fn(),
    prepareObject: vi.fn(),
    applyDocument: vi.fn(async () => undefined),
    rebuildFrameDecorations: vi.fn(async () => undefined),
    sendFrameObjectsToBack: vi.fn(),
    ensureObjectReachable: vi.fn(() => true),
    ensureReachableObjects: vi.fn(() => true),
    focusObjectInViewport: vi.fn(),
    withHistoryMuted: vi.fn(<T>(callback: () => T) => callback()),
    commitHistory: vi.fn(),
    scheduleZoomToFit: vi.fn(),
    syncRuntimeState: vi.fn(),
    applyToolMode: vi.fn(),
    switchToSelectTool: vi.fn(),
    nextLabelIndex: vi.fn(() => 7),
    advanceStepValue: vi.fn(),
    clearRasterSelection: vi.fn(),
    subscribeRasterOverlay: vi.fn(() => () => undefined),
    renderRasterOverlay: vi.fn(),
    applyRasterBitmap: vi.fn(async () => undefined),
    mount: vi.fn(),
    dispose: vi.fn(),
  };
}
