import { vi } from 'vitest';
import { createMockDocument } from '../test-fixtures-document';

export function createMockControllerDocumentMethods() {
  return {
    openImage: vi.fn(async () => undefined),
    loadDocument: vi.fn(async () => undefined),
    closeDocument: vi.fn(),
    exportDocument: vi.fn(() => createMockDocument()),
    renderToDataUrl: vi.fn(() => 'data:image/png;base64,abc'),
    copyRenderedImage: vi.fn(async () => undefined),
    setActiveTool: vi.fn(),
    suspendToolMode: vi.fn(),
    applyActiveSettingsToSelection: vi.fn(),
    undo: vi.fn(async () => undefined),
    redo: vi.fn(async () => undefined),
    resetToOriginal: vi.fn(async () => undefined),
    deleteSelection: vi.fn(),
    duplicateSelection: vi.fn(async () => undefined),
    nudgeSelection: vi.fn(() => true),
    finalizeSelectionNudge: vi.fn(),
    bringForwardSelection: vi.fn(),
    sendBackwardSelection: vi.fn(),
    bringSelectionToFront: vi.fn(),
    sendSelectionToBack: vi.fn(),
    reorderLayer: vi.fn(),
    selectLayer: vi.fn(),
    toggleLayerVisibility: vi.fn(),
    toggleLayerLock: vi.fn(),
    resizeLayer: vi.fn(),
    insertImage: vi.fn(async () => undefined),
    insertTechnicalData: vi.fn(),
    resizeCanvas: vi.fn(),
    resizeImage: vi.fn(),
    applyFrameSettings: vi.fn(),
    applyBrowserFrame: vi.fn(async () => undefined),
    removeBrowserFrame: vi.fn(async () => undefined),
    zoomIn: vi.fn(),
    zoomOut: vi.fn(),
    zoomToFit: vi.fn(),
    resetZoom: vi.fn(),
    setZoom: vi.fn(),
    setZoomAtViewportPoint: vi.fn(),
    navigateViewportTo: vi.fn(),
    clearCropSelection: vi.fn(),
    cancelCropMode: vi.fn(),
    applyCropSelection: vi.fn(async () => undefined),
  };
}
