export {
  clearAllHighlights,
  clearFrameEditing,
  consumeHighlighterSuppressedClick,
  disableHighlighterMode,
  enableHighlighterMode,
  invalidateFrameCache,
  isHighlighterEnabled,
  isFrameEditing,
  isHighlighterPausedState,
  pauseHighlighter,
  registerFrameCallbacks,
  resumeHighlighter,
  setFrameEditing,
} from '../highlighter-runtime';
