export const brushSettings = {
  color: '#111111',
  width: 4,
  opacity: 1,
  shadow: 0,
  shadowAngle: 90,
  shadowBlur: 12,
  shadowColor: '#111111',
  shadowDistance: 4,
  smoothingLevel: 4,
  shapeCorrection: 'subtle' as const,
};

export const shapeSettings = {
  strokeColor: '#111111',
  fillColor: '#00000000',
  strokeWidth: 4,
  opacity: 1,
  strokeOpacity: 1,
  fillOpacity: 0.5,
  borderPresetId: null,
  strokeStyle: 'solid' as const,
  radius: 8,
  shadow: 0,
  shadowAngle: 90,
  shadowBlur: 12,
  shadowColor: '#111111',
  shadowDistance: 4,
  customCss: '',
  inheritCustomCss: false,
};

export const arrowSettings = {
  color: '#111111',
  width: 4,
  style: 'solid' as const,
  opacity: 1,
  shadow: 0,
  shadowAngle: 90,
  shadowBlur: 12,
  shadowColor: '#111111',
  shadowDistance: 4,
  variant: 'standard' as const,
  mode: 'straight' as const,
  roughness: 0,
  bowing: 0,
  startHead: 'none' as const,
  endHead: 'triangle' as const,
};

export const lineSettings = {
  color: '#111827',
  width: 3,
  style: 'solid' as const,
  corners: 'round' as const,
  roughness: 0,
  bowing: 0,
  opacity: 1,
  shadow: 0,
  shadowAngle: 90,
  shadowBlur: 12,
  shadowColor: '#111827',
  shadowDistance: 4,
  fillMode: 'rough' as const,
  fillColor: '#ffffff',
  fillOpacity: 0.2,
  gradientFrom: '#ffffff',
  gradientTo: '#ff671d',
  gradientAngle: 0,
  roughFillStyle: 'cross-hatch' as const,
  roughFillColor: '#abcdef',
  roughFillGap: 8,
  roughFillAngle: -41,
  roughFillWeight: 1,
  roughFillRoughness: 1,
  roughFillBowing: 1,
  roughFillOpacity: 0.2,
};

export const blurSettings = {
  amount: 14,
  blurType: 'pixelate' as const,
  borderPresetId: 'preset-1',
  radius: 8,
  shadow: 30,
  showBorder: true,
  strokeColor: '#112233',
  strokeOpacity: 0.6,
  strokeStyle: 'dash-dot' as const,
  strokeWidth: 5,
};

export const textSettings = {
  calloutFormat: 'panel' as const,
  layoutMode: 'auto' as const,
  textAlign: 'center' as const,
  verticalAlign: 'top' as const,
  fontFamily: 'sans' as const,
  fontSize: 16,
  fontWeight: 'normal' as const,
  fontStyle: 'normal' as const,
  underline: false,
  linethrough: false,
  textColor: '#ffffff',
  textOpacity: 1,
  backgroundColor: '#111111',
  backgroundOpacity: 1,
  shadow: 0,
  shadowAngle: 90,
  shadowBlur: 12,
  shadowColor: '#ffffff',
  shadowDistance: 4,
  tailSize: 12,
};

export const stepSettings = {
  type: 'number' as const,
  alphabet: 'latin' as const,
  sizeLevel: 3,
  value: '1',
  color: '#111111',
  opacity: 1,
  textColor: '#ffffff',
  strokeColor: '#f8fafc',
  strokeOpacity: 1,
  strokeWidth: 2,
};

export const sceneBackgroundSettings = {
  paddingTop: 128,
  paddingRight: 128,
  paddingBottom: 128,
  paddingLeft: 128,
  backgroundMode: 'gradient' as const,
  backgroundColor: 'transparent',
  backgroundGradientFrom: '#7c2d12',
  backgroundGradientStops: ['#7c2d12', '#f59e0b'],
  backgroundGradientTo: '#f59e0b',
  backgroundGradientAngle: 145,
  backgroundImageData: null,
  backgroundImageFit: 'cover' as const,
  layoutMode: 'expand-canvas' as const,
  sourceImage: {
    borderPresetId: null,
    opacity: 1,
    radius: 0,
    shadow: 0,
    shadowAngle: 90,
    shadowBlur: 12,
    shadowColor: '#475569',
    shadowDistance: 4,
    strokeColor: '#475569',
    strokeOpacity: 1,
    strokeStyle: 'solid' as const,
    strokeWidth: 0,
  },
};
