export const EXPRESSION_SHAPES: Record<
  string,
  { args?: readonly [number, number]; fields?: readonly string[] }
> = {
  abs: { args: [1, 1] },
  add: { args: [1, 64] },
  and: { args: [1, 64] },
  clamp: { args: [3, 3] },
  concat: { args: [1, 64] },
  cos: { args: [1, 1] },
  cubicPoint: { args: [5, 5] },
  cubicTangent: { args: [5, 5] },
  div: { args: [2, 2] },
  ellipsePoint: { args: [5, 5] },
  ellipseVelocity: { args: [5, 5] },
  eq: { args: [2, 2] },
  exp: { args: [1, 1] },
  fallback: { fields: ['fallback', 'value'] },
  floor: { args: [1, 1] },
  gt: { args: [2, 2] },
  gte: { args: [2, 2] },
  inOut: { args: [1, 1] },
  lt: { args: [2, 2] },
  lte: { args: [2, 2] },
  max: { args: [1, 64] },
  min: { args: [1, 64] },
  mix: { args: [3, 3] },
  mod: { args: [2, 2] },
  mul: { args: [1, 64] },
  neg: { args: [1, 1] },
  not: { args: [1, 1] },
  or: { args: [1, 64] },
  out: { args: [1, 1] },
  point: { args: [2, 2] },
  pow: { args: [2, 2] },
  read: { fields: ['path'] },
  rgba: { args: [3, 4] },
  select: { fields: ['value', 'values'] },
  sin: { args: [1, 1] },
  sqrt: { args: [1, 1] },
  sub: { args: [2, 2] },
};
