export const NATIVE_APP_PROTOCOL_VERSION = 1;
export const NATIVE_APP_SETTINGS_SCHEMA_VERSION = 1;
export const NATIVE_APP_CACHE_SCHEMA_VERSION = 1;
export const NATIVE_HOST_MANIFEST_VERSION = '0.1.0';
export const MIN_SUPPORTED_NATIVE_APP_VERSION = '0.1.0';
export const MIN_SUPPORTED_EXTENSION_VERSION = '0.1.0';

export const NATIVE_HOST_TO_EXTENSION_MAX_MESSAGE_BYTES = 1_048_576;
export const NATIVE_EXTENSION_TO_HOST_MAX_MESSAGE_BYTES = 64 * 1024 * 1024;
export const NATIVE_MESSAGE_TARGET_MAX_JSON_UTF8_BYTES = 900 * 1024;
export const NATIVE_CHUNK_RAW_BYTES = 512 * 1024;
export const NATIVE_CHUNK_MAX_BASE64_CHARS = 700_000;
export const NATIVE_SCREENSHOT_MAX_TOTAL_BYTES = 256 * 1024 * 1024;
export const NATIVE_RECORDING_MAX_TOTAL_BYTES = 8 * 1024 * 1024 * 1024;

export const NATIVE_SUPPORTED_PROTOCOL_VERSIONS = [NATIVE_APP_PROTOCOL_VERSION] as const;
export const NATIVE_SUPPORTED_SETTINGS_SCHEMA_VERSIONS = [
  NATIVE_APP_SETTINGS_SCHEMA_VERSION,
] as const;
