import type { ContentPrivilegedActionCapability } from '../../protocol/content-privileged-action';

export const MessageType = {
  ENABLE_SCREENSHOT_MODE: 'ENABLE_SCREENSHOT_MODE',
  DISABLE_SCREENSHOT_MODE: 'DISABLE_SCREENSHOT_MODE',
  SCREENSHOT_MODE_STATUS: 'SCREENSHOT_MODE_STATUS',
  ENABLE_HIGHLIGHTER_MODE: 'ENABLE_HIGHLIGHTER_MODE',
  DISABLE_HIGHLIGHTER_MODE: 'DISABLE_HIGHLIGHTER_MODE',
  HIGHLIGHTER_MODE_STATUS: 'HIGHLIGHTER_MODE_STATUS',
  ENABLE_QUICK_EDIT_MODE: 'ENABLE_QUICK_EDIT_MODE',
  DISABLE_QUICK_EDIT_MODE: 'DISABLE_QUICK_EDIT_MODE',
  QUICK_EDIT_MODE_STATUS: 'QUICK_EDIT_MODE_STATUS',
  SHOW_TOOLBAR: 'SHOW_TOOLBAR',
  HIDE_TOOLBAR: 'HIDE_TOOLBAR',
  TOOLBAR_STATUS: 'TOOLBAR_STATUS',
  REQUEST_LLM_SESSION: 'REQUEST_LLM_SESSION',
  PROCESS_WITH_LLM: 'PROCESS_WITH_LLM',
  PROCESS_SCENARIO_EDITOR_WITH_LLM: 'PROCESS_SCENARIO_EDITOR_WITH_LLM',
  AI_SETTINGS_QUERY: 'AI_SETTINGS_QUERY',
  AI_SETTINGS_MUTATION: 'AI_SETTINGS_MUTATION',
  AI_SETTINGS_NAVIGATION: 'AI_SETTINGS_NAVIGATION',
  AI_SECRET_UNLOCK: 'AI_SECRET_UNLOCK',
  NATIVE_APP_QUERY: 'NATIVE_APP_QUERY',
  NATIVE_APP_MUTATION: 'NATIVE_APP_MUTATION',
  PAGE_ACCESS: 'PAGE_ACCESS',
  ERASE_LOCAL_EXTENSION_DATA: 'ERASE_LOCAL_EXTENSION_DATA',
  OFFSCREEN_PRIVACY_ERASURE_PAGE_STORAGE: 'OFFSCREEN_PRIVACY_ERASURE_PAGE_STORAGE',
  FRAME_ANNOTATION_RASTERIZE: 'FRAME_ANNOTATION_RASTERIZE',
  OFFSCREEN_FRAME_ANNOTATION_RASTERIZE: 'OFFSCREEN_FRAME_ANNOTATION_RASTERIZE',
  OFFSCREEN_VOICE_INPUT_STATUS: 'OFFSCREEN_VOICE_INPUT_STATUS',
  OFFSCREEN_VOICE_INPUT_START: 'OFFSCREEN_VOICE_INPUT_START',
  OFFSCREEN_VOICE_INPUT_STOP: 'OFFSCREEN_VOICE_INPUT_STOP',
  OFFSCREEN_VOICE_INPUT_EVENT: 'OFFSCREEN_VOICE_INPUT_EVENT',
  LLM_RESPONSE: 'LLM_RESPONSE',
  LLM_ERROR: 'LLM_ERROR',
  APPLY_VIEWPORT_PRESET: 'APPLY_VIEWPORT_PRESET',
  RELEASE_VIEWPORT_PRESET: 'RELEASE_VIEWPORT_PRESET',
  GET_VIEWPORT_PRESET_AVAILABILITY: 'GET_VIEWPORT_PRESET_AVAILABILITY',
  VIEWPORT_CHANGED: 'VIEWPORT_CHANGED',
  GET_VIEWPORT_STATUS: 'GET_VIEWPORT_STATUS',
  OPEN_EXPORT_MODAL: 'OPEN_EXPORT_MODAL',
  DOWNLOAD_BROWSER_ANNOTATIONS: 'DOWNLOAD_BROWSER_ANNOTATIONS',
  CONSUME_POPUP_EXPORT_LAUNCH_INTENT: 'CONSUME_POPUP_EXPORT_LAUNCH_INTENT',
  EXPORT_POPUP_PREVIEW: 'EXPORT_POPUP_PREVIEW',
  EXPORT_POPUP_START: 'EXPORT_POPUP_START',
  EXPORT_POPUP_BUILD_PACKAGE: 'EXPORT_POPUP_BUILD_PACKAGE',
  EXPORT_POPUP_SAVE_WEB_SNAPSHOT: 'EXPORT_POPUP_SAVE_WEB_SNAPSHOT',
  STAGE_POPUP_EXPORT_ARCHIVE_CHUNK: 'STAGE_POPUP_EXPORT_ARCHIVE_CHUNK',
  EXPORT_POPUP_SAVE_ARCHIVE: 'EXPORT_POPUP_SAVE_ARCHIVE',
  RELEASE_POPUP_EXPORT_ARCHIVE: 'RELEASE_POPUP_EXPORT_ARCHIVE',
  EXPORT_POPUP_CANCEL: 'EXPORT_POPUP_CANCEL',
  REQUEST_POPUP_TAB_ROUTE_CAPABILITY: 'REQUEST_POPUP_TAB_ROUTE_CAPABILITY',
  REQUEST_CONTENT_PRIVILEGED_ACTION_ACTIVATION_KEY:
    'REQUEST_CONTENT_PRIVILEGED_ACTION_ACTIVATION_KEY',
  REQUEST_CONTENT_PRIVILEGED_ACTION_RUNTIME_TOKEN:
    'REQUEST_CONTENT_PRIVILEGED_ACTION_RUNTIME_TOKEN',
  REQUEST_CONTENT_PRIVILEGED_ACTION_PROOF: 'REQUEST_CONTENT_PRIVILEGED_ACTION_PROOF',
  REQUEST_CONTENT_PRIVILEGED_ACTION_CAPABILITY: 'REQUEST_CONTENT_PRIVILEGED_ACTION_CAPABILITY',
  CONTENT_RUNTIME_WAKEUP: 'CONTENT_RUNTIME_WAKEUP',
  ANNOTATION_FORK_SESSION: 'ANNOTATION_FORK_SESSION',
  EXPORT_POPUP_PROGRESS: 'EXPORT_POPUP_PROGRESS',
  EXPORT_POPUP_RESULT: 'EXPORT_POPUP_RESULT',
  REQUEST_EXPORT_HAR_START_CAPABILITY: 'REQUEST_EXPORT_HAR_START_CAPABILITY',
  EXPORT_START_HAR: 'EXPORT_START_HAR',
  EXPORT_STOP_HAR: 'EXPORT_STOP_HAR',
  EXPORT_CAPTURE_FULL_PAGE: 'EXPORT_CAPTURE_FULL_PAGE',
  EXPORT_CAPTURE_FULL_PAGE_UNATTENDED: 'EXPORT_CAPTURE_FULL_PAGE_UNATTENDED',
  PREPARE_FULL_PAGE_CAPTURE: 'PREPARE_FULL_PAGE_CAPTURE',
  HEARTBEAT_FULL_PAGE_CAPTURE: 'HEARTBEAT_FULL_PAGE_CAPTURE',
  PREPARE_FULL_PAGE_TILE: 'PREPARE_FULL_PAGE_TILE',
  VERIFY_FULL_PAGE_TILE: 'VERIFY_FULL_PAGE_TILE',
  RESTORE_FULL_PAGE_CAPTURE: 'RESTORE_FULL_PAGE_CAPTURE',
  OPEN_EDITOR_WITH_IMAGE: 'OPEN_EDITOR_WITH_IMAGE',
  IMAGE_DATA_FOR_EDITOR: 'IMAGE_DATA_FOR_EDITOR',
  SAVE_SCREENSHOT_TO_GALLERY: 'SAVE_SCREENSHOT_TO_GALLERY',
  SAVE_WEB_SNAPSHOT_TO_GALLERY: 'SAVE_WEB_SNAPSHOT_TO_GALLERY',
  REGISTER_WEB_SNAPSHOT_ASSETS: 'REGISTER_WEB_SNAPSHOT_ASSETS',
  FETCH_WEB_SNAPSHOT_ASSET: 'FETCH_WEB_SNAPSHOT_ASSET',
  STAGE_WEB_SNAPSHOT_BLOB_CHUNK: 'STAGE_WEB_SNAPSHOT_BLOB_CHUNK',
  RELEASE_WEB_SNAPSHOT_STAGED_BLOBS: 'RELEASE_WEB_SNAPSHOT_STAGED_BLOBS',
  REQUEST_GALLERY_IMAGE_UPDATE_CAPABILITY: 'REQUEST_GALLERY_IMAGE_UPDATE_CAPABILITY',
  UPDATE_GALLERY_IMAGE_ASSET: 'UPDATE_GALLERY_IMAGE_ASSET',
  SCENARIO_GET_SESSION: 'SCENARIO_GET_SESSION',
  SCENARIO_SET_ENABLED: 'SCENARIO_SET_ENABLED',
  SCENARIO_SET_CAPTURE_MODE: 'SCENARIO_SET_CAPTURE_MODE',
  SCENARIO_SET_SIDEBAR_VISIBLE: 'SCENARIO_SET_SIDEBAR_VISIBLE',
  SCENARIO_SET_ACTIVE_PROJECT: 'SCENARIO_SET_ACTIVE_PROJECT',
  SCENARIO_LIST_PROJECTS: 'SCENARIO_LIST_PROJECTS',
  SCENARIO_CREATE_PROJECT: 'SCENARIO_CREATE_PROJECT',
  SCENARIO_SAVE_CAPTURE_STEP: 'SCENARIO_SAVE_CAPTURE_STEP',
  SCENARIO_DELETE_STEP: 'SCENARIO_DELETE_STEP',
  SCENARIO_RESTORE_STEP: 'SCENARIO_RESTORE_STEP',
  SCENARIO_MOVE_STEP: 'SCENARIO_MOVE_STEP',
  SCENARIO_RECORD_SUGGESTED_EVENT: 'SCENARIO_RECORD_SUGGESTED_EVENT',
  SCENARIO_OPEN_EDITOR: 'SCENARIO_OPEN_EDITOR',
  SCENARIO_GET_RESTORE_SNAPSHOT: 'SCENARIO_GET_RESTORE_SNAPSHOT',
  SCENARIO_UPDATE_SURFACE_STATE: 'SCENARIO_UPDATE_SURFACE_STATE',
  SCENARIO_UPDATE_SESSION_PREFS: 'SCENARIO_UPDATE_SESSION_PREFS',
  EXECUTE_SAVE: 'EXECUTE_SAVE',
  SHOW_SAVE_DIALOG: 'SHOW_SAVE_DIALOG',
  TRIGGER_QUICK_ACTION: 'TRIGGER_QUICK_ACTION',
  SHOW_TOAST: 'SHOW_TOAST',
  SHOW_QUICK_ACTION_COUNTDOWN: 'SHOW_QUICK_ACTION_COUNTDOWN',
  COPY_IMAGE_TO_CLIPBOARD: 'COPY_IMAGE_TO_CLIPBOARD',
  COPY_TEXT_TO_CLIPBOARD: 'COPY_TEXT_TO_CLIPBOARD',
  DESTROY_UI_TOOLBAR: 'DESTROY_UI_TOOLBAR',
} as const;

export type MessageType = (typeof MessageType)[keyof typeof MessageType];

export { CaptureMessageType, CaptureType } from '../capture-messages';
export type { CaptureArea } from '../capture-messages';

export interface AppliedViewportPresetPayload {
  presetId: string;
  target: 'viewport' | 'window';
  width: number;
  height: number;
}

export type ViewportPresetAvailabilityPayload =
  | {
      status: 'available';
      presetId: string;
      target: 'viewport' | 'window';
      required: { width: number; height: number };
    }
  | {
      status: 'requires-start-validation';
      presetId: string;
      target: 'viewport';
      required: { width: number; height: number };
    }
  | {
      status: 'unavailable';
      presetId: string;
      target: 'viewport' | 'window' | null;
      reason:
        | 'disabled'
        | 'missing'
        | 'unsupported-context'
        | 'viewport-too-large'
        | 'window-too-large'
        | 'window-not-normal'
        | 'zoom-not-100'
        | 'surface-busy'
        | 'permission-denied'
        | 'platform-rejected'
        | 'verification-failed';
      required?: { width: number; height: number };
      available?: { width: number; height: number };
    };

interface ApplyViewportPresetMessage {
  type: typeof MessageType.APPLY_VIEWPORT_PRESET;
  operationGeneration: number;
  presetId: string;
  surfaceCapabilityToken: string;
  tabId?: number;
}

interface ReleaseViewportPresetMessage {
  type: typeof MessageType.RELEASE_VIEWPORT_PRESET;
  leaseGeneration: number;
  operationGeneration: number;
  surfaceCapabilityToken: string;
  tabId?: number;
}

interface GetViewportPresetAvailabilityMessage {
  type: typeof MessageType.GET_VIEWPORT_PRESET_AVAILABILITY;
  context?: 'screenshot' | 'video';
  presetIds: string[];
  tabId?: number;
}

interface GetViewportStatusMessage {
  type: typeof MessageType.GET_VIEWPORT_STATUS;
  tabId?: number;
}

export interface ViewportStatusResponse {
  success: boolean;
  viewport: AppliedViewportPresetPayload | null;
  error?: string;
}

export type ResponseSender<T = unknown> = (response?: T) => void;

export type TabModeMessage =
  | {
      type: typeof MessageType.ENABLE_SCREENSHOT_MODE;
      tabId?: number;
      viewport?: AppliedViewportPresetPayload | null;
      contentIntent?: ContentPrivilegedActionCapability;
      surfaceCapabilityToken?: string;
      surfaceWarning?: string;
    }
  | {
      type: typeof MessageType.DISABLE_SCREENSHOT_MODE;
      leaseGeneration?: number;
      operationGeneration?: number;
      surfaceCapabilityToken?: string;
      tabId?: number;
    }
  | {
      type: typeof MessageType.SCREENSHOT_MODE_STATUS;
      tabId?: number;
    }
  | { type: typeof MessageType.ENABLE_HIGHLIGHTER_MODE; tabId?: number }
  | { type: typeof MessageType.DISABLE_HIGHLIGHTER_MODE; tabId?: number }
  | { type: typeof MessageType.HIGHLIGHTER_MODE_STATUS; tabId?: number }
  | { type: typeof MessageType.ENABLE_QUICK_EDIT_MODE; tabId?: number }
  | { type: typeof MessageType.DISABLE_QUICK_EDIT_MODE; tabId?: number }
  | { type: typeof MessageType.QUICK_EDIT_MODE_STATUS; tabId?: number }
  | ApplyViewportPresetMessage
  | ReleaseViewportPresetMessage
  | GetViewportPresetAvailabilityMessage
  | GetViewportStatusMessage;
