export const RELEASE_DIRECT_STEPS = [
  ['changed-line-readability', 'Changed-line readability', 'verify-line-length.mjs'],
  ['oxlint', 'Oxlint', 'verify-oxlint.mjs'],
  ['eslint', 'ESLint', 'verify-eslint.mjs'],
  ['sonarjs', 'SonarJS', 'verify-sonarjs.mjs'],
  ['ai-limits', 'AI limits', 'verify-ai-limits.mjs'],
  ['naming', 'Naming', 'verify-naming.mjs'],
  ['i18n', 'i18n', 'verify-i18n.mjs'],
  ['design-system', 'Design system', 'verify-design-system.mjs'],
  ['audit', 'Audit', 'verify-audit.mjs'],
  ['security', 'Security', 'verify-security.mjs'],
  ['dependency-boundaries', 'Dependency boundaries', 'verify-boundaries.mjs'],
  ['cycles', 'Cycles', 'verify-cycles.mjs'],
  ['typecheck', 'Typecheck', 'verify-typecheck.mjs'],
  ['dead-exports', 'Dead exports', 'verify-dead-exports.mjs'],
  ['unit-tests', 'Unit tests', 'verify-unit-tests.mjs'],
  ['test-coverage', 'Test coverage', 'verify-test-coverage.mjs'],
  ['build', 'Build', 'verify-build.mjs'],
  ['release-archive', 'Release archive', 'package-dist.mjs'],
];

export const FOCUSED_DIRECT_STEPS = [
  ['format', 'Format', 'verify-prettier.mjs'],
  ['oxlint', 'Oxlint', 'verify-oxlint.mjs'],
  ['eslint', 'ESLint', 'verify-eslint.mjs'],
  ['sonarjs', 'SonarJS', 'verify-sonarjs.mjs'],
  ['changed-line-readability', 'Changed-line readability', 'verify-line-length.mjs'],
  ['ai-limits', 'AI limits', 'verify-ai-limits.mjs'],
  ['mock-export-parity', 'Mock export parity', 'verify-manual-mock-export-parity.mjs'],
  ['security', 'Security', 'verify-security.mjs'],
  ['dead-exports', 'Dead exports', 'verify-dead-exports.mjs'],
  ['unit-tests', 'Unit tests', 'verify-unit-tests.mjs'],
  ['test-coverage', 'Test coverage', 'verify-test-coverage.mjs'],
];

export const FOCUSED_TRIGGERED_RUNTIME_STEPS = [
  ['config-policy', 'Config policy', 'verify-config-policy.mjs', 'conditional'],
];

export const HARNESS_STEPS = [
  ['format', 'Format', 'verify-prettier.mjs', 'always'],
  ['oxlint', 'Oxlint', 'verify-oxlint.mjs', 'always'],
  ['eslint', 'ESLint', 'verify-eslint.mjs', 'always'],
  ['changed-line-readability', 'Changed-line readability', 'verify-line-length.mjs', 'always'],
  ['ai-limits', 'AI limits', 'verify-ai-limits.mjs', 'always'],
  [
    'qa-rule-coverage-contract',
    'QA rule coverage contract',
    'verify-qa-rule-coverage-contract.mjs',
    'always',
  ],
  ['qa-control-inventory', 'QA control inventory', 'verify-qa-controls.mjs', 'always'],
  ['technical-debt-registry', 'Technical debt registry', 'verify-technical-debt.mjs', 'always'],
  ['retired-controls', 'Retired controls', 'retired-controls/validation.mjs', 'always'],
  ['dependency-admission', 'Dependency admission', 'verify-dependency-admission.mjs', 'always'],
  [
    'runtime-listener-ownership',
    'Runtime listener ownership',
    'verify-runtime-listener-seams.mjs',
    'always',
  ],
  ['typecheck', 'Typecheck', 'verify-typecheck.mjs', 'conditional'],
  ['unit-tests', 'Unit tests', 'verify-unit-tests.mjs', 'conditional'],
];

export const BUILD_STEPS = [
  ['naming', 'Naming', 'verify-naming.mjs'],
  ['security', 'Security', 'verify-security.mjs'],
  ['architecture-guardrails', 'Architecture guardrails', 'verify-architecture-guardrails.mjs'],
  ['dependency-boundaries', 'Dependency boundaries', 'verify-boundaries.mjs'],
  ['cycles', 'Cycles', 'verify-cycles.mjs'],
  ['canonical-facades', 'Canonical facades', 'verify-canonical-facades.mjs'],
  ['root-side-effects', 'Root side effects', 'verify-root-side-effects.mjs'],
  ['typecheck', 'Typecheck', 'verify-typecheck.mjs'],
  ['unit-tests', 'Unit tests', 'verify-unit-tests.mjs'],
  ['test-coverage', 'Test coverage', 'verify-test-coverage.mjs'],
  ['build', 'Build', 'verify-build.mjs'],
];

export const BUILD_COMMIT_STEPS = [
  ['stage-changes', 'Stage changes', 'git', 'conditional'],
  ['task-artifacts', 'Task artifacts', 'verify-task-artifacts.mjs', 'conditional'],
  [
    'pre-commit-diff-guard',
    'Pre-commit diff guard',
    'build.commit-steps.mjs',
    'conditional',
    'tooling/qa/wrappers/build.commit-steps.mjs',
  ],
  ['git-commit', 'Git commit', 'git', 'conditional'],
];

export const CLOSEOUT_STEPS = [
  [
    'qa-checkpoint',
    'QA checkpoint',
    'checkpoint.mjs',
    'conditional',
    'tooling/qa/wrappers/checkpoint.mjs',
  ],
  ['full-build', 'Full build', 'build.mjs', 'conditional', 'tooling/qa/wrappers/build.mjs'],
];

export const CANONICAL_WRAPPER_IDS = Object.freeze([
  'qa:preflight',
  'qa:advisory',
  'qa:checkpoint',
  'qa:closeout',
  'qa:build',
  'qa:release-harness',
  'qa:release',
  'qa:audit',
  'qa:e2e',
]);

export const WRAPPER_LIFECYCLE_STEPS = [
  [
    'wrapper-lifecycle',
    'Wrapper lifecycle',
    'run-controller.mjs',
    'conditional',
    'tooling/qa/runtime/observability/run-controller.mjs',
    CANONICAL_WRAPPER_IDS,
  ],
  [
    'wrapper-interruption',
    'Wrapper interruption',
    'run-controller.mjs',
    'conditional',
    'tooling/qa/runtime/observability/run-controller.mjs',
    CANONICAL_WRAPPER_IDS,
  ],
  [
    'wrapper-stale-run-recovery',
    'Wrapper stale-run recovery',
    'maintenance.mjs',
    'conditional',
    'tooling/qa/runtime/observability/maintenance.mjs',
    CANONICAL_WRAPPER_IDS,
  ],
  [
    'qa-preflight',
    'QA preflight',
    'preflight.mjs',
    'always',
    'tooling/qa/wrappers/preflight.mjs',
    ['qa:preflight'],
  ],
  [
    'qa-checkpoint',
    'QA checkpoint',
    'checkpoint.mjs',
    'conditional',
    'tooling/qa/wrappers/checkpoint.mjs',
    ['qa:closeout'],
  ],
  [
    'qa-build',
    'QA build',
    'build.mjs',
    'conditional',
    'tooling/qa/wrappers/build.mjs',
    ['qa:build'],
  ],
  [
    'qa-release-harness',
    'QA release harness',
    'release-harness.mjs',
    'conditional',
    'tooling/qa/wrappers/release-harness.mjs',
    ['qa:release-harness'],
  ],
  [
    'harness-qa',
    'Harness QA',
    'verify-harness.state.helpers.mjs',
    'conditional',
    'tooling/qa/core/harness-freshness-step.mjs',
    ['qa:checkpoint'],
  ],
  [
    'wrapper-help',
    'Wrapper help',
    'cli-contracts.mjs',
    'conditional',
    'tooling/qa/wrappers/cli-contracts.mjs',
    CANONICAL_WRAPPER_IDS,
  ],
  [
    'no-applicable-targets',
    'No applicable targets',
    'qa-scope.mjs',
    'conditional',
    'tooling/qa/core/qa-scope.mjs',
    CANONICAL_WRAPPER_IDS,
  ],
];

export const E2E_STEPS = [
  ['e2e-build', 'E2E build', 'vite', 'always', 'tooling/test/e2e/run-e2e.mjs'],
  ['playwright', 'Playwright', 'playwright', 'always', 'tooling/test/e2e/run-e2e.mjs'],
];

export const ADVISORY_STEPS = [
  ['advisory-report', 'Advisory report', 'verify-advisory.mjs', 'advisory'],
];

export const AUDIT_STEPS = [
  ['full-product-coverage', 'Full product coverage', 'verify-test-coverage.mjs'],
  ['audit-evidence', 'Audit evidence report-only inventory', 'evidence.mjs'],
  ['topology-report', 'Topology report-only inventory', 'verify-naming.mjs'],
  ['npm-audit', 'npm audit', 'npm-audit.mjs'],
  ['npm-audit-signatures', 'npm audit signatures', 'npm-audit-signatures.mjs'],
  ['osv-scanner', 'OSV-Scanner', 'osv.mjs'],
  ['gitleaks', 'Gitleaks', 'gitleaks.mjs'],
  ['license-inventory', 'License inventory', 'licenses.mjs'],
  ['ast-grep', 'ast-grep', 'ast-grep.mjs'],
  ['knip', 'Knip', 'knip.mjs'],
  ['jscpd', 'jscpd', 'jscpd.mjs'],
  ['semgrep', 'Semgrep', 'semgrep.mjs'],
  ['codeql', 'CodeQL', 'codeql.mjs'],
];

export const FULL_VIOLATION_STEP_TOOLS = new Map([
  ['Hotspot regression', 'verify-hotspot-regression.mjs'],
  ['Architecture guardrails', 'verify-architecture-guardrails.mjs'],
  ['Boundary casts', 'verify-boundary-casts.mjs'],
  ['Boundary inputs', 'verify-boundary-inputs.mjs'],
  ['Runtime protocol contracts', 'verify-runtime-protocol-contracts.mjs'],
  ['Runtime response privacy', 'verify-runtime-response-privacy.mjs'],
  ['ZIP package profile', 'verify-zip-package-profile.mjs'],
  ['Sniptale identity', 'verify-sniptale-identity.mjs'],
  ['Contract optionality drift', 'verify-contract-optionality-drift.mjs'],
  ['Messaging schema casts', 'verify-messaging-schema-casts.mjs'],
  ['Contract parser coverage', 'verify-contract-parser-coverage.mjs'],
  ['Network fetch policy', 'verify-network-fetch-policy.mjs'],
  ['Export artifact boundaries', 'verify-export-artifact-boundaries.mjs'],
  ['Backup import atomicity', 'verify-backup-import-atomicity.mjs'],
  ['Resource budget consistency', 'verify-resource-budget-consistency.mjs'],
  ['Resource lifecycle pairs', 'verify-resource-lifecycle-pairs.mjs'],
  ['State-machine proof', 'verify-state-machine-proof.mjs'],
  ['Hot-loop work', 'verify-hot-loop-work.mjs'],
  ['Runtime listener ownership', 'verify-runtime-listener-seams.mjs'],
  ['Entrypoint wiring', 'verify-entrypoint-wiring.mjs'],
  ['Logging policy', 'verify-logging.mjs'],
  ['Dependency admission', 'verify-dependency-admission.mjs'],
  ['Secret storage', 'verify-secret-storage.mjs'],
  ['Sensitive retention', 'verify-sensitive-retention.mjs'],
  ['Fetch ownership', 'verify-fetch-ownership.mjs'],
  ['Diagnostic sanitization', 'verify-diagnostic-sanitization.mjs'],
  ['Suppression directives', 'verify-suppression-directives.mjs'],
  ['Messaging', 'verify-messaging.mjs'],
  ['Root scatter', 'verify-root-scatter.mjs'],
  ['Read path side effects', 'verify-read-path-side-effects.mjs'],
  ['Read-safe naming', 'verify-read-safe-naming.mjs'],
  ['Lifecycle intent loss', 'verify-lifecycle-intent.mjs'],
  ['Success/failure asymmetry', 'verify-success-failure-asymmetry.mjs'],
  ['Destructive async swaps', 'verify-destructive-async-swaps.mjs'],
  ['Detached controller methods', 'verify-detached-controller-methods.mjs'],
  ['Storage write patterns', 'verify-storage-write-patterns.mjs'],
  ['Parser snapshot purity', 'verify-parser-snapshot-purity.mjs'],
  ['History revision semantics', 'verify-history-revision-semantics.mjs'],
  ['History detached snapshots', 'verify-history-detached-snapshots.mjs'],
  ['History transaction lifecycle', 'verify-history-transaction-lifecycle.mjs'],
  ['Manifest integrity', 'verify-manifest-integrity.mjs'],
  ['Manifest permissions', 'verify-manifest-permissions.mjs'],
  ['Runtime topology', 'verify-runtime-topology.mjs'],
  ['Package boundaries', 'verify-package-boundaries.mjs'],
  ['App-core owners', 'verify-app-core-owners.mjs'],
  ['Target-only paths', 'verify-target-only-paths.mjs'],
  ['OSS release surface', 'verify-oss-release-surface.mjs'],
  ['Shared UI boundaries', 'verify-shared-ui-boundaries.mjs'],
  ['Browser adapters', 'verify-browser-adapters.mjs'],
  ['Heavy runtime imports', 'verify-heavy-runtime-import-ownership.mjs'],
  ['Canonical facades', 'verify-canonical-facades.mjs'],
  ['Root side effects', 'verify-root-side-effects.mjs'],
  ['Shared style ownership', 'verify-shared-style-ownership.mjs'],
  ['Interface surfaces', 'verify-interface-surfaces.mjs'],
  ['Returned object surfaces', 'verify-interface-surfaces.mjs'],
  ['Multi-message transitions', 'verify-multi-message-transitions.mjs'],
  ['UI automation seams', 'verify-ui-automation-seams.mjs'],
  ['Interactive controller ownership', 'verify-instance-ownership.mjs'],
]);

export const FOCUSED_VIOLATION_STEP_TOOLS = new Map([
  ...FULL_VIOLATION_STEP_TOOLS,
  ['Domain fixture realism', 'verify-domain-fixture-realism.mjs'],
  ['Naming', 'verify-naming.mjs'],
]);
