import type {
  CalloutPreset,
  SystemCalloutPresetKey,
} from '@sniptale/runtime-contracts/highlighter/callout';
import { getShowcaseSurface, type ShowcaseSurfaceId } from '../showcase-resources';
import { createSolidPaint } from '@sniptale/foundation/paint';
import {
  BASE_CALLOUT_VISUAL_STYLE as baseStyle,
  cloneCalloutPreset,
  cloneCalloutVisualStyle,
} from './visual-style';
import {
  createSystemCalloutPreset as createSystemPreset,
  type SystemCalloutPreset,
} from './system-preset';

const surfacePaint = (id: ShowcaseSurfaceId) => getShowcaseSurface(id).fillPaint;

function createFrameBoundBodyBadgeStyle() {
  return {
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'body-start' as const,
      shape: 'circle' as const,
      backgroundColorSource: 'accent' as const,
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border' as const,
      connector: 'frame-border' as const,
      surfaceBorder: 'frame-border' as const,
    },
  };
}

const canonicalCatalog: readonly SystemCalloutPreset[] = [
  createSystemPreset('system-callout-bubble', 0, 'sniptale', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: false },
    badge: {
      ...baseStyle.badge,
      enabled: false,
      text: '',
      placement: 'title-end',
      backgroundColorSource: 'accent',
      textColor: '#0F172A',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      color: '#f97316',
      frameMarker: 'circle',
      kind: 'wedge',
      wedgeSize: 10,
    },
    customCss: '',
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-plain'),
      borderColor: '#f97316',
      borderWidth: 1,
      radius: 8,
      shadow: 12,
      textColor: '#0F172A',
    },
    title: {
      ...baseStyle.title,
      dividerColor: '#F97316',
      dividerWidth: 1,
      enabled: false,
      fillMode: 'unified',
      textColor: '#0F172A',
    },
    typography: { ...baseStyle.typography, maxWidth: 200 },
  }),
  createSystemPreset('system-callout-card', 1, 'sniptale', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-plain'),
      borderColor: '#F97316',
      borderWidth: 1,
      radius: 12,
      shadow: 16,
      textColor: '#0F172A',
    },
    title: { ...baseStyle.title, textColor: '#0F172A' },
  }),
  createSystemPreset('system-callout-text', 7, 'neon', {
    ...cloneCalloutVisualStyle(baseStyle),
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBackground: 'custom',
    },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'circle',
      kind: 'line',
      routing: 'curve',
      width: 2,
    },
    customCss: '[body]\ntext-shadow: 0 0 12px rgba(124, 58, 237, 0.2);',
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-clear-tint'),
      paddingX: 12,
      paddingY: 8,
      radius: 18,
      shadow: 12,
      textColor: '#0F172A',
    },
    title: { ...baseStyle.title, textColor: '#4C1D95' },
  }),
  createSystemPreset('system-callout-pointer-note', 3, 'paper', {
    ...cloneCalloutVisualStyle(baseStyle),
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      color: '#172033',
      frameMarker: 'ring-dot',
      frameMarkerSize: 11,
      kind: 'line',
      routing: 'polyline',
      width: 1,
    },
    customCss: [
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: 0.06em;',
      '[body]',
      'opacity: 0.82;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-tonal-cool'),
      paddingX: 8,
      paddingY: 6,
      radius: 0,
      shadow: 0,
      textColor: '#334155',
    },
    title: {
      ...baseStyle.title,
      dividerColor: '#172033',
      dividerWidth: 1,
      enabled: true,
      fillMode: 'unified',
      fontSize: 14,
      textColor: '#172033',
    },
    typography: { ...baseStyle.typography, fontSize: 12, maxWidth: 210 },
  }),
  createSystemPreset('system-callout-header-card', 6, 'neon', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'top', width: 3 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      shape: 'square',
      placement: 'title-end',
      backgroundColorSource: 'accent',
      textColor: '#020617',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      color: '#22D3EE',
      frameMarker: 'square',
      frameMarkerSize: 8,
      kind: 'line',
      routing: 'polyline',
      width: 2,
    },
    customCss: [
      '[card]',
      'outline-color: rgba(34, 211, 238, 0.44);',
      'outline-offset: 3px;',
      'outline-style: solid;',
      'outline-width: 1px;',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: 0.05em;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-acrylic-dark'),
      borderColor: '#22D3EE',
      borderWidth: 1,
      paddingX: 14,
      paddingY: 10,
      radius: 10,
      shadow: 28,
      textColor: '#E0F2FE',
    },
    title: {
      ...baseStyle.title,
      fillPaint: createSolidPaint('#D946EF'),
      dividerColor: '#22D3EE',
      dividerWidth: 2,
      enabled: true,
      fontSize: 14,
      textColor: '#020617',
    },
    typography: { ...baseStyle.typography, fontSize: 13, maxWidth: 240 },
  }),
  createSystemPreset('system-callout-framed-note', 4, 'paper', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: {
      ...baseStyle.accentEdge,
      color: '#D99000',
      enabled: true,
      side: 'left',
      width: 5,
    },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-end',
      backgroundColorSource: 'accent',
    },
    connector: {
      ...baseStyle.connector,
      color: '#8A5A00',
      frameMarker: 'diamond',
      frameMarkerSize: 9,
      kind: 'line',
      routing: 'polyline',
      width: 2,
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    customCss: [
      '[card]',
      'background-image: linear-gradient(135deg, rgba(15, 118, 110, 0.10), transparent 62%);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: 0.045em;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-tonal-warm'),
      borderColor: '#E8C56A',
      borderWidth: 1,
      paddingX: 14,
      paddingY: 9,
      radius: 3,
      shadow: 10,
      textColor: '#134E4A',
    },
    title: {
      ...baseStyle.title,
      dividerColor: '#0F766E',
      dividerWidth: 2,
      enabled: true,
      fontSize: 14,
      textColor: '#134E4A',
    },
    typography: { ...baseStyle.typography, fontSize: 13, maxWidth: 230 },
  }),
  createSystemPreset('system-callout-ribbon', 2, 'sniptale', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'top', width: 5 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-start',
      shape: 'rounded',
      backgroundColorSource: 'accent',
      textColor: '#4C0519',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      shadow: 'surface-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      blockMarker: 'circle',
      frameMarker: 'arrow',
      kind: 'line',
      routing: 'curve',
      width: 3,
    },
    customCss: [
      '[card]',
      'box-shadow: 0 18px 38px rgba(67,20,7,.18);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: 0.08em;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-soft-elevated'),
      borderColor: '#FB7185',
      borderWidth: 2,
      paddingX: 16,
      paddingY: 11,
      radius: 18,
      shadow: 28,
      textColor: '#431407',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fillPaint: surfacePaint('system-surface-liquid-glow'),
      dividerColor: '#FB7185',
      dividerWidth: 2,
      textColor: '#9F1239',
    },
    typography: { ...baseStyle.typography, fontSize: 13, maxWidth: 250 },
  }),
  createSystemPreset('system-callout-sticky', 5, 'paper', {
    ...cloneCalloutVisualStyle(baseStyle),
    ...createFrameBoundBodyBadgeStyle(),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'bottom', width: 3 },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'diamond',
      blockMarker: 'circle',
      kind: 'line',
      routing: 'elbow',
      cornerStyle: { kind: 'rounded', radius: 10 },
      width: 2,
    },
    customCss: '[card]\nbox-shadow: 3px 5px 0 rgba(120,53,15,.14);\n[body]\nfont-style: italic;',
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-mica'),
      borderColor: '#92400E',
      borderStyle: 'dashed',
      borderWidth: 2,
      paddingX: 15,
      paddingY: 12,
      radius: 3,
      shadow: 16,
      textColor: '#422006',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fillMode: 'unified',
      fontFamily: 'serif',
      fontStyle: 'italic',
      dividerColor: '#92400E',
      dividerStyle: 'dashed',
      dividerWidth: 1,
      textColor: '#422006',
    },
    typography: { ...baseStyle.typography, fontFamily: 'serif', maxWidth: 230 },
  }),
  createSystemPreset('system-callout-terminal', 8, 'neon', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'left', width: 3 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-end',
      shape: 'square',
      backgroundColorSource: 'accent',
      textColor: '#020617',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'square',
      blockMarker: 'arrow',
      kind: 'line',
      routing: 'elbow',
      lineStyle: 'dotted',
      width: 2,
    },
    customCss: [
      '[card]',
      'box-shadow: 0 0 0 1px rgba(34,211,238,.45), 0 0 30px rgba(34,211,238,.22);',
      '[body]',
      'text-shadow: 0 0 9px rgba(34,211,238,.45);',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-frosted-dark'),
      borderColor: '#22D3EE',
      borderWidth: 1,
      paddingX: 14,
      paddingY: 10,
      radius: 5,
      shadow: 30,
      textColor: '#CFFAFE',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fillMode: 'unified',
      fontFamily: 'mono',
      dividerColor: '#22D3EE',
      dividerStyle: 'dotted',
      dividerWidth: 1,
      textColor: '#67E8F9',
    },
    typography: { ...baseStyle.typography, fontFamily: 'mono', fontSize: 12, maxWidth: 250 },
  }),
  createSystemPreset('system-callout-editorial-caption', 9, 'editorial', {
    ...cloneCalloutVisualStyle(baseStyle),
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'circle',
      kind: 'line',
      routing: 'straight',
      width: 1,
    },
    customCss:
      '[title]\ntext-transform: uppercase;\nletter-spacing: 0.12em;\n[body]\nletter-spacing: 0.015em;',
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-frosted-light'),
      borderColor: '#111827',
      borderWidth: 1,
      paddingX: 12,
      paddingY: 9,
      radius: 0,
      shadow: 8,
      textColor: '#171717',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fillMode: 'unified',
      fontFamily: 'serif',
      fontSize: 12,
      dividerColor: '#111827',
      dividerWidth: 1,
      textColor: '#111827',
    },
    typography: { ...baseStyle.typography, fontFamily: 'serif', fontSize: 13, maxWidth: 260 },
  }),
  createSystemPreset('system-callout-editorial-quote', 10, 'editorial', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'left', width: 7 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-start',
      shape: 'square',
      backgroundColorSource: 'accent',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      shadow: 'surface-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'ring-dot',
      blockMarker: 'diamond',
      kind: 'line',
      routing: 'polyline',
      width: 2,
    },
    customCss: [
      '[card]',
      'box-shadow: 7px 7px 0 rgba(10,10,10,.12);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: .1em;',
      '[body]',
      'font-style: italic;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-acrylic-light'),
      borderColor: '#0A0A0A',
      borderWidth: 2,
      paddingX: 18,
      paddingY: 13,
      radius: 0,
      shadow: 0,
      textColor: '#0A0A0A',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fontFamily: 'serif',
      fontSize: 15,
      dividerColor: '#0A0A0A',
      dividerWidth: 3,
      textColor: '#0A0A0A',
    },
    typography: {
      ...baseStyle.typography,
      fontFamily: 'serif',
      fontSize: 15,
      lineHeight: 1.55,
      maxWidth: 290,
    },
  }),
  createSystemPreset('system-callout-editorial-proof', 11, 'editorial', {
    ...cloneCalloutVisualStyle(baseStyle),
    ...createFrameBoundBodyBadgeStyle(),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'right', width: 2 },
    connector: {
      ...baseStyle.connector,
      frameMarker: 'arrow',
      blockMarker: 'circle',
      kind: 'line',
      routing: 'curve',
      lineStyle: 'dashed',
      width: 1,
    },
    customCss: [
      '[card]',
      'box-shadow: 2px 3px 0 rgba(23,23,23,.16);',
      '[title]',
      'text-decoration: underline;',
      '[body]',
      'font-family: ui-monospace, monospace;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-liquid-glow'),
      borderColor: '#525252',
      borderStyle: 'dotted',
      borderWidth: 2,
      paddingX: 14,
      paddingY: 10,
      radius: 2,
      shadow: 6,
      textColor: '#171717',
    },
    title: {
      ...baseStyle.title,
      enabled: true,
      fontFamily: 'mono',
      dividerColor: '#525252',
      dividerStyle: 'dotted',
      dividerWidth: 1,
      textColor: '#171717',
    },
    typography: { ...baseStyle.typography, fontFamily: 'mono', fontSize: 12, maxWidth: 250 },
  }),
  createSystemPreset('system-callout-retro-sunset', 12, 'retro80s', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'top', width: 5 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-end',
      shape: 'rounded',
      backgroundColorSource: 'accent',
      textColor: '#020617',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      blockMarker: 'circle',
      frameMarker: 'ring-dot',
      kind: 'line',
      routing: 'curve',
      width: 3,
    },
    customCss: [
      '[card]',
      'box-shadow: 0 0 34px rgba(244,114,182,.38);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: .12em;',
      '[body]',
      'text-shadow: 0 0 10px rgba(34,211,238,.4);',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-acrylic-dark'),
      borderColor: '#F472B6',
      borderWidth: 2,
      paddingX: 16,
      paddingY: 11,
      radius: 3,
      shadow: 32,
      textColor: '#CFFAFE',
    },
    title: {
      ...baseStyle.title,
      fillPaint: createSolidPaint('#4C1D95'),
      dividerColor: '#22D3EE',
      dividerWidth: 2,
      enabled: true,
      fontStyle: 'italic',
      textColor: '#FFFFFF',
    },
    typography: { ...baseStyle.typography, maxWidth: 250 },
  }),
  createSystemPreset('system-callout-retro-arcade', 13, 'retro80s', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'left', width: 4 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'body-start',
      shape: 'square',
      backgroundColorSource: 'accent',
      textColor: '#020617',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      blockMarker: 'square',
      frameMarker: 'square',
      kind: 'line',
      lineStyle: 'dotted',
      routing: 'elbow',
      width: 2,
    },
    customCss: [
      '[card]',
      'box-shadow: 4px 4px 0 rgba(168,85,247,.65);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: .08em;',
      '[body]',
      'font-family: ui-monospace, monospace;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-ink'),
      borderColor: '#A3E635',
      borderStyle: 'dashed',
      borderWidth: 2,
      paddingX: 14,
      paddingY: 10,
      radius: 0,
      shadow: 26,
      textColor: '#ECFCCB',
    },
    title: {
      ...baseStyle.title,
      dividerColor: '#A855F7',
      dividerStyle: 'dotted',
      dividerWidth: 2,
      enabled: true,
      fillMode: 'unified',
      fontFamily: 'mono',
      textColor: '#A3E635',
    },
    typography: { ...baseStyle.typography, fontFamily: 'mono', fontSize: 12, maxWidth: 240 },
  }),
  createSystemPreset('system-callout-retro-memphis', 14, 'retro80s', {
    ...cloneCalloutVisualStyle(baseStyle),
    accentEdge: { ...baseStyle.accentEdge, enabled: true, side: 'right', width: 7 },
    badge: {
      ...baseStyle.badge,
      enabled: true,
      text: '',
      placement: 'title-start',
      shape: 'circle',
      backgroundColor: '#FACC15',
      backgroundColorSource: 'custom',
      textColor: '#111827',
    },
    colorBindings: {
      ...baseStyle.colorBindings,
      accent: 'frame-border',
      connector: 'frame-border',
      shadow: 'surface-border',
      surfaceBorder: 'frame-border',
    },
    connector: {
      ...baseStyle.connector,
      blockMarker: 'diamond',
      frameMarker: 'arrow',
      kind: 'line',
      routing: 'polyline',
      width: 3,
    },
    customCss: [
      '[card]',
      'background-image: linear-gradient(135deg, transparent 56%, rgba(20,184,166,.22) 56%);',
      'box-shadow: 7px 7px 0 rgba(17,24,39,.22);',
      '[title]',
      'text-transform: uppercase;',
      'letter-spacing: .09em;',
    ].join('\n'),
    surface: {
      ...baseStyle.surface,
      fillPaint: surfacePaint('system-surface-tonal-warm'),
      borderColor: '#111827',
      borderWidth: 3,
      paddingX: 17,
      paddingY: 12,
      radius: 16,
      shadow: 14,
      textColor: '#111827',
    },
    title: {
      ...baseStyle.title,
      fillPaint: createSolidPaint('#F472B6'),
      dividerColor: '#111827',
      dividerWidth: 3,
      enabled: true,
      textColor: '#111827',
    },
    typography: { ...baseStyle.typography, fontWeight: 'bold', maxWidth: 255 },
  }),
];

export function createSystemCalloutPresetCatalog(): CalloutPreset[] {
  return canonicalCatalog.map(cloneCalloutPreset).sort((left, right) => left.order - right.order);
}

export function getCanonicalSystemCalloutPreset(key: SystemCalloutPresetKey): SystemCalloutPreset {
  return cloneCalloutPreset(
    canonicalCatalog.find((preset) => preset.systemPresetKey === key)!
  ) as SystemCalloutPreset;
}
