import { vi } from 'vitest';

const selectionMocks = vi.hoisted(() => ({
  applyLayerEffectForController: vi.fn(async () => undefined),
  applyLayerTransformationForController: vi.fn(async () => undefined),
  applySelectionSettingsForController: vi.fn(),
  applyTextSelectionStyleForController: vi.fn(() => true),
  bringForwardSelectionForController: vi.fn(),
  bringSelectionToFrontForController: vi.fn(),
  deleteSelectionForController: vi.fn(),
  duplicateSelectionForController: vi.fn(async () => undefined),
  finalizeSelectionNudgeForController: vi.fn(),
  insertImageForController: vi.fn(async () => undefined),
  insertRichShapeForController: vi.fn(),
  insertTechnicalDataForController: vi.fn(),
  mergeSelectedLayersForController: vi.fn(async () => undefined),
  nudgeSelectionForController: vi.fn(() => true),
  previewSelectionSettingsForController: vi.fn(),
  redoForController: vi.fn(async () => undefined),
  removeLayerEffectForController: vi.fn(),
  renameLayerForController: vi.fn(),
  reorderLayerForController: vi.fn(),
  resetToOriginalForController: vi.fn(async () => undefined),
  resizeLayerForController: vi.fn(),
  sendBackwardSelectionForController: vi.fn(),
  sendSelectionToBackForController: vi.fn(),
  selectLayerForController: vi.fn(),
  toggleLayerLockForController: vi.fn(),
  toggleLayerVisibilityForController: vi.fn(),
  undoForController: vi.fn(async () => undefined),
  updateLayerEffectForController: vi.fn(async () => undefined),
}));

export function getSelectionMocks() {
  return selectionMocks;
}

vi.mock('../../instance/actions/selection', () => ({
  applyLayerEffectForController: selectionMocks.applyLayerEffectForController,
  applyLayerTransformationForController: selectionMocks.applyLayerTransformationForController,
  applySelectionSettingsForController: selectionMocks.applySelectionSettingsForController,
  applyTextSelectionStyleForController: selectionMocks.applyTextSelectionStyleForController,
  bringForwardSelectionForController: selectionMocks.bringForwardSelectionForController,
  bringSelectionToFrontForController: selectionMocks.bringSelectionToFrontForController,
  deleteSelectionForController: selectionMocks.deleteSelectionForController,
  duplicateSelectionForController: selectionMocks.duplicateSelectionForController,
  finalizeSelectionNudgeForController: selectionMocks.finalizeSelectionNudgeForController,
  insertImageForController: selectionMocks.insertImageForController,
  insertRichShapeForController: selectionMocks.insertRichShapeForController,
  insertTechnicalDataForController: selectionMocks.insertTechnicalDataForController,
  mergeSelectedLayersForController: selectionMocks.mergeSelectedLayersForController,
  nudgeSelectionForController: selectionMocks.nudgeSelectionForController,
  previewLayerEffectForController: selectionMocks.applyLayerEffectForController,
  previewSelectionSettingsForController: selectionMocks.previewSelectionSettingsForController,
  redoForController: selectionMocks.redoForController,
  removeLayerEffectForController: selectionMocks.removeLayerEffectForController,
  renameLayerForController: selectionMocks.renameLayerForController,
  reorderLayerForController: selectionMocks.reorderLayerForController,
  resetLayerEffectPreviewForController: selectionMocks.removeLayerEffectForController,
  resetToOriginalForController: selectionMocks.resetToOriginalForController,
  resizeLayerForController: selectionMocks.resizeLayerForController,
  sendBackwardSelectionForController: selectionMocks.sendBackwardSelectionForController,
  sendSelectionToBackForController: selectionMocks.sendSelectionToBackForController,
  selectLayerForController: selectionMocks.selectLayerForController,
  toggleLayerLockForController: selectionMocks.toggleLayerLockForController,
  toggleLayerVisibilityForController: selectionMocks.toggleLayerVisibilityForController,
  undoForController: selectionMocks.undoForController,
  updateLayerEffectForController: selectionMocks.updateLayerEffectForController,
}));
