export const QA_LABELS_BY_DOMAIN = {
  architecture: new Set([
    'App-core owners',
    'Architecture guardrails',
    'Browser adapters',
    'Config policy',
    'Dependency boundaries',
    'Design system',
    'Entrypoint wiring',
    'Forwarding module drift',
    'Heavy runtime imports',
    'i18n',
    'Manifest integrity',
    'Manifest permissions',
    'Messaging',
    'Package boundaries',
    'Root side effects',
    'Runtime topology',
    'Shared style ownership',
    'Target-only paths',
    'UI automation seams',
    'ZIP package profile',
  ]),
  lifecycle: new Set([
    'Interactive controller ownership',
    'Parser snapshot purity',
    'Persistence ownership',
  ]),
  maintainability: new Set([
    'AI hygiene',
    'Changed-line readability',
    'Detached controller methods',
    'Structural risk',
    'Structural audit',
    'Naming',
    'Read path side effects',
    'Root scatter',
  ]),
  security: new Set([
    'Dependency admission',
    'Diagnostic sanitization',
    'Fetch ownership',
    'Network fetch policy',
    'OSS release surface',
    'Secret storage',
    'HTML sanitizer ownership',
    'Sensitive retention',
    'Suppression directives',
  ]),
};
