import type { BackgroundIngressRouteGroupData } from './background-ingress.types';

export const backgroundIngressTabRouteGroups = [
  {
    acceptedSenderClass: 'owned content tab or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:tab-mode',
    boundary: 'background-runtime',
    errorShape: 'tab-mode route error response',
    freshnessReplayPolicy:
      'resolved tab/frame/document state plus one-shot trusted intent scopes content surface enable',
    handlerId: 'tab-mode',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/runtime/tab-mode-router/router.ts',
    policyAuthorityFamily: 'tab-mode-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
      'tab-mode-runtime-state',
    ],
    requiredAuthority:
      'privileged tab mode authorization policy and trusted content intent for content surface enable',
    responseShape: 'tab-mode route response',
    routeAuthorityFamily: 'tab-mode-privileged-tab-route',
    sideEffects: 'content overlay mode, viewport, or highlighter runtime changes',
    transitiveStateOwner: 'background tab-mode route owner',
    messageTypes: [
      'ENABLE_SCREENSHOT_MODE',
      'DISABLE_SCREENSHOT_MODE',
      'SCREENSHOT_MODE_STATUS',
      'ENABLE_HIGHLIGHTER_MODE',
      'DISABLE_HIGHLIGHTER_MODE',
      'HIGHLIGHTER_MODE_STATUS',
      'ENABLE_QUICK_EDIT_MODE',
      'DISABLE_QUICK_EDIT_MODE',
      'QUICK_EDIT_MODE_STATUS',
      'APPLY_VIEWPORT_PRESET',
      'RELEASE_VIEWPORT_PRESET',
      'GET_VIEWPORT_PRESET_AVAILABILITY',
      'GET_VIEWPORT_STATUS',
    ],
  },
  {
    acceptedSenderClass: 'active content tab, scenario viewer, or scenario editor owner',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:scenario',
    boundary: 'background-runtime',
    errorShape: 'scenario route error response',
    freshnessReplayPolicy: 'tab id, project/session identity, and revision freshness scope writes',
    handlerId: 'scenario',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/scenario/router/index.ts',
    policyAuthorityFamily: 'scenario-privileged-tab-route',
    policyStateIds: ['tab-mode-runtime-state'],
    requiredAuthority: 'privileged tab scenario authorization policy',
    responseShape: 'scenario route response',
    routeAuthorityFamily: 'scenario-privileged-tab-route',
    sideEffects: 'scenario session, project, capture, editor-open, or event persistence effects',
    transitiveStateOwner: 'background scenario router and scenario session-service owners',
    messageTypes: [
      'SCENARIO_GET_SESSION',
      'SCENARIO_GET_RESTORE_SNAPSHOT',
      'SCENARIO_SET_ENABLED',
      'SCENARIO_SET_CAPTURE_MODE',
      'SCENARIO_SET_SIDEBAR_VISIBLE',
      'SCENARIO_UPDATE_SURFACE_STATE',
      'SCENARIO_UPDATE_SESSION_PREFS',
      'SCENARIO_SET_ACTIVE_PROJECT',
      'SCENARIO_LIST_PROJECTS',
      'SCENARIO_CREATE_PROJECT',
      'SCENARIO_SAVE_CAPTURE_STEP',
      'SCENARIO_DELETE_STEP',
      'SCENARIO_MOVE_STEP',
      'SCENARIO_RECORD_SUGGESTED_EVENT',
      'SCENARIO_OPEN_EDITOR',
      'SCENARIO_RESTORE_STEP',
    ],
  },
  {
    acceptedSenderClass: 'popup or viewer route presenting one-shot tab-route capability',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'popup-export-tab-route',
    boundary: 'background-runtime',
    errorShape: 'popup export tab route error response',
    freshnessReplayPolicy: 'capability binds tab id, operation, request id, and expiry',
    handlerId: 'popup-export',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/runtime/routing/boundary/popup-export-routing.ts',
    policyAuthorityFamily: 'popup-export-tab-route-capability',
    policyStateIds: ['popup-tab-route-capabilities'],
    requiredAuthority: 'popup export tab-route capability',
    responseShape: 'popup export route response',
    routeAuthorityFamily: 'popup-export-tab-route-capability',
    sideEffects: 'page parsing, snapshot packaging, media-hub write, export build, or cancellation',
    transitiveStateOwner: 'popup export routing and web snapshot owners',
    messageTypes: [
      'EXPORT_POPUP_PREVIEW',
      'EXPORT_POPUP_BUILD_PACKAGE',
      'CONSUME_POPUP_EXPORT_LAUNCH_INTENT',
    ],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/route/screenshot-adapter.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: [
      'CAPTURE_VISIBLE',
      'CAPTURE_VISIBLE_FOR_CROP',
      'CAPTURE_FULL',
      'RENEW_SCREENSHOT_SURFACE_SESSION',
    ],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/annotation-export/route.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: ['DOWNLOAD_BROWSER_ANNOTATIONS', 'OPEN_EXPORT_MODAL'],
  },
  {
    acceptedSenderClass: 'owned content tab or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'quick-action tab route error response',
    freshnessReplayPolicy: 'trusted local action intent and resolved tab/frame/document must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/actions.quick-action.ts',
    policyAuthorityFamily: 'quick-action-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'privileged tab quick-action authorization policy',
    responseShape: 'quick-action route response',
    routeAuthorityFamily: 'quick-action-privileged-tab-route',
    sideEffects: 'quick capture or editor action side effects',
    transitiveStateOwner: 'background capture quick-action owner',
    messageTypes: [
      'TRIGGER_QUICK_ACTION',
      'PREPARE_DESKTOP_SCREENSHOT_CAPTURE',
      'TRIGGER_SCREENSHOT_CAPTURE',
    ],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/actions.download.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
      'recent-capture-editor-asset-binding',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: ['EXECUTE_SAVE', 'OPEN_EDITOR_WITH_IMAGE'],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/actions.export.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: ['EXPORT_CAPTURE_FULL_PAGE'],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/actions.gallery-update.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
      'recent-capture-editor-asset-binding',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: ['SAVE_SCREENSHOT_TO_GALLERY'],
  },
  {
    acceptedSenderClass: 'owned content tab, popup, or extension page routed to an authorized tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:capture',
    boundary: 'background-runtime',
    errorShape: 'tab route error response through capture/background router',
    freshnessReplayPolicy: 'resolved tab, frame, document, or capability must match',
    handlerId: 'capture',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/capture/routing/actions.web-snapshot.ts',
    policyAuthorityFamily: 'capture-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'privileged tab capture authorization policy',
    responseShape: 'capture/tab route response contract',
    routeAuthorityFamily: 'capture-privileged-tab-route',
    sideEffects:
      'screenshot capture, editor open, annotation or staged download, popup launch, gallery, or web snapshot',
    transitiveStateOwner: 'capture routing and media-hub storage owners',
    messageTypes: [
      'REGISTER_WEB_SNAPSHOT_ASSETS',
      'FETCH_WEB_SNAPSHOT_ASSET',
      'STAGE_PAGE_PACKAGE_JOB_CHUNK',
      'WEB_SNAPSHOT_SAVE_PROGRESS_UPDATED',
    ],
  },
  {
    acceptedSenderClass: 'video editor or authorized extension page routed to recording tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [
      'video-control-camera-recorder-route',
      'video-control-no-tab-route',
      'video-control-owner-no-tab-route',
    ],
    alternateAuthorityFamilies: [
      'video-control-camera-recorder-route',
      'video-control-no-tab-route',
      'video-control-owner-no-tab-route',
    ],
    authorizationPolicyId: 'privileged-tab-route:video-control',
    boundary: 'background-runtime',
    errorShape: 'video control route error response',
    freshnessReplayPolicy: 'recording lease, owner tab/document, generation, and TTL must match',
    handlerId: 'video-control',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/media/video/runtime/manager/control-route.ts',
    policyAuthorityFamily: 'video-control-privileged-tab-route',
    policyStateIds: ['video-recording-control-lease'],
    requiredAuthority: 'privileged tab video-control authorization policy',
    responseShape: 'video recording control response',
    routeAuthorityFamily: 'video-control-privileged-tab-route',
    sideEffects:
      'recording start, start cancellation, stop, pause, resume, live settings, and session state updates',
    transitiveStateOwner: 'background video runtime recording owner',
    messageTypes: [
      'START_RECORDING',
      'CANCEL_RECORDING_START',
      'STOP_RECORDING',
      'PAUSE_RECORDING',
      'RESUME_RECORDING',
      'UPDATE_SETTINGS',
    ],
  },
  {
    acceptedSenderClass: 'owned top-frame content document bound to its tab',
    actionKind: 'tab',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'privileged-tab-route:video-recording-surface',
    boundary: 'background-runtime',
    errorShape: 'video recording surface route error response',
    freshnessReplayPolicy:
      'one-shot trusted intent for entry plus surface token, tab, document generation, capability epoch, and recording id for commands',
    handlerId: 'video-recording-surface',
    keepChannelBehaviorSource: 'tab-routing-adapter',
    ownerModule: 'apps/extension/src/background/media/video/content-surface/route.ts',
    policyAuthorityFamily: 'video-recording-surface-privileged-tab-route',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
      'video-recording-control-lease',
      'video-recording-surface-lease',
    ],
    requiredAuthority: 'video recording surface privileged tab authorization policy',
    responseShape: 'surface activation, snapshot, or command response',
    routeAuthorityFamily: 'video-recording-surface-privileged-tab-route',
    sideEffects:
      'saved tab recording start, content surface binding, recording controls, or embedded camera settings',
    transitiveStateOwner:
      'background video content-surface lease and recording-control lease owners',
    messageTypes: [
      'START_SAVED_TAB_VIDEO_RECORDING',
      'ACTIVATE_VIDEO_RECORDING_SURFACE',
      'RELEASE_VIDEO_RECORDING_SURFACE',
      'VIDEO_RECORDING_SURFACE_COMMAND',
      'VIDEO_RECORDING_CAMERA_OFFER',
      'VIDEO_RECORDING_CAMERA_CLOSE',
    ],
  },
] as const satisfies readonly BackgroundIngressRouteGroupData[];
