import type { BackgroundIngressRouteGroupData } from './background-ingress.types';

export const backgroundIngressVideoRouteGroups = [
  {
    acceptedSenderClass: 'video editor owner, background video owner, or authorized runtime sender',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'owner-local:video-runtime-owner-policy',
    boundary: 'background-runtime',
    errorShape: 'video runtime route error response',
    freshnessReplayPolicy:
      'video runtime owner policy and recording/export ids reject stale messages',
    handlerId: 'video-runtime',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule: 'apps/extension/src/background/media/video/runtime/router.ts',
    policyAuthorityFamily: 'video-runtime-owner-policy',
    policyStateIds: [],
    requiredAuthority: 'video runtime owner policy',
    responseShape: 'video runtime route response',
    routeAuthorityFamily: 'video-runtime-owner-policy',
    sideEffects: 'video runtime state reads, capture source handoff, or owner-local state changes',
    transitiveStateOwner: 'background video runtime owner',
    messageTypes: [
      'GET_RECORDING_STATE',
      'ACKNOWLEDGE_POST_RECORD_RESULT',
      'REGISTER_CAMERA_RECORDER_CONTROL',
      'GET_RECORDING_TAB_ID',
    ],
  },
  {
    acceptedSenderClass: 'authorized offscreen document or background video owner',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'offscreen-runtime',
    boundary: 'background-runtime',
    errorShape: 'video runtime error response',
    freshnessReplayPolicy:
      'offscreen capability, runtime generation, and command idempotency gate writes',
    handlerId: 'video-runtime',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule:
      'apps/extension/src/background/media/video/runtime/handlers/state/offscreen-lifecycle.ts',
    policyAuthorityFamily: 'offscreen-runtime-capability',
    policyStateIds: [
      'project-export-capabilities',
      'project-export-job-ledger',
      'video-recording-control-lease',
    ],
    requiredAuthority: 'offscreen runtime sender capability',
    responseShape: 'video runtime route response',
    routeAuthorityFamily: 'offscreen-runtime-capability',
    sideEffects: 'recording, project export, download, or offscreen lifecycle state mutation',
    transitiveStateOwner: 'background video runtime and offscreen runtime owners',
    messageTypes: [
      'RECORDING_DURATION_UPDATED',
      'OFFSCREEN_RECORDING_STARTED',
      'OFFSCREEN_SOURCE_READY',
      'OFFSCREEN_RECORDING_STOPPED',
      'OFFSCREEN_RECORDING_PAUSED',
      'OFFSCREEN_RECORDING_RESUMED',
      'OFFSCREEN_ERROR',
      'VIDEO_SAVED_TO_IDB',
      'OFFSCREEN_READY',
      'DESKTOP_MEDIA_OBTAINED',
      'DESKTOP_MEDIA_CANCELLED',
      'DESKTOP_MEDIA_FAILED',
      'PROJECT_EXPORT_PROGRESS',
      'PROJECT_EXPORT_COMPLETED',
      'PROJECT_EXPORT_FAILED',
      'PROJECT_EXPORT_CANCELLED',
    ],
  },
  {
    acceptedSenderClass: 'video editor owner, background video owner, or authorized runtime sender',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'owner-local:video-runtime-owner-policy',
    boundary: 'background-runtime',
    errorShape: 'video runtime route error response',
    freshnessReplayPolicy:
      'video runtime owner policy and recording/export ids reject stale messages',
    handlerId: 'video-runtime',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule:
      'apps/extension/src/background/media/video/runtime/handlers/state/offscreen-lifecycle.ts',
    policyAuthorityFamily: 'video-runtime-owner-policy',
    policyStateIds: [],
    requiredAuthority: 'video runtime owner policy',
    responseShape: 'video runtime route response',
    routeAuthorityFamily: 'video-runtime-owner-policy',
    sideEffects: 'video runtime state reads, capture source handoff, or owner-local state changes',
    transitiveStateOwner: 'background video runtime owner',
    messageTypes: ['CAPTURE_SOURCE_OBTAINED'],
  },
  {
    acceptedSenderClass: 'video editor owner presenting project-export start/cancel authority',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'project-export-runtime',
    boundary: 'background-runtime',
    errorShape: 'project export authorization or route error response',
    freshnessReplayPolicy: 'capability binds job, project, owner document/url, purpose, and TTL',
    handlerId: 'project-export-runtime',
    keepChannelBehaviorSource: 'video-runtime-project-export-authority',
    ownerModule:
      'apps/extension/src/background/media/video/runtime/handlers/export/project-export.ts',
    policyAuthorityFamily: 'project-export-capability',
    policyStateIds: ['project-export-capabilities', 'project-export-job-ledger'],
    requiredAuthority: 'project export start/cancel preauthorization',
    responseShape: 'project export start/cancel route response',
    routeAuthorityFamily: 'project-export-capability',
    sideEffects: 'project export ledger reservation, offscreen export start, or cancel request',
    transitiveStateOwner: 'video export ledger and project-export handler owners',
    messageTypes: ['START_PROJECT_EXPORT', 'CANCEL_PROJECT_EXPORT'],
  },
  {
    acceptedSenderClass: 'video editor owner requesting project-export capabilities',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'owner-local:project-export-capability-issuance',
    boundary: 'background-runtime',
    errorShape: 'project export capability issuance error response',
    freshnessReplayPolicy: 'active ledger owner and requested project/job identity gate issuance',
    handlerId: 'project-export-capabilities',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule:
      'apps/extension/src/background/media/video/runtime/handlers/export/project-export.ts',
    policyAuthorityFamily: 'project-export-capability-issuance',
    policyStateIds: [],
    requiredAuthority: 'project export capability issuer',
    responseShape: 'project export capability grant response',
    routeAuthorityFamily: 'project-export-capability-issuance',
    sideEffects: 'issues or reissues owner-scoped project export controls',
    transitiveStateOwner: 'video export ledger capability owner',
    messageTypes: ['GET_PROJECT_EXPORT_CAPABILITIES'],
  },
  {
    acceptedSenderClass: 'authorized offscreen document or background video owner',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'offscreen-runtime',
    boundary: 'background-runtime',
    errorShape: 'video runtime error response',
    freshnessReplayPolicy:
      'offscreen capability, runtime generation, and command idempotency gate writes',
    handlerId: 'video-runtime',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule: 'apps/extension/src/background/media/video/runtime/handlers/export/download.ts',
    policyAuthorityFamily: 'offscreen-runtime-capability',
    policyStateIds: [
      'project-export-capabilities',
      'project-export-job-ledger',
      'video-recording-control-lease',
    ],
    requiredAuthority: 'offscreen runtime sender capability',
    responseShape: 'video runtime route response',
    routeAuthorityFamily: 'offscreen-runtime-capability',
    sideEffects: 'recording, project export, download, or offscreen lifecycle state mutation',
    transitiveStateOwner: 'background video runtime and offscreen runtime owners',
    messageTypes: ['DOWNLOAD_PROJECT_EXPORT', 'DOWNLOAD_RECORDING_SIDECAR', 'DOWNLOAD_RECORDING'],
  },
  {
    acceptedSenderClass: 'owned content runtime for diagnostics events',
    actionKind: 'video-runtime',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'owner-local:diagnostic-content-runtime',
    boundary: 'background-runtime',
    errorShape: 'diagnostics route error response',
    freshnessReplayPolicy: 'sender tab authority and diagnostics session identity gate writes',
    handlerId: 'video-runtime',
    keepChannelBehaviorSource: 'video-runtime-router-result',
    ownerModule: 'apps/extension/src/background/diagnostics/handlers.ts',
    policyAuthorityFamily: 'diagnostic-content-runtime',
    policyStateIds: [],
    requiredAuthority: 'diagnostic content runtime sender policy',
    responseShape: 'diagnostics event acknowledgement',
    routeAuthorityFamily: 'diagnostic-content-runtime',
    sideEffects: 'sanitized diagnostics event persistence or session update',
    transitiveStateOwner: 'background diagnostics owner',
    messageTypes: ['DIAGNOSTIC_EVENT_FROM_CS'],
  },
] as const satisfies readonly BackgroundIngressRouteGroupData[];
