import type { BackgroundIngressRouteGroupData } from './background-ingress.types';

export const backgroundIngressBackgroundOwnedRouteGroups = [
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'aggregate-promotion',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/application/aggregate-promotion/route.ts',
    policyAuthorityFamily: 'aggregate-promotion-authority',
    policyStateIds: ['aggregate-editor-presence'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['PROMOTE_AGGREGATE_TO_LIBRARY'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'llm-session',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/llm/session-route.ts',
    policyAuthorityFamily: 'llm-session-issuance',
    policyStateIds: ['llm-session-tokens'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['REQUEST_LLM_SESSION'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'ai-settings-query',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/settings/query-route.ts',
    policyAuthorityFamily: 'ai-settings-query-authority',
    policyStateIds: [],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['AI_SETTINGS_QUERY'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'ai-settings-mutation',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/settings/route.ts',
    policyAuthorityFamily: 'ai-settings-authority',
    policyStateIds: [],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['AI_SETTINGS_MUTATION'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'ai-settings-navigation',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/settings/navigation-route.ts',
    policyAuthorityFamily: 'ai-settings-navigation-authority',
    policyStateIds: [],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['AI_SETTINGS_NAVIGATION'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'annotation-fork-session',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/annotation-fork-session/route.ts',
    policyAuthorityFamily: 'annotation-fork-session',
    policyStateIds: ['annotation-fork-sessions'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['ANNOTATION_FORK_SESSION'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'ai-secret-unlock',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/settings/secret-unlock-route.ts',
    policyAuthorityFamily: 'ai-secret-unlock-authority',
    policyStateIds: ['ai-secret-unlock-requests'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['AI_SECRET_UNLOCK'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'native-app-runtime',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/runtime/native-app/route.ts',
    policyAuthorityFamily: 'native-app-runtime-authority',
    policyStateIds: [],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['NATIVE_APP_QUERY', 'NATIVE_APP_MUTATION'],
  },
  {
    acceptedSenderClass:
      'authorized extension page or content runtime selected by page-access policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'page-access route error response',
    freshnessReplayPolicy: 'tab activation record and tab lifecycle cleanup reject stale access',
    handlerId: 'page-access',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/page-access/service.ts',
    policyAuthorityFamily: 'page-access-owner',
    policyStateIds: ['page-access-tab-activation'],
    requiredAuthority: 'page-access owner policy',
    responseShape: 'page-access route response',
    routeAuthorityFamily: 'page-access-owner',
    sideEffects: 'page-access activation and session-storage authority writes',
    transitiveStateOwner: 'background page-access owner',
    messageTypes: ['PAGE_ACCESS'],
  },
  {
    acceptedSenderClass:
      'owned top-frame content runtime; the passive shim may request wake-up without pin mutation',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'content runtime wake-up route error response',
    freshnessReplayPolicy:
      'content sender binding and page-access state are checked before full runtime injection; pin activation consumes a one-shot trusted-event capability',
    handlerId: 'content-runtime-wakeup',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/runtime/page-access/wakeup-route.ts',
    policyAuthorityFamily: 'content-runtime-wakeup',
    policyStateIds: ['content-action-capabilities', 'page-access-tab-activation'],
    requiredAuthority:
      'content runtime wake-up owner policy and trusted-event capability for pin activation',
    responseShape: 'authoritative pin state, wake-up restored flag, and optional restore reason',
    routeAuthorityFamily: 'content-runtime-wakeup',
    sideEffects:
      'optional all-sites grant and pin-session mutation, lazy runtime injection, and page-preparation restore',
    transitiveStateOwner:
      'background pin-session persistence, page-access owner, and scenario session state',
    messageTypes: ['CONTENT_RUNTIME_WAKEUP'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'local-data-erasure',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/application/privacy-erasure/route.ts',
    policyAuthorityFamily: 'local-data-erasure-authority',
    policyStateIds: [
      'diagnostics-erasure-exclusion',
      'native-ingestion-erasure-exclusion',
      'offscreen-command-capability-generations',
      'offscreen-media-activity-lease',
      'page-access-tab-activation',
      'persistent-data-erasure-lease',
      'popup-export-erasure-exclusion',
      'project-export-capabilities',
      'project-export-job-ledger',
      'tab-mode-runtime-state',
      'video-recording-control-lease',
      'voice-input-port-session-authority',
    ],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['ERASE_LOCAL_EXTENSION_DATA'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'settings-transfer',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/application/settings-transfer/route.ts',
    policyAuthorityFamily: 'settings-transfer-authority',
    policyStateIds: ['persistent-data-erasure-lease'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['SETTINGS_TRANSFER'],
  },
  {
    acceptedSenderClass: 'popup export runtime',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'owner-local:popup-export-job',
    boundary: 'background-runtime',
    errorShape: 'popup export job route error response',
    freshnessReplayPolicy: 'job id and monotonic status revisions reject stale updates',
    handlerId: 'popup-export-job',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/capture/popup-export/job/route.ts',
    policyAuthorityFamily: 'popup-export-job',
    policyStateIds: ['popup-export-jobs'],
    requiredAuthority: 'popup export job owner policy',
    responseShape: 'popup export job status response',
    routeAuthorityFamily: 'popup-export-job',
    sideEffects: 'page package collection, visible native capture, archive creation, and download',
    transitiveStateOwner: 'background popup-export job owner',
    messageTypes: [
      'START_POPUP_EXPORT_JOB',
      'GET_POPUP_EXPORT_JOB_STATUS',
      'CANCEL_POPUP_EXPORT_JOB',
      'ACK_POPUP_EXPORT_JOB_STATUS',
    ],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'llm-content-processing',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/llm/router.ts',
    policyAuthorityFamily: 'llm-content-processing',
    policyStateIds: ['llm-session-tokens'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['PROCESS_WITH_LLM'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'llm-scenario-editor-processing',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/ai/llm/editor-router.ts',
    policyAuthorityFamily: 'llm-scenario-editor-processing',
    policyStateIds: ['llm-session-tokens'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['PROCESS_SCENARIO_EDITOR_WITH_LLM'],
  },
  {
    acceptedSenderClass: 'popup runtime requesting scoped tab-route authority',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'popup capability issuance error response',
    freshnessReplayPolicy: 'issued capability binds current tab, operation, request id, and expiry',
    handlerId: 'popup-tab-route-capability-issuance',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule:
      'apps/extension/src/background/runtime/routing/capabilities/popup-tab/route-capabilities.ts',
    policyAuthorityFamily: 'popup-tab-route-capability-issuance',
    policyStateIds: ['popup-tab-route-capabilities'],
    requiredAuthority: 'popup tab-route capability issuer',
    responseShape: 'popup tab-route capability grant response',
    routeAuthorityFamily: 'popup-tab-route-capability-issuance',
    sideEffects: 'issues one-shot tab-route capability without performing tab side effects',
    transitiveStateOwner: 'popup tab-route capability store',
    messageTypes: ['REQUEST_POPUP_TAB_ROUTE_CAPABILITY'],
  },
  {
    acceptedSenderClass:
      'owned content runtime requesting activation-key, runtime-token, proof, or capability issuance',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'capability issuance error response',
    freshnessReplayPolicy:
      'activation key binds sender and action purpose; runtime token/proof/content intent bind action, request, sender, one-shot use, and expiry',
    handlerId: 'content-action-capability-issuance',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule:
      'apps/extension/src/background/routing-contracts/capabilities/content-action/route.ts',
    policyAuthorityFamily: 'content-action-capability-issuance',
    policyStateIds: [
      'content-action-activation-keys',
      'content-action-capabilities',
      'content-action-runtime-tokens',
      'content-action-trusted-event-proofs',
    ],
    requiredAuthority: 'content privileged action capability issuer',
    responseShape:
      'activation key, runtime token, trusted-event proof, or content action capability grant response',
    routeAuthorityFamily: 'content-action-capability-issuance',
    sideEffects: 'issues one-shot proofs and capabilities without performing the privileged action',
    transitiveStateOwner: 'content privileged action capability store',
    messageTypes: [
      'REQUEST_CONTENT_PRIVILEGED_ACTION_ACTIVATION_KEY',
      'REQUEST_CONTENT_PRIVILEGED_ACTION_RUNTIME_TOKEN',
      'REQUEST_CONTENT_PRIVILEGED_ACTION_PROOF',
      'REQUEST_CONTENT_PRIVILEGED_ACTION_CAPABILITY',
    ],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'voice-input-offscreen-event',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/voice-input/route.ts',
    policyAuthorityFamily: 'voice-input-offscreen-event-authority',
    policyStateIds: ['voice-input-port-session-authority'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['OFFSCREEN_VOICE_INPUT_EVENT'],
  },
  {
    acceptedSenderClass: 'authorized extension page or content runtime selected by owner policy',
    actionKind: 'background-owned',
    alternateAuthorizationPolicyIds: [],
    alternateAuthorityFamilies: [],
    authorizationPolicyId: 'background-owned',
    boundary: 'background-runtime',
    errorShape: 'standard runtime error response with sanitized message',
    freshnessReplayPolicy:
      'owner policy checks sender and route-specific freshness before dispatch',
    handlerId: 'frame-annotation-raster',
    keepChannelBehaviorSource: 'background-owned-route-handler',
    ownerModule: 'apps/extension/src/background/frame-annotation-raster/route.ts',
    policyAuthorityFamily: 'frame-annotation-raster-authority',
    policyStateIds: ['frame-annotation-raster-jobs'],
    requiredAuthority: 'background-owned authorization policy registry entry',
    responseShape: 'owner route response contract',
    routeAuthorityFamily: 'background-owned-ipc',
    sideEffects: 'owner-scoped background storage, AI, privacy, page-access, or runtime effects',
    transitiveStateOwner: 'declared background route owner module',
    messageTypes: ['FRAME_ANNOTATION_RASTERIZE'],
  },
] as const satisfies readonly BackgroundIngressRouteGroupData[];
