export const AUDIT_OWNER_MAPPINGS = [
  {
    owner: 'audit-db-read-guards',
    productionPrefix: 'apps/extension/src/composition/persistence/infrastructure/indexed-db/',
    exclusive: true,
    reason: 'Audit DB parser guard changes are covered by focused DB boundary suites.',
    testFiles: [
      'apps/extension/src/composition/persistence/diagnostics/index.test.ts',
      'apps/extension/src/composition/persistence/projects/index.read-guards.test.ts',
      'apps/extension/src/composition/persistence/scenario/projects/assets.test.ts',
      'apps/extension/src/composition/persistence/scenario/projects/exports.test.ts',
      'apps/extension/src/composition/persistence/scenario/projects/project.test.ts',
      'apps/extension/src/composition/persistence/effect-bundles/index.test.ts',
    ],
  },
  {
    owner: 'audit-video-runtime-export',
    productionPrefix: 'apps/extension/src/background/media/video/runtime/',
    exclusive: true,
    reason: 'Audit video runtime routes are covered by focused runtime suites.',
    testFiles: [
      'apps/extension/src/background/media/video/runtime/export-capabilities.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/export/project-export.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/state/offscreen-lifecycle.test.ts',
      'apps/extension/src/background/media/video/runtime/handlers/state/root.test.ts',
      'apps/extension/src/background/media/video/runtime/router.branches.test.ts',
      'apps/extension/src/background/media/video/runtime/router.export.test.ts',
      'apps/extension/src/background/media/video/runtime/router.fallback.test.ts',
    ],
  },
  {
    owner: 'audit-parser-and-ai-privacy',
    productionPrefix: 'apps/extension/src/content/parser/parsers/gwt/',
    exclusive: true,
    reason: 'Audit parser privacy changes are covered by focused GWT parser suites.',
    testFiles: [
      'apps/extension/src/content/parser/parsers/gwt/attr-list-dynamic-fields.helpers.test.ts',
      'apps/extension/src/content/parser/parsers/gwt/attr-list-dynamic-fields.privacy.test.ts',
    ],
  },
  {
    owner: 'audit-llm-privacy',
    productionPrefix: 'apps/extension/src/background/ai/llm/',
    exclusive: true,
    reason: 'Audit LLM payload privacy changes are covered by focused router suites.',
    testFiles: [
      'apps/extension/src/background/ai/llm/router-processing.test.ts',
      'apps/extension/src/background/ai/llm/editor-router.attachments.test.ts',
    ],
  },
  {
    owner: 'audit-shared-message-contracts',
    productionFile: 'packages/runtime-contracts/src/messaging/message-types/index.ts',
    reason: 'Shared message contract changes are exercised by messaging validator tests.',
    testFiles: ['apps/extension/src/contracts/messaging/validators/shared.test.ts'],
  },
  {
    owner: 'audit-editor-export-disclosure',
    productionPrefix: 'apps/extension/src/editor/inspector/document-actions/',
    exclusive: true,
    reason: 'Editor export disclosure changes are covered by focused document action suites.',
    testFiles: [
      'apps/extension/src/editor/inspector/document-actions/compact.test.tsx',
      'apps/extension/src/editor/inspector/document-actions/disclosure-shared.test.tsx',
      'apps/extension/src/editor/inspector/document-actions/export-image-size.test.tsx',
      'apps/extension/src/editor/inspector/document-actions/export-settings.test.tsx',
      'apps/extension/src/editor/inspector/document-actions/settings.test.ts',
    ],
  },
  {
    owner: 'audit-offscreen-project-export',
    productionPrefix: 'apps/extension/src/offscreen/project-export/',
    exclusive: true,
    reason: 'Offscreen project export changes are covered by focused export suites.',
    testFiles: [
      'apps/extension/src/offscreen/project-export/scope.test.ts',
      'apps/extension/src/offscreen/project-export/service/lifecycle.test.ts',
    ],
  },
  {
    owner: 'audit-security-boundaries',
    productionPrefix: 'packages/platform/src/security/',
    exclusive: true,
    reason: 'Security privacy and KDF boundaries are covered by focused security suites.',
    testFiles: [
      'packages/platform/src/security/ai-payload-input.test.ts',
      'packages/platform/src/security/ai-payload-privacy.test.ts',
      'packages/platform/src/security/local-secret-crypto.test.ts',
      'packages/platform/src/security/secure-random-id.test.ts',
    ],
  },
  {
    owner: 'audit-app-security-boundaries',
    productionPrefix: 'apps/extension/src/features/ai/privacy/',
    exclusive: true,
    reason: 'App-local security adapters are covered by focused security suites.',
    testFiles: ['apps/extension/src/features/ai/privacy/index.test.ts'],
  },
  {
    owner: 'audit-content-popup-export-runtime',
    productionPrefix: 'apps/extension/src/content/parser/popup-export/controller/start/',
    exclusive: true,
    allowCrossOwner: true,
    reason: 'Popup export runtime boundary changes are covered by focused start tests.',
    testFiles: [
      'apps/extension/src/content/parser/popup-export/controller/start/runtime.test.ts',
      'apps/extension/src/popup/shell/export/runtime/start/batch-save.test.ts',
    ],
  },
  {
    owner: 'audit-messaging-validator-contracts',
    productionPrefix: 'apps/extension/src/contracts/messaging/validators/',
    exclusive: true,
    reason: 'Messaging validator changes are covered by focused validator suites.',
    testFiles: [
      'apps/extension/src/contracts/messaging/validators/shared.test.ts',
      'apps/extension/src/contracts/messaging/video/validators.test.ts',
    ],
  },
];
