export const EDITOR_OWNER_MAPPINGS = [
  {
    owner: 'editor-controller-core-instance',
    productionFile: 'apps/extension/src/editor/controller/core/controller.ts',
    reason: 'Controller instance ownership is covered by core instance and crop delegation tests.',
    testFiles: [
      'apps/extension/src/editor/controller/core/base.instance-ownership.test.ts',
      'apps/extension/src/editor/controller/core/controller-crop-actions.test.ts',
    ],
  },
  {
    owner: 'editor-controller-core-instance',
    productionFile: 'apps/extension/src/editor/controller/core/controller-crop-actions.ts',
    reason: 'Crop action delegation must stay bound to the controller instance seam.',
    testFiles: ['apps/extension/src/editor/controller/core/controller-crop-actions.test.ts'],
  },
  {
    owner: 'editor-controller-core-instance',
    productionFile: 'apps/extension/src/editor/controller/core/controller-state.ts',
    reason: 'Controller state ownership is covered by the core instance ownership suite.',
    testFiles: ['apps/extension/src/editor/controller/core/base.instance-ownership.test.ts'],
  },
  {
    owner: 'editor-input-window-events',
    productionFile: 'apps/extension/src/editor/controller/input/window-events.ts',
    reason: 'Window input adaptation is covered by focused, public facade, and integration suites.',
    testFiles: [
      'apps/extension/src/editor/controller/input/index.test.ts',
      'apps/extension/src/editor/controller/input/keyboard-actions.test.ts',
      'apps/extension/src/editor/controller/input/keyboard.integration.test.ts',
      'apps/extension/src/editor/controller/input/legacy.test.ts',
      'apps/extension/src/editor/controller/input/window-events.test.ts',
    ],
  },
  {
    owner: 'editor-input-keyboard-editing',
    productionFile: 'apps/extension/src/editor/controller/input/keyboard-editing.ts',
    reason: 'Editing-key precedence is covered by focused resolver and composed keyboard suites.',
    testFiles: [
      'apps/extension/src/editor/controller/input/index.test.ts',
      'apps/extension/src/editor/controller/input/keyboard-actions.test.ts',
      'apps/extension/src/editor/controller/input/keyboard-editing.test.ts',
      'apps/extension/src/editor/controller/input/keyboard.integration.test.ts',
      'apps/extension/src/editor/controller/input/keyboard.test.ts',
      'apps/extension/src/editor/controller/input/legacy.test.ts',
    ],
  },
  {
    owner: 'editor-input-keyboard-shortcuts',
    productionFile: 'apps/extension/src/editor/controller/input/keyboard-shortcuts.ts',
    reason: 'Modifier shortcut precedence is covered by focused and composed keyboard suites.',
    testFiles: [
      'apps/extension/src/editor/controller/input/index.test.ts',
      'apps/extension/src/editor/controller/input/keyboard-actions.test.ts',
      'apps/extension/src/editor/controller/input/keyboard-shortcuts.test.ts',
      'apps/extension/src/editor/controller/input/keyboard.integration.test.ts',
      'apps/extension/src/editor/controller/input/keyboard.test.ts',
      'apps/extension/src/editor/controller/input/legacy.test.ts',
    ],
  },
  {
    owner: 'editor-freehand-dynamic-width-outline',
    productionFile:
      'apps/extension/src/editor/controller/freehand/dynamic-width/outline/points.ts',
    reason: 'Dynamic-width outline assembly is covered by the outline owner suite.',
    testFiles: [
      'apps/extension/src/editor/controller/freehand/dynamic-width/outline/owners.test.ts',
    ],
  },
  {
    owner: 'editor-freehand-point-cloud-modeling',
    productionFile: 'apps/extension/src/editor/controller/freehand/modeling.ts',
    reason: 'Freehand stroke modeling is covered by the focused modeling suite.',
    testFiles: ['apps/extension/src/editor/controller/freehand/modeling.test.ts'],
  },
  {
    owner: 'editor-freehand-recognition-corners',
    productionFile: 'apps/extension/src/editor/controller/freehand/recognition-corners.ts',
    reason: 'Corner-profile behavior is exercised through the focused recognition suite.',
    testFiles: ['apps/extension/src/editor/controller/freehand/recognition.test.ts'],
  },
  {
    owner: 'editor-selection-root-contract',
    productionFile: 'apps/extension/src/editor/controller/selection/index.ts',
    reason: 'The selection root contract is covered by the combined apply and sync owner suite.',
    testFiles: ['apps/extension/src/editor/controller/selection/coverage.test.ts'],
  },
  {
    owner: 'editor-scene-resize-dimensions',
    productionFile:
      'apps/extension/src/editor/controller/public-actions/scene/resize/dimensions.ts',
    reason: 'Scene dimension mutations are covered by the resize and public action suites.',
    testFiles: [
      'apps/extension/src/editor/controller/public-actions/index.test.ts',
      'apps/extension/src/editor/controller/public-actions/scene/resize.coverage.test.ts',
    ],
  },
  {
    owner: 'editor-scene-resize-geometry',
    productionFile:
      'apps/extension/src/editor/controller/public-actions/scene/resize/geometry.ts',
    reason: 'Scene geometry classification is covered directly and through resize actions.',
    testFiles: [
      'apps/extension/src/editor/controller/public-actions/scene/resize.coverage.test.ts',
      'apps/extension/src/editor/controller/public-actions/scene/resize/geometry.test.ts',
    ],
  },
  {
    owner: 'editor-rich-shape-callout-controls-contract',
    productionPrefix: 'apps/extension/src/editor/objects/rich-shape/callout-controls/',
    reason: 'Callout-control behavior is covered by the complete owner-local control suite.',
    testFiles: [
      'apps/extension/src/editor/objects/rich-shape/callout-controls.test.ts',
      'apps/extension/src/editor/objects/rich-shape/callout-controls/coordinates.test.ts',
      'apps/extension/src/editor/objects/rich-shape/callout-controls/factory.test.ts',
      'apps/extension/src/editor/objects/rich-shape/callout-controls/handlers.test.ts',
      'apps/extension/src/editor/objects/rich-shape/callout-controls/patch.test.ts',
    ],
  },
  {
    owner: 'editor-rich-shape-mutation-contract',
    productionPrefix: 'apps/extension/src/editor/objects/rich-shape/mutation/',
    reason: 'Rich-shape mutation behavior is covered by the root, mutation, and callout suites.',
    testFiles: [
      'apps/extension/src/editor/objects/rich-shape/callout-object-mutation.test.ts',
      'apps/extension/src/editor/objects/rich-shape/index.test.ts',
      'apps/extension/src/editor/objects/rich-shape/mutation.test.ts',
      'apps/extension/src/editor/objects/rich-shape/mutation/owners.test.ts',
    ],
  },
  {
    owner: 'editor-rich-shape-text-frame-contract',
    productionPrefix: 'apps/extension/src/editor/objects/rich-shape/text-frame/',
    reason: 'Text-frame behavior is covered at the object owner and controller projection seams.',
    testFiles: [
      'apps/extension/src/editor/controller/rich-shape-text-editor/geometry.test.ts',
      'apps/extension/src/editor/objects/rich-shape/text-frame.test.ts',
      'apps/extension/src/editor/objects/rich-shape/text-frame/owners.test.ts',
    ],
  },
  {
    owner: 'editor-line-controls-contract',
    productionPrefix: 'apps/extension/src/editor/objects/line/controls/',
    reason: 'Line control construction is covered by the aggregate and leaf control suites.',
    testFiles: [
      'apps/extension/src/editor/objects/line/controls.test.ts',
      'apps/extension/src/editor/objects/line/controls/factory.test.ts',
      'apps/extension/src/editor/objects/line/controls/midpoint.test.ts',
      'apps/extension/src/editor/objects/line/controls/point.test.ts',
    ],
  },
  {
    owner: 'editor-line-rough-fill-contract',
    productionPrefix: 'apps/extension/src/editor/objects/line/rough-fill/',
    reason: 'Line rough-fill rendering is covered by leaf, aggregate, and state integration suites.',
    testFiles: [
      'apps/extension/src/editor/objects/line/rough-fill.test.ts',
      'apps/extension/src/editor/objects/line/rough-fill/drawers.test.ts',
      'apps/extension/src/editor/objects/line/rough-fill/pattern.test.ts',
      'apps/extension/src/editor/objects/line/rough-fill/stroke.test.ts',
      'apps/extension/src/editor/objects/line/state/fill.test.ts',
    ],
  },
  {
    owner: 'editor-line-settings-contract',
    productionPrefix: 'apps/extension/src/editor/objects/line/settings/',
    reason: 'Line settings parsing is covered by leaf, root-state, and drawing-consumer suites.',
    testFiles: [
      'apps/extension/src/editor/controller/drawing/draft-update/owners.test.ts',
      'apps/extension/src/editor/controller/drawing/line-size.branches.test.ts',
      'apps/extension/src/editor/objects/line/gradient-stops.test.ts',
      'apps/extension/src/editor/objects/line/settings/fill.test.ts',
      'apps/extension/src/editor/objects/line/settings/number.test.ts',
      'apps/extension/src/editor/objects/line/settings/read.test.ts',
      'apps/extension/src/editor/objects/line/settings/rough-fill.test.ts',
      'apps/extension/src/editor/objects/line/settings/shadow.test.ts',
      'apps/extension/src/editor/objects/line/settings/stroke.test.ts',
      'apps/extension/src/editor/objects/line/state.test.ts',
    ],
  },
  {
    owner: 'editor-arrow-point-edit-contract',
    productionPrefix: 'apps/extension/src/editor/objects/arrow/point-edit/',
    reason: 'Arrow point-edit geometry is covered by aggregate and owner-focused suites.',
    testFiles: [
      'apps/extension/src/editor/objects/arrow/point-edit.test.ts',
      'apps/extension/src/editor/objects/arrow/point-edit/owners.test.ts',
    ],
  },
  {
    owner: 'editor-arrow-state-contract',
    productionPrefix: 'apps/extension/src/editor/objects/arrow/state/',
    reason: 'Arrow state application is covered by state, point-update, and leaf owner suites.',
    testFiles: [
      'apps/extension/src/editor/objects/arrow/state.appearance.test.ts',
      'apps/extension/src/editor/objects/arrow/state.coverage-extra.test.ts',
      'apps/extension/src/editor/objects/arrow/state.dynamic-width.test.ts',
      'apps/extension/src/editor/objects/arrow/state.elbow.test.ts',
      'apps/extension/src/editor/objects/arrow/state.extra.test.ts',
      'apps/extension/src/editor/objects/arrow/state.guard.test.ts',
      'apps/extension/src/editor/objects/arrow/state.test.ts',
      'apps/extension/src/editor/objects/arrow/state/appearance.test.ts',
      'apps/extension/src/editor/objects/arrow/state/apply.test.ts',
      'apps/extension/src/editor/objects/arrow/state/metadata.test.ts',
      'apps/extension/src/editor/objects/arrow/state/style.test.ts',
    ],
  },
  {
    owner: 'editor-arrow-head-builders-contract',
    productionPrefix: 'apps/extension/src/editor/objects/arrow/visual/heads-builders/',
    reason: 'Arrow-head path builders are covered by leaf and composed head suites.',
    testFiles: [
      'apps/extension/src/editor/objects/arrow/visual/heads.test.ts',
      'apps/extension/src/editor/objects/arrow/visual/heads-builders/builders.test.ts',
      'apps/extension/src/editor/objects/arrow/visual/heads-builders/open.test.ts',
    ],
  },
  {
    owner: 'editor-rectangle-shape-geometry',
    productionPrefix: 'apps/extension/src/editor/objects/shape-style-rectangle/',
    reason: 'Rectangle shape geometry is covered by owner, root contract, and scaling consumers.',
    testFiles: [
      'apps/extension/src/editor/controller/events/runtime.object-scaling.test.ts',
      'apps/extension/src/editor/controller/layer-actions/state/resize.test.ts',
      'apps/extension/src/editor/objects/facade.contract.test.ts',
      'apps/extension/src/editor/objects/shape-style-apply.test.ts',
      'apps/extension/src/editor/objects/shape-style-rectangle.test.ts',
      'apps/extension/src/editor/objects/shape-style-rectangle/owners.test.ts',
      'apps/extension/src/editor/objects/shape-style.extra.test.ts',
      'apps/extension/src/editor/objects/shape-style.normalize.test.ts',
    ],
  },
  {
    owner: 'editor-blur-render-lifecycle',
    productionPrefix: 'apps/extension/src/editor/objects/annotation/blur/render/',
    reason: 'Blur rendering is covered by lifecycle, owner, and public rendering suites.',
    testFiles: [
      'apps/extension/src/editor/objects/annotation/blur-rendering.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/render.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/render/owners.test.ts',
    ],
  },
  {
    owner: 'editor-blur-backdrop-capture',
    productionPrefix: 'apps/extension/src/editor/objects/annotation/blur/backdrop/',
    reason: 'Blur backdrop capture is covered by bounds, canvas, capture, and render integration.',
    testFiles: [
      'apps/extension/src/editor/objects/annotation/blur/backdrop.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/backdrop/bounds.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/backdrop/canvas.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/backdrop/canvas/owners.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/backdrop/capture.test.ts',
      'apps/extension/src/editor/objects/annotation/blur/render.test.ts',
    ],
  },
  {
    owner: 'editor-magnet-manager',
    productionFile: 'apps/extension/src/editor/controller/magnet/manager.ts',
    reason: 'Magnet manager behavior is covered by focused manager tests.',
    testFiles: [
      'apps/extension/src/editor/controller/magnet/manager.test.ts',
      'apps/extension/src/editor/controller/magnet/manager.active-tool.test.ts',
    ],
  },
  {
    owner: 'editor-floating-workspace-tool-properties',
    productionFile: 'apps/extension/src/editor/workspace/floating/tool-properties-rail.tsx',
    reason: 'Floating tool properties rail behavior is covered by its focused component suite.',
    testFiles: ['apps/extension/src/editor/workspace/floating/tool-properties-rail.test.tsx'],
  },
  {
    owner: 'editor-floating-workspace-selection-toolbar-geometry',
    productionFile: 'apps/extension/src/editor/workspace/floating/canvas-toolbar-geometry.ts',
    reason: 'Selection toolbar geometry is covered by the focused geometry suite.',
    testFiles: ['apps/extension/src/editor/workspace/floating/canvas-toolbar-geometry.test.ts'],
  },
  {
    owner: 'editor-floating-workspace-view-controls',
    productionFile: 'apps/extension/src/editor/workspace/floating/view-controls-popovers.tsx',
    reason: 'Floating view control popovers are covered through the view controls suite.',
    testFiles: ['apps/extension/src/editor/workspace/floating/view-controls.test.tsx'],
  },
  {
    owner: 'editor-custom-shape-import',
    productionPrefix: 'apps/extension/src/editor/objects/custom-shapes/',
    reason:
      'Custom shape import parsing, budget, and persistence are covered by focused import suites.',
    testFiles: [
      'apps/extension/src/editor/objects/custom-shapes/budget.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/importer.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/import-persistence.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/excalidraw/parser.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/excalidraw/geometry.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/path-data.test.ts',
      'apps/extension/src/editor/objects/custom-shapes/svg-safety.test.ts',
    ],
  },
  {
    owner: 'editor-shape-browser-custom-import',
    productionPrefix: 'apps/extension/src/editor/inspector/tools/shape-browser/',
    reason:
      'Shape browser custom import state and diagnostics are covered by focused browser import suites.',
    testFiles: [
      'apps/extension/src/editor/inspector/tools/shape-browser/custom-shapes.import.test.tsx',
      'apps/extension/src/editor/inspector/tools/shape-browser/custom-shapes.hook.test.tsx',
      'apps/extension/src/editor/inspector/tools/shape-browser/custom-shapes.stale.test.tsx',
      'apps/extension/src/editor/inspector/tools/shape-browser/custom-shapes.test.tsx',
    ],
  },
];
