const settings = 'apps/extension/src/settings';
const settingsSections = `${settings}/sections`;
const popup = 'apps/extension/src/popup';

export const SHARED_FACADE_OWNER_MAPPINGS = [
  {
    owner: 'sf-editor-floating-workspace',
    productionPrefix: 'apps/extension/src/editor/workspace/floating/',
    exclusive: true,
    reason: 'Editor floating workspace suites.',
    testFiles: [
      'apps/extension/src/editor/workspace/floating/canvas-selection-toolbar.test.tsx',
      'apps/extension/src/editor/workspace/floating/document-bar.test.tsx',
      'apps/extension/src/editor/workspace/floating/inspector.test.tsx',
      'apps/extension/src/editor/workspace/floating/overlays.test.tsx',
      'apps/extension/src/editor/workspace/floating/tool-rail.test.tsx',
      'apps/extension/src/editor/workspace/floating/view-controls.test.tsx',
    ],
  },
  {
    owner: 'sf-editor-toolbar',
    productionPrefix: 'apps/extension/src/editor/workspace/toolbar/',
    exclusive: true,
    reason: 'Editor toolbar suites.',
    testFiles: [
      'apps/extension/src/editor/workspace/toolbar/index.test.tsx',
      'apps/extension/src/editor/workspace/toolbar/inspector-summary.test.tsx',
      'apps/extension/src/editor/workspace/toolbar/section-helpers.test.tsx',
    ],
  },
  {
    owner: 'sf-scenario-canvas',
    productionPrefix: 'apps/extension/src/scenario-editor/canvas/',
    exclusive: true,
    reason: 'Scenario canvas suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/canvas/controls.test.tsx',
      'apps/extension/src/scenario-editor/canvas/controls.zoom.test.tsx',
    ],
  },
  {
    owner: 'sf-scenario-page-shell',
    productionPrefix: 'apps/extension/src/scenario-editor/page-shell/',
    exclusive: true,
    reason: 'Scenario page-shell suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/page-shell/page.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/side-panels.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/timeline.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/toolbar/shell.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/view.presentation.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/view.test.tsx',
    ],
  },
  {
    owner: 'sf-scenario-inspector',
    productionPrefix: 'apps/extension/src/scenario-editor/inspector/',
    exclusive: true,
    reason: 'Scenario inspector suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/inspector/layers.test.tsx',
      'apps/extension/src/scenario-editor/inspector/panel.tabs.test.tsx',
      'apps/extension/src/scenario-editor/inspector/panel.test.tsx',
    ],
  },
  {
    owner: 'sf-settings-ai-providers',
    productionPrefix: `${settingsSections}/ai-providers`,
    exclusive: true,
    reason: 'Settings AI provider suites.',
    testFiles: [
      `${settingsSections}/ai-providers/index.test.tsx`,
      `${settingsSections}/ai-providers/surface/modals.test.tsx`,
      `${settingsSections}/ai-providers/surface/prompt-card.test.tsx`,
    ],
  },
  {
    owner: 'sf-settings-quick-actions',
    productionPrefix: `${settingsSections}/quick-actions`,
    exclusive: true,
    reason: 'Settings quick-action suites.',
    testFiles: [`${settingsSections}/quick-actions/editor-output.test.tsx`],
  },
  {
    owner: 'sf-settings-surface',
    productionPrefix: `${settings}/section-surface`,
    exclusive: true,
    reason: 'Settings surface suite.',
    testFiles: [`${settings}/section-surface/loading-state.test.tsx`],
  },
  {
    owner: 'sf-settings-save-presets',
    productionPrefix: `${settingsSections}/save-presets`,
    exclusive: true,
    reason: 'Settings preset suites.',
    testFiles: [
      `${settingsSections}/save-presets/editor-modal/fields/name-field.test.tsx`,
      `${settingsSections}/save-presets/editor-modal/fields/path-field.test.tsx`,
      `${settingsSections}/save-presets/editor-modal/index.test.tsx`,
      `${settingsSections}/save-presets/surface/cards.test.tsx`,
    ],
  },
  {
    owner: 'sf-settings-sections',
    productionPrefix: settingsSections,
    exclusive: true,
    reason: 'Settings section suites.',
    testFiles: [
      `${settingsSections}/ai-providers/index.test.tsx`,
      `${settingsSections}/editor/rows.test.tsx`,
      `${settingsSections}/quick-actions/editor-output.test.tsx`,
      `${settingsSections}/save-presets/surface/cards.test.tsx`,
    ],
  },
  {
    owner: 'sf-settings-viewport-preset-editor',
    productionPrefix: `${settingsSections}/viewport-presets/editor`,
    exclusive: true,
    reason: 'Viewport preset suites.',
    testFiles: [`${settingsSections}/viewport-presets/editor/views.test.tsx`],
  },
  {
    owner: 'sf-offscreen-multi-source',
    productionPrefix: 'apps/extension/src/offscreen/recording/multi-source/',
    exclusive: true,
    reason: 'Offscreen multi-source suites.',
    testFiles: [
      'apps/extension/src/offscreen/recording/multi-source/finalize.test.ts',
      'apps/extension/src/offscreen/recording/multi-source/index.test.ts',
      'apps/extension/src/offscreen/recording/multi-source/recorders.test.ts',
    ],
  },
  {
    owner: 'sf-offscreen-signals',
    productionPrefix: 'apps/extension/src/offscreen/recording/signals/',
    exclusive: true,
    reason: 'Offscreen signal suite.',
    testFiles: ['apps/extension/src/offscreen/recording/signals/static-frame.test.ts'],
  },
  {
    owner: 'sf-popup',
    productionPrefix: popup,
    exclusive: true,
    reason: 'Popup owner suites.',
    testFiles: [
      `${popup}/shell/app-shell/content/export.test.tsx`,
      `${popup}/shell/command-palette/index.test.tsx`,
      `${popup}/shell/export/footer/primary-action.test.tsx`,
      `${popup}/recording/video/footer/active-controls.test.tsx`,
      `${popup}/recording/video/footer/actions.test.tsx`,
      `${popup}/recording/video/setup/options/preset-selector.test.tsx`,
      `${popup}/recording/video/setup/options/webcam-selector.test.tsx`,
    ],
  },
  {
    owner: 'sf-scenario-project-state',
    productionPrefix: 'apps/extension/src/scenario-editor/project/state/',
    exclusive: true,
    reason: 'Scenario project-state suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/project/state/index.test.tsx',
      'apps/extension/src/scenario-editor/project/state/selection-autosave-effects.test.tsx',
      'apps/extension/src/scenario-editor/project/state/ui.test.tsx',
    ],
  },
  {
    owner: 'sf-scenario-project-mutation',
    productionPrefix: 'apps/extension/src/scenario-editor/project/mutation/',
    exclusive: true,
    reason: 'Scenario project-mutation suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/project/mutation/actions/index.test.ts',
      'apps/extension/src/scenario-editor/project/mutation/actions/project-crud/video.test.ts',
      'apps/extension/src/scenario-editor/project/mutation/history/project/index.test.tsx',
    ],
  },
  {
    owner: 'sf-scenario-slide-navigator',
    productionPrefix: 'apps/extension/src/scenario-editor/page-shell/slide-navigator/',
    exclusive: true,
    reason: 'Scenario slide-navigator suites.',
    testFiles: [
      'apps/extension/src/scenario-editor/page-shell/slide-navigator/ScenarioSlideNavigator.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/slide-navigator/ScenarioSlideNavigatorStepRow.test.tsx',
      'apps/extension/src/scenario-editor/page-shell/slide-navigator/thumbnails.test.tsx',
    ],
  },
  {
    owner: 'sf-video-editor-workspace',
    productionPrefix: 'apps/extension/src/video-editor/workspace/surface/',
    exclusive: true,
    reason: 'Video workspace suites.',
    testFiles: [
      'apps/extension/src/video-editor/workspace/surface/index.test.tsx',
      'apps/extension/src/video-editor/workspace/surface/main.test.tsx',
    ],
  },
  {
    owner: 'sf-editor-command-palette',
    productionPrefix: 'apps/extension/src/editor/shell/command-palette/',
    exclusive: true,
    reason: 'Editor command-palette suite.',
    testFiles: ['apps/extension/src/editor/shell/command-palette/index.test.tsx'],
  },
];
