const MAX_TEXT_FIELD_CHARS = 1_000_000;
const MAX_PROMPT_CHARS = 16_000;
const MAX_TEXT_FIELD_DECODED_BYTES = 2_000_000;
const MAX_PROMPT_DECODED_BYTES = 64_000;
const MAX_LEGACY_NODE_COUNT = 2_000;
const MAX_LEGACY_NODE_TEXT_CHARS = 16_000;
const MAX_LEGACY_NODE_TEXT_DECODED_BYTES = 64_000;
const MAX_SCENARIO_ATTACHMENT_COUNT = 20;
const MAX_SCENARIO_ATTACHMENT_TOTAL_CHARS = 50_000_000;
const MAX_SCENARIO_ATTACHMENT_DATA_URL_CHARS = 10_000_000;
const MAX_SCENARIO_ATTACHMENT_TOTAL_DECODED_BYTES = 38_000_000;
const MAX_SCENARIO_ATTACHMENT_DATA_URL_DECODED_BYTES = 7_000_000;

export const CONTENT_AI_PAYLOAD_LIMITS = {
  maxLegacyNodeCount: MAX_LEGACY_NODE_COUNT,
  maxLegacyNodeTextChars: MAX_LEGACY_NODE_TEXT_CHARS,
  maxLegacyNodeTextDecodedBytes: MAX_LEGACY_NODE_TEXT_DECODED_BYTES,
  maxPromptChars: MAX_PROMPT_CHARS,
  maxPromptDecodedBytes: MAX_PROMPT_DECODED_BYTES,
  maxTextFieldChars: MAX_TEXT_FIELD_CHARS,
  maxTextFieldDecodedBytes: MAX_TEXT_FIELD_DECODED_BYTES,
} as const;

export const SCENARIO_EDITOR_AI_PAYLOAD_LIMITS = {
  allowedAttachmentMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
  maxAttachmentCount: MAX_SCENARIO_ATTACHMENT_COUNT,
  maxAttachmentDataUrlChars: MAX_SCENARIO_ATTACHMENT_DATA_URL_CHARS,
  maxAttachmentDataUrlDecodedBytes: MAX_SCENARIO_ATTACHMENT_DATA_URL_DECODED_BYTES,
  maxAttachmentTotalChars: MAX_SCENARIO_ATTACHMENT_TOTAL_CHARS,
  maxAttachmentTotalDecodedBytes: MAX_SCENARIO_ATTACHMENT_TOTAL_DECODED_BYTES,
  maxInstructionChars: MAX_PROMPT_CHARS,
  maxInstructionDecodedBytes: MAX_PROMPT_DECODED_BYTES,
  maxJsonFieldChars: MAX_TEXT_FIELD_CHARS,
  maxJsonFieldDecodedBytes: MAX_TEXT_FIELD_DECODED_BYTES,
  maxProjectSnapshotJsonChars: MAX_TEXT_FIELD_CHARS * 2,
  maxProjectSnapshotJsonDecodedBytes: MAX_TEXT_FIELD_DECODED_BYTES * 2,
} as const;
