import { defineShapeEntry } from './entry-builders';
import { EDITOR_RICH_SHAPE_FAMILY } from './families';
import { SHAPE_GEOMETRY } from './geometry/index';
import { EDITOR_BUILT_IN_SHAPE_CATEGORY } from './types';

export const BLOCK_ARROW_SHAPE_ENTRIES = [
  defineShapeEntry({
    id: 'block-arrow',
    label: 'Блочная стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'right-arrow',
    geometry: SHAPE_GEOMETRY.rightArrow,
    aliases: ['блочная стрелка', 'block arrow', 'filled arrow'],
    compatibilityIds: ['right-block-arrow'],
  }),
  defineShapeEntry({
    id: 'right-arrow',
    label: 'Стрелка вправо',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'right-arrow',
    geometry: SHAPE_GEOMETRY.rightArrow,
    aliases: ['стрелка вправо', 'right arrow', 'block right arrow'],
  }),
  defineShapeEntry({
    id: 'left-arrow',
    label: 'Стрелка влево',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'left-arrow',
    geometry: SHAPE_GEOMETRY.leftArrow,
    aliases: ['стрелка влево', 'left arrow', 'block left arrow'],
  }),
  defineShapeEntry({
    id: 'up-arrow',
    label: 'Стрелка вверх',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'up-arrow',
    geometry: SHAPE_GEOMETRY.upArrow,
    aliases: ['стрелка вверх', 'up arrow', 'block up arrow'],
  }),
  defineShapeEntry({
    id: 'down-arrow',
    label: 'Стрелка вниз',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'down-arrow',
    geometry: SHAPE_GEOMETRY.downArrow,
    aliases: ['стрелка вниз', 'down arrow', 'block down arrow'],
  }),
  defineShapeEntry({
    id: 'left-right-arrow',
    label: 'Стрелка влево-вправо',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'left-right-arrow',
    geometry: SHAPE_GEOMETRY.leftRightArrow,
    aliases: ['стрелка влево вправо', 'left right arrow', 'bidirectional arrow'],
  }),
  defineShapeEntry({
    id: 'up-down-arrow',
    label: 'Стрелка вверх-вниз',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'up-down-arrow',
    geometry: SHAPE_GEOMETRY.upDownArrow,
    aliases: ['стрелка вверх вниз', 'up down arrow', 'vertical double arrow'],
  }),
  defineShapeEntry({
    id: 'quad-arrow',
    label: 'Четырехсторонняя стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'quad-arrow',
    geometry: SHAPE_GEOMETRY.quadArrow,
    aliases: ['четырехсторонняя стрелка', 'quad arrow', 'four way arrow'],
  }),
  defineShapeEntry({
    id: 'notched-right-arrow',
    label: 'Стрелка с вырезом',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'notched-right-arrow',
    geometry: SHAPE_GEOMETRY.notchedRightArrow,
    aliases: ['стрелка с вырезом', 'notched arrow', 'notched right arrow'],
  }),
  defineShapeEntry({
    id: 'striped-right-arrow',
    label: 'Полосатая стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'striped-right-arrow',
    geometry: SHAPE_GEOMETRY.stripedRightArrow,
    aliases: ['полосатая стрелка', 'striped arrow', 'striped right arrow'],
  }),
  defineShapeEntry({
    id: 'chevron',
    label: 'Шеврон',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'chevron',
    geometry: SHAPE_GEOMETRY.chevron,
    aliases: ['шеврон', 'chevron'],
  }),
  defineShapeEntry({
    id: 'left-right-chevron',
    label: 'Двойной шеврон',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'left-right-chevron',
    geometry: SHAPE_GEOMETRY.leftRightChevron,
    aliases: ['двойной шеврон', 'left right chevron', 'double chevron'],
  }),
  defineShapeEntry({
    id: 'u-turn-block-arrow',
    label: 'Разворотная стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'u-turn-block-arrow',
    geometry: SHAPE_GEOMETRY.uTurnArrow,
    aliases: ['разворотная стрелка', 'u-turn arrow', 'return arrow'],
  }),
  defineShapeEntry({
    id: 'curved-right-arrow',
    label: 'Изогнутая стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'curved-right-arrow',
    geometry: SHAPE_GEOMETRY.curvedArrow,
    aliases: ['изогнутая стрелка', 'curved arrow', 'curved right arrow'],
  }),
  defineShapeEntry({
    id: 'circular-arrow',
    label: 'Круговая стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BLOCK_ARROWS,
    family: EDITOR_RICH_SHAPE_FAMILY.BLOCK_ARROW,
    kind: 'circular-arrow',
    geometry: SHAPE_GEOMETRY.circularArrow,
    aliases: ['круговая стрелка', 'circular arrow', 'cycle arrow'],
  }),
] as const;
