import { defineShapeEntry } from './entry-builders';
import { EDITOR_RICH_SHAPE_FAMILY } from './families';
import { SHAPE_GEOMETRY } from './geometry/index';
import { EDITOR_BUILT_IN_SHAPE_CATEGORY } from './types';

export const FLOWCHART_SHAPE_ENTRIES = [
  defineShapeEntry({
    id: 'flowchart-process',
    label: 'Процесс',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'process',
    geometry: SHAPE_GEOMETRY.rectangle,
    aliases: ['процесс', 'process', 'flowchart process'],
    compatibilityIds: ['process'],
  }),
  defineShapeEntry({
    id: 'flowchart-decision',
    label: 'Решение',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'decision',
    geometry: SHAPE_GEOMETRY.diamond,
    aliases: ['решение', 'decision', 'flowchart decision'],
    compatibilityIds: ['decision'],
  }),
  defineShapeEntry({
    id: 'flowchart-data',
    label: 'Данные',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'data',
    geometry: SHAPE_GEOMETRY.parallelogram,
    aliases: ['данные', 'data', 'input output'],
    compatibilityIds: ['data'],
  }),
  defineShapeEntry({
    id: 'flowchart-document',
    label: 'Документ',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'document',
    geometry: SHAPE_GEOMETRY.document,
    aliases: ['документ', 'document', 'flowchart document'],
    compatibilityIds: ['document'],
  }),
  defineShapeEntry({
    id: 'flowchart-terminator',
    label: 'Терминатор',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'terminator',
    geometry: SHAPE_GEOMETRY.roundRectangle,
    aliases: ['терминатор', 'terminator', 'start end'],
    compatibilityIds: ['terminator'],
  }),
  defineShapeEntry({
    id: 'flowchart-predefined-process',
    label: 'Предопределенный процесс',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'predefined-process',
    geometry: SHAPE_GEOMETRY.predefinedProcess,
    aliases: ['предопределенный процесс', 'predefined process', 'subprocess'],
    compatibilityIds: ['predefined-process'],
  }),
  defineShapeEntry({
    id: 'flowchart-manual-input',
    label: 'Ручной ввод',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'manual-input',
    geometry: SHAPE_GEOMETRY.manualInput,
    aliases: ['ручной ввод', 'manual input'],
    compatibilityIds: ['manual-input'],
  }),
  defineShapeEntry({
    id: 'flowchart-preparation',
    label: 'Подготовка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'preparation',
    geometry: SHAPE_GEOMETRY.hexagon,
    aliases: ['подготовка', 'preparation'],
    compatibilityIds: ['preparation'],
  }),
  defineShapeEntry({
    id: 'flowchart-connector',
    label: 'Соединитель',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'connector',
    geometry: SHAPE_GEOMETRY.ellipse,
    aliases: ['соединитель', 'connector', 'flowchart connector'],
    compatibilityIds: ['connector'],
  }),
  defineShapeEntry({
    id: 'flowchart-offpage-connector',
    label: 'Соединитель на другой странице',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'offpage-connector',
    geometry: SHAPE_GEOMETRY.pentagon,
    aliases: ['соединитель на другой странице', 'off-page connector', 'offpage connector'],
    compatibilityIds: ['offpage-connector'],
  }),
  defineShapeEntry({
    id: 'flowchart-delay',
    label: 'Задержка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'delay',
    geometry: SHAPE_GEOMETRY.delay,
    aliases: ['задержка', 'delay'],
    compatibilityIds: ['delay'],
  }),
  defineShapeEntry({
    id: 'flowchart-display',
    label: 'Дисплей',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'display',
    geometry: SHAPE_GEOMETRY.display,
    aliases: ['дисплей', 'display'],
    compatibilityIds: ['display'],
  }),
  defineShapeEntry({
    id: 'flowchart-stored-data',
    label: 'Хранимые данные',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'stored-data',
    geometry: SHAPE_GEOMETRY.storedData,
    aliases: ['хранимые данные', 'stored data', 'storage'],
    compatibilityIds: ['stored-data'],
  }),
  defineShapeEntry({
    id: 'flowchart-database',
    label: 'База данных',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.FLOWCHART,
    family: EDITOR_RICH_SHAPE_FAMILY.FLOWCHART,
    kind: 'database',
    geometry: SHAPE_GEOMETRY.database,
    aliases: ['база данных', 'database', 'data storage'],
    compatibilityIds: ['database'],
  }),
] as const;
