import { SHAPE_GEOMETRY } from './geometry/index';
import { EDITOR_RICH_SHAPE_FAMILY } from './families';
import { defineShapeEntry } from './entry-builders';
import { EDITOR_BUILT_IN_SHAPE_CATEGORY } from './types';

const lineCapabilities = ['line', 'connectors'] as const;

export const LINE_AND_BASIC_SHAPE_ENTRIES = [
  defineShapeEntry({
    id: 'line',
    label: 'Линия',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.LINE,
    kind: 'line',
    geometry: SHAPE_GEOMETRY.line,
    aliases: ['линия', 'line', 'straight line', 'отрезок'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'arrow',
    label: 'Стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.ARROW,
    kind: 'line-arrow',
    geometry: SHAPE_GEOMETRY.line,
    aliases: ['стрелка', 'arrow', 'line arrow', 'односторонняя стрелка'],
    compatibilityIds: ['line-arrow'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'double-line-arrow',
    label: 'Двусторонняя стрелка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.ARROW,
    kind: 'double-line-arrow',
    geometry: SHAPE_GEOMETRY.line,
    aliases: ['двусторонняя стрелка', 'double arrow', 'two-sided arrow', 'обоюдная стрелка'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'left-line-arrow',
    label: 'Стрелка влево',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.ARROW,
    kind: 'left-line-arrow',
    geometry: SHAPE_GEOMETRY.line,
    aliases: ['стрелка влево', 'left arrow', 'one-sided arrow'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'straight-connector',
    label: 'Прямой соединитель',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.CONNECTOR,
    kind: 'straight-connector',
    geometry: SHAPE_GEOMETRY.line,
    aliases: ['прямой соединитель', 'straight connector', 'connector'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'elbow-connector',
    label: 'Ломаный соединитель',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.CONNECTOR,
    kind: 'elbow-connector',
    geometry: SHAPE_GEOMETRY.elbowConnector,
    aliases: ['ломаный соединитель', 'orthogonal connector', 'elbow connector'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'curved-connector',
    label: 'Кривой соединитель',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.LINES,
    family: EDITOR_RICH_SHAPE_FAMILY.CONNECTOR,
    kind: 'curved-connector',
    geometry: SHAPE_GEOMETRY.curvedConnector,
    aliases: ['кривой соединитель', 'curved connector', 'curve connector'],
    capabilities: lineCapabilities,
  }),
  defineShapeEntry({
    id: 'rectangle',
    label: 'Прямоугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'rectangle',
    geometry: SHAPE_GEOMETRY.rectangle,
    aliases: ['прямоугольник', 'rectangle', 'rect'],
  }),
  defineShapeEntry({
    id: 'rounded-rectangle',
    label: 'Скругленный прямоугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'round-rectangle',
    geometry: SHAPE_GEOMETRY.roundRectangle,
    aliases: ['скругленный прямоугольник', 'rounded rectangle', 'round rectangle'],
    compatibilityIds: ['round-rectangle'],
  }),
  defineShapeEntry({
    id: 'oval',
    label: 'Овал',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'ellipse',
    geometry: SHAPE_GEOMETRY.ellipse,
    aliases: ['овал', 'эллипс', 'круг', 'oval', 'ellipse', 'circle'],
    compatibilityIds: ['ellipse', 'circle'],
  }),
  defineShapeEntry({
    id: 'triangle',
    label: 'Треугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'triangle',
    geometry: SHAPE_GEOMETRY.triangle,
    aliases: ['треугольник', 'triangle', 'isosceles triangle'],
  }),
  defineShapeEntry({
    id: 'right-triangle',
    label: 'Прямоугольный треугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'right-triangle',
    geometry: SHAPE_GEOMETRY.rightTriangle,
    aliases: ['прямоугольный треугольник', 'right triangle'],
  }),
  defineShapeEntry({
    id: 'diamond',
    label: 'Ромб',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'diamond',
    geometry: SHAPE_GEOMETRY.diamond,
    aliases: ['ромб', 'diamond', 'rhombus'],
  }),
  defineShapeEntry({
    id: 'parallelogram',
    label: 'Параллелограмм',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'parallelogram',
    geometry: SHAPE_GEOMETRY.parallelogram,
    aliases: ['параллелограмм', 'parallelogram'],
  }),
  defineShapeEntry({
    id: 'trapezoid',
    label: 'Трапеция',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'trapezoid',
    geometry: SHAPE_GEOMETRY.trapezoid,
    aliases: ['трапеция', 'trapezoid', 'trapezium'],
  }),
  defineShapeEntry({
    id: 'pentagon',
    label: 'Пятиугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'pentagon',
    geometry: SHAPE_GEOMETRY.pentagon,
    aliases: ['пятиугольник', 'pentagon'],
  }),
  defineShapeEntry({
    id: 'hexagon',
    label: 'Шестиугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'hexagon',
    geometry: SHAPE_GEOMETRY.hexagon,
    aliases: ['шестиугольник', 'hexagon'],
  }),
  defineShapeEntry({
    id: 'octagon',
    label: 'Восьмиугольник',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.BASIC,
    family: EDITOR_RICH_SHAPE_FAMILY.OFFICE,
    kind: 'octagon',
    geometry: SHAPE_GEOMETRY.octagon,
    aliases: ['восьмиугольник', 'octagon'],
  }),
] as const;
