import { defineShapeEntry } from './entry-builders';
import { EDITOR_RICH_SHAPE_FAMILY } from './families';
import { SHAPE_GEOMETRY } from './geometry/index';
import { EDITOR_BUILT_IN_SHAPE_CATEGORY } from './types';

export const STAR_AND_BANNER_SHAPE_ENTRIES = [
  defineShapeEntry({
    id: 'star-4',
    label: 'Четырехконечная звезда',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'star-4',
    geometry: SHAPE_GEOMETRY.star4,
    aliases: ['четырехконечная звезда', '4 point star', 'sparkle'],
  }),
  defineShapeEntry({
    id: 'star-5',
    label: 'Пятиконечная звезда',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'star-5',
    geometry: SHAPE_GEOMETRY.star5,
    aliases: ['пятиконечная звезда', 'star', '5 point star'],
  }),
  defineShapeEntry({
    id: 'star-8',
    label: 'Восьмиконечная звезда',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'star-8',
    geometry: SHAPE_GEOMETRY.star8,
    aliases: ['восьмиконечная звезда', '8 point star'],
  }),
  defineShapeEntry({
    id: 'star-16',
    label: 'Шестнадцатиконечная звезда',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'star-16',
    geometry: SHAPE_GEOMETRY.star16,
    aliases: ['шестнадцатиконечная звезда', '16 point star'],
  }),
  defineShapeEntry({
    id: 'burst-12',
    label: 'Вспышка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'burst-12',
    geometry: SHAPE_GEOMETRY.burst12,
    aliases: ['вспышка', 'burst', 'seal', 'explosion'],
  }),
  defineShapeEntry({
    id: 'ribbon',
    label: 'Лента',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'ribbon',
    geometry: SHAPE_GEOMETRY.ribbon,
    aliases: ['лента', 'ribbon', 'banner'],
  }),
  defineShapeEntry({
    id: 'double-ribbon',
    label: 'Двойная лента',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'double-ribbon',
    geometry: SHAPE_GEOMETRY.doubleRibbon,
    aliases: ['двойная лента', 'double ribbon', 'banner'],
  }),
  defineShapeEntry({
    id: 'wave',
    label: 'Волна',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'wave',
    geometry: SHAPE_GEOMETRY.wave,
    aliases: ['волна', 'wave', 'wavy banner'],
  }),
  defineShapeEntry({
    id: 'scroll',
    label: 'Свиток',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.STARS_BANNERS,
    family: EDITOR_RICH_SHAPE_FAMILY.STAR_BANNER,
    kind: 'scroll',
    geometry: SHAPE_GEOMETRY.scroll,
    aliases: ['свиток', 'scroll', 'scroll banner'],
  }),
] as const;

export const ACTION_BUTTON_SHAPE_ENTRIES = [
  defineShapeEntry({
    id: 'action-button-home',
    label: 'Кнопка: домой',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-home',
    geometry: SHAPE_GEOMETRY.roundRectangle,
    aliases: ['кнопка домой', 'home button', 'action button home'],
  }),
  defineShapeEntry({
    id: 'action-button-information',
    label: 'Кнопка: информация',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-information',
    geometry: SHAPE_GEOMETRY.roundRectangle,
    aliases: ['кнопка информация', 'information button', 'info button'],
  }),
  defineShapeEntry({
    id: 'action-button-back',
    label: 'Кнопка: назад',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-back',
    geometry: SHAPE_GEOMETRY.leftArrow,
    aliases: ['кнопка назад', 'back button', 'action button back'],
  }),
  defineShapeEntry({
    id: 'action-button-forward',
    label: 'Кнопка: вперед',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-forward',
    geometry: SHAPE_GEOMETRY.rightArrow,
    aliases: ['кнопка вперед', 'forward button', 'action button forward'],
  }),
  defineShapeEntry({
    id: 'action-button-return',
    label: 'Кнопка: возврат',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-return',
    geometry: SHAPE_GEOMETRY.uTurnArrow,
    aliases: ['кнопка возврат', 'return button', 'action button return'],
  }),
  defineShapeEntry({
    id: 'action-button-help',
    label: 'Кнопка: справка',
    category: EDITOR_BUILT_IN_SHAPE_CATEGORY.ACTION_BUTTONS,
    family: EDITOR_RICH_SHAPE_FAMILY.ACTION,
    kind: 'action-button-help',
    geometry: SHAPE_GEOMETRY.ellipse,
    aliases: ['кнопка справка', 'help button', 'question button'],
  }),
] as const;
