import { vi } from 'vitest';
import type { VideoEditorState } from '../../state/store';

const STORE_ACTION_NAMES = [
  'openExportDialog',
  'renameProject',
  'renameTrack',
  'setDiagnosticsOpen',
  'setPlaying',
  'togglePlaying',
  'setPixelsPerSecond',
  'clearPlacementMode',
  'selectScene',
  'selectClip',
  'selectTrack',
  'selectTransition',
  'selectCursorSegment',
  'selectObjectTrack',
  'selectActionSegment',
  'selectMotionRegion',
  'startActionPointPlacement',
  'startMotionAreaPlacement',
  'startMotionFocusPlacement',
  'startMotionPathStopAreaPlacement',
  'startMotionPathStopPointPlacement',
  'startObjectTrackAnchorPlacement',
  'moveClip',
  'closeTrackGap',
  'trimClipStart',
  'trimClipEnd',
  'addTrackLogicalLane',
  'moveTrack',
  'toggleTrackVisibility',
  'toggleTrackLock',
  'toggleUtilityLaneVisibility',
  'toggleUtilityLaneLock',
  'clearUtilityLane',
  'addTextOverlay',
  'addAnnotationOverlay',
  'addVideoBlock',
  'addShapeOverlay',
  'updateClipTransform',
  'updateProject',
  'detachClipGroup',
  'updateClipMuted',
  'updateClipVolume',
  'updateClipAudioEnvelope',
  'updateClipFades',
  'updateClipPlaybackRate',
  'updateClipTransitions',
  'applyMediaClipVisualsToTrack',
  'applyEffectDocument',
  'deleteEffectInstance',
  'duplicateEffectInstance',
  'moveEffectInstance',
  'updateEffectInstance',
  'upsertObjectTrack',
  'upsertObjectTrackCorrectionAnchor',
  'deleteObjectTrack',
  'convertTextClipToAnnotation',
  'updateMediaClipFitMode',
  'updateMediaClipFitScalePercent',
  'updateMediaClipShadowIntensity',
  'updateMediaClipShadowMode',
  'updateTextClipContent',
  'updateTextClipStyle',
  'updateAnnotationClipContent',
  'updateAnnotationClipStyle',
  'updateAnnotationClipTemplate',
  'updateShapeClipStyle',
  'updateTransitionDuration',
  'updateTransitionEasing',
  'updateTransitionTemplate',
  'updateCursorSampleSkinOverride',
  'updateCursorSampleInterpolation',
  'updateCursorSampleVisibility',
  'clearCursorSampleSkinOverride',
  'updateActionEventDetails',
  'deleteMotionRegion',
  'updateMotionRegion',
  'deleteClip',
  'duplicateClip',
  'splitClipAt',
  'closeExportDialog',
  'updateExportSettings',
  'setProject',
  'setRecordingTelemetry',
  'setReady',
  'setError',
  'setSaveState',
  'setCurrentTime',
  'updateExportStatus',
  'failExport',
  'failExportCancellation',
  'completeExport',
  'cancelExport',
  'toggleTelemetryLaneVisibility',
  'upsertAsset',
  'addAssetClip',
  'addSubtitleOverlay',
  'startExport',
  'addTrack',
  'deleteTrack',
  'insertCursorSample',
  'deleteCursorSample',
  'deleteActionEvent',
  'updateSubtitleTrackStyle',
] as const;

export function createHookStoreActions() {
  return Object.fromEntries(STORE_ACTION_NAMES.map((name) => [name, vi.fn()])) as unknown as Pick<
    VideoEditorState,
    (typeof STORE_ACTION_NAMES)[number]
  >;
}

export function createWorkspaceHookPreviewState() {
  return {
    handleStartVerticalResize: vi.fn(),
    paneHeight: 280,
    preferences: {
      preferences: {
        mode: 'live' as const,
        rasterPreset: '720p' as const,
        zoom: 'fit' as const,
      },
      retrySave: vi.fn(),
      saveFailed: false,
      updatePreferences: vi.fn(),
    },
    workspaceSplitRef: { current: null },
  };
}
