export const ARCHIVE_PACKAGE_OWNER_MAPPINGS = [
  {
    owner: 'runtime-contracts-page-package',
    productionFile: 'packages/runtime-contracts/src/page-package/index.ts',
    reason: 'Page Package hostile wire parsing and closed schema limits have exact contract proof.',
    testFiles: ['packages/runtime-contracts/src/page-package/index.test.ts'],
  },
  {
    owner: 'page-package-path-admission',
    productionFile: 'apps/extension/src/workflows/page-package/paths.ts',
    reason: 'Page Package contribution paths and collision policy have focused hostile proof.',
    testFiles: ['apps/extension/src/workflows/page-package/paths.test.ts'],
  },
  {
    owner: 'page-package-composer',
    productionFile: 'apps/extension/src/workflows/page-package/composer.ts',
    reason: 'Page Package inventory and canonical manifest bytes have focused composition proof.',
    testFiles: ['apps/extension/src/workflows/page-package/composer.test.ts'],
  },
  {
    owner: 'page-package-archive-writer',
    productionFile: 'apps/extension/src/workflows/page-package/archive.ts',
    reason: 'Page Package streaming archive emission and rollback have focused writer proof.',
    testFiles: ['apps/extension/src/workflows/page-package/archive.test.ts'],
  },
  {
    owner: 'page-collection-manifest-planner',
    productionFile: 'apps/extension/src/workflows/page-package/collection/manifest.ts',
    reason: 'Collection allocation, reports, totals and archive ordering have focused plan proof.',
    testFiles: ['apps/extension/src/workflows/page-package/collection/manifest.test.ts'],
  },
  {
    owner: 'page-collection-archive-writer',
    productionFile: 'apps/extension/src/workflows/page-package/collection/archive.ts',
    reason: 'Flat Collection Package streaming, ordering and rollback have focused writer proof.',
    testFiles: ['apps/extension/src/workflows/page-package/collection/archive.test.ts'],
  },
  {
    owner: 'page-package-blob-contribution',
    productionFile: 'apps/extension/src/workflows/page-package/contributions/blob.ts',
    reason: 'Blob-backed contribution MIME, digest and source admission has exact focused proof.',
    testFiles: ['apps/extension/src/workflows/page-package/contributions/blob.test.ts'],
  },
  {
    owner: 'page-package-export-contribution',
    productionFile: 'apps/extension/src/workflows/page-package/contributions/export.ts',
    reason: 'Export Manager Blob entry classification and allocation has exact focused proof.',
    testFiles: ['apps/extension/src/workflows/page-package/contributions/export.test.ts'],
  },
  {
    owner: 'page-package-web-copy-contribution',
    productionFile: 'apps/extension/src/workflows/page-package/contributions/web-copy.ts',
    reason: 'Safe Web-copy singleton and linked asset contribution admission has exact proof.',
    testFiles: ['apps/extension/src/workflows/page-package/contributions/web-copy.test.ts'],
  },
  {
    owner: 'page-package-diagnostic-contribution',
    productionFile: 'apps/extension/src/workflows/page-package/contributions/diagnostics.ts',
    reason: 'Diagnostic level, intent, inert path and digest admission has exact focused proof.',
    testFiles: ['apps/extension/src/workflows/page-package/contributions/diagnostics.test.ts'],
  },
  {
    owner: 'shared-provenance-url-sanitizer',
    productionFile: 'packages/platform/src/security/provenance-url.ts',
    reason: 'Provenance URL sanitization policy is covered by focused security fixtures.',
    testFiles: ['packages/platform/src/security/provenance-url.test.ts'],
  },
  {
    owner: 'background-web-snapshot-package-boundary',
    productionFile: 'apps/extension/src/background/media-hub/web-snapshot.ts',
    reason: 'Web snapshot package save boundaries are covered by the focused media-hub tests.',
    testFiles: ['apps/extension/src/background/media-hub/web-snapshot.test.ts'],
  },
  {
    owner: 'scenario-project-v3-guards',
    productionFile: 'apps/extension/src/features/scenario/project/v3/guards.ts',
    reason: 'Scenario v3 project guard boundaries are covered by focused guard tests.',
    testFiles: ['apps/extension/src/features/scenario/project/v3/guards.test.ts'],
  },
  {
    owner: 'db-video-project-read-guards',
    productionFile: 'apps/extension/src/composition/persistence/projects/read-guards.ts',
    reason: 'Video project read guard behavior is covered by focused read-guard tests.',
    testFiles: ['apps/extension/src/composition/persistence/projects/index.read-guards.test.ts'],
  },
  {
    owner: 'scenario-project-entry-raw-reader',
    productionFile: 'apps/extension/src/composition/persistence/scenario/projects/project.ts',
    reason: 'Raw scenario project entry reads are covered by backup restore preparation tests.',
    testFiles: ['apps/extension/src/composition/persistence/scenario/projects/project.test.ts'],
  },
  {
    owner: 'media-hub-store-filename-boundary',
    productionFile: 'apps/extension/src/workflows/media-hub/store.ts',
    reason: 'Media hub storage filename boundaries are covered by explicit unsafe-name tests.',
    testFiles: [
      'apps/extension/src/workflows/media-hub/store.filename-boundary.test.ts',
      'apps/extension/src/workflows/media-hub/store.test.ts',
      'apps/extension/src/workflows/media-hub/assembly.test.ts',
      'apps/extension/src/workflows/media-hub/cleanup.inventory.test.ts',
      'apps/extension/src/workflows/media-hub/cleanup.test.ts',
      'apps/extension/src/features/media-hub/events/index.test.ts',
      'apps/extension/src/workflows/media-hub/store.cleanup-targets.test.ts',
    ],
  },
  {
    owner: 'shared-zip-profile-entry-filenames',
    productionFile: 'packages/platform/src/data/zip-profile/entry-filenames.ts',
    reason: 'Archive leaf filename normalization is covered by focused unsafe-name fixtures.',
    testFiles: ['packages/platform/src/data/zip-profile/entry-filenames.test.ts'],
  },
];
