import type { DesignSystemRegistryEntry } from '../types';
import { SHARED_DESIGN_SYSTEM_ANNOTATABLE_IMAGE_REGISTRY } from './annotatable-image.data.ts';
import { SHARED_DESIGN_SYSTEM_COMPACT_INSPECTOR_CONTROLS_REGISTRY } from './compact-inspector-controls.data.ts';
import { SHARED_DESIGN_SYSTEM_COMMANDS_REGISTRY } from './commands.data.ts';
import { SHARED_DESIGN_SYSTEM_CONTENT_REGISTRY } from './content.data.ts';
import { SHARED_DESIGN_SYSTEM_EDITOR_CHROME_REGISTRY } from './editor-chrome.data.ts';
import { SHARED_DESIGN_SYSTEM_FEEDBACK_REGISTRY } from './feedback.data.ts';
import { SHARED_DESIGN_SYSTEM_GLASS_REGISTRY } from './glass.data.ts';
import { SHARED_DESIGN_SYSTEM_POPUP_SHELL_REGISTRY } from './popup-shell.data.ts';
import { SHARED_DESIGN_SYSTEM_SCENARIO_REGISTRY } from './scenario.data.ts';

export const SHARED_DESIGN_SYSTEM_REGISTRY: DesignSystemRegistryEntry[] = [
  ...SHARED_DESIGN_SYSTEM_ANNOTATABLE_IMAGE_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_COMPACT_INSPECTOR_CONTROLS_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_COMMANDS_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_FEEDBACK_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_EDITOR_CHROME_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_GLASS_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_POPUP_SHELL_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_CONTENT_REGISTRY,
  ...SHARED_DESIGN_SYSTEM_SCENARIO_REGISTRY,
];
