export const EDITOR_CORNER_CONTROL_SIZE = 13;
export const EDITOR_CORNER_CONTROL_SIZE_HOVER = 17;
export const EDITOR_CORNER_CONTROL_SIZE_MIN = 9;
export const EDITOR_CORNER_CONTROL_SIZE_HOVER_MIN = 12;
export const EDITOR_ROTATE_CONTROL_SIZE = 18;
export const EDITOR_ROTATE_CONTROL_SIZE_HOVER = 22;
export const EDITOR_SELECTION_BORDER_SCALE_FACTOR = 1.35;

export const DEFAULT_CORNER_CONTROLS = ['tl', 'tr', 'br', 'bl'] as const;
