import type React from 'react';

// Diagnostics panel still uses inline styles, but its palette now comes from the shared theme tokens.
export const COLORS = {
  background: 'var(--sniptale-color-surface-panel)',
  surface1: 'var(--sniptale-color-surface-panel)',
  surface2: 'var(--sniptale-color-surface-panel)',
  surfaceHover: 'var(--sniptale-color-surface-overlay)',
  primary: 'var(--sniptale-color-text-primary)',
  secondary: 'var(--sniptale-color-text-secondary)',
  tertiary: 'var(--sniptale-color-text-muted)',
  brandPrimary: 'var(--sniptale-color-accent)',
  brandSecondary: 'var(--sniptale-color-danger)',
  iconPurple: 'var(--sniptale-color-accent-emphasis)',
  iconTeal: 'var(--sniptale-color-info)',
  iconBlue: 'var(--sniptale-color-info)',
  success: 'var(--sniptale-color-success)',
  error: 'var(--sniptale-color-danger)',
  warning: 'var(--sniptale-color-accent-emphasis)',
  border: 'var(--sniptale-color-border-soft)',
  borderHover: 'var(--sniptale-color-border-strong)',
};

export const diagnosticsPanelStyles: Record<string, React.CSSProperties> = {
  container: {
    borderRadius: '14px',
    background: COLORS.surface1,
    border: `1px solid ${COLORS.border}`,
    overflow: 'hidden',
  },
  card: {
    padding: '16px',
    borderRadius: '14px',
    background: COLORS.surface1,
    border: `1px solid ${COLORS.border}`,
  },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid var(--sniptale-color-border-accent-soft)',
    borderTopColor: COLORS.brandPrimary,
    borderRadius: '50%',
    animation: 've-spin 0.8s linear infinite',
  },
  iconBox: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    background: 'var(--sniptale-color-accent-soft)',
    border: '1px solid var(--sniptale-color-border-accent-soft)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    padding: '16px',
    borderBottom: '1px solid var(--sniptale-color-border-subtle)',
  },
  headerDisclosure: {
    margin: '6px 0 0',
    maxWidth: '520px',
    fontSize: '11px',
    lineHeight: 1.4,
    color: COLORS.tertiary,
  },
  title: {
    margin: 0,
    fontSize: '13px',
    fontWeight: 500,
    color: COLORS.primary,
  },
  subtitle: {
    margin: 0,
    fontSize: '12px',
    color: COLORS.tertiary,
    marginTop: '1px',
  },
  statsBar: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '1px',
    background: 'var(--sniptale-color-surface-overlay)',
  },
  statValue: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 600,
  },
  statLabel: {
    margin: 0,
    fontSize: '12px',
    color: COLORS.tertiary,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginTop: '2px',
  },
  eventsList: {
    maxHeight: '320px',
    overflowY: 'auto',
  },
  emptyState: {
    padding: '24px',
    textAlign: 'center',
    color: COLORS.tertiary,
    fontSize: '13px',
  },
  eventRow: {
    width: '100%',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    background: 'transparent',
    border: 'none',
    borderBottom: '1px solid var(--sniptale-color-border-subtle)',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background 0.15s ease',
  },
  eventChevron: {
    marginTop: '2px',
    flexShrink: 0,
  },
  eventIcon: {
    marginTop: '2px',
    flexShrink: 0,
  },
  eventContent: {
    flex: 1,
    minWidth: 0,
  },
  eventTs: {
    fontSize: '12px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: COLORS.tertiary,
  },
  eventKind: {
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  eventMessage: {
    margin: 0,
    fontSize: '13px',
    color: COLORS.secondary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginTop: '2px',
  },
  eventData: {
    padding: '0 16px 12px 44px',
  },
  eventDataPre: {
    margin: 0,
    fontSize: '12px',
    color: COLORS.tertiary,
    background: COLORS.background,
    borderRadius: '8px',
    padding: '10px 12px',
    overflowX: 'auto',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  metaBar: {
    padding: '10px 16px',
    borderTop: '1px solid var(--sniptale-color-border-subtle)',
    background: 'var(--sniptale-color-surface-overlay)',
  },
};
