export function buildScenarioHtmlScript(): string {
  return [
    '(function(){',
    'var activeLightbox=null;',
    'function closeLightbox(){',
    'if(!(activeLightbox instanceof HTMLElement)){return;}',
    'activeLightbox.hidden=true;',
    'document.body.classList.remove("lightbox-open");',
    'activeLightbox=null;',
    '}',
    'function openLightbox(id){',
    'var next=document.getElementById(id);',
    'if(!(next instanceof HTMLElement)){return;}',
    'closeLightbox();',
    'next.hidden=false;',
    'document.body.classList.add("lightbox-open");',
    'activeLightbox=next;',
    '}',
    'document.addEventListener("click",function(event){',
    'if(!(event.target instanceof Element)){return;}',
    'var trigger=event.target.closest("[data-lightbox-trigger]");',
    'if(trigger instanceof HTMLElement){',
    'var targetId=trigger.getAttribute("data-lightbox-target");',
    'if(targetId){event.preventDefault();openLightbox(targetId);return;}',
    '}',
    'if(event.target.closest("[data-lightbox-close]")){event.preventDefault();closeLightbox();}',
    '});',
    'document.addEventListener("keydown",function(event){',
    'if(event.key==="Escape"){closeLightbox();}',
    '});',
    '})();',
  ].join('');
}
