export function buildScenarioStepStyles(): string[] {
  return [
    '.capture-step,.missing-step{display:grid;gap:18px;padding:18px 0 4px;background:transparent;',
    'break-inside:avoid;page-break-inside:avoid;}',
    '.step-topline{display:grid;gap:12px;}',
    '.step-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;}',
    '.step-index{display:inline-flex;align-items:center;justify-content:center;min-width:46px;height:32px;',
    'padding:0 14px;border-radius:999px;background:rgba(147,97,47,.08);color:var(--editorial);',
    'font-size:12px;font-weight:700;letter-spacing:.18em;text-transform:uppercase;white-space:nowrap;}',
    '.step-title{margin:0;font-size:clamp(26px,4vw,38px);line-height:1.02;letter-spacing:-.03em;}',
    '.step-body,.section-content p,.note-step p{max-width:60ch;color:var(--text-soft);font-size:16px;line-height:1.7;}',
    '.capture-media{position:relative;overflow:hidden;padding:8px;border-radius:24px;background:rgba(236,226,210,.52);',
    'box-shadow:0 10px 24px rgba(68,45,21,.06);}',
    '.capture-media-link{display:block;position:relative;width:100%;padding:0;border:0;background:none;',
    'color:inherit;cursor:zoom-in;text-decoration:none;}',
    '.capture-preview{display:block;width:100%;height:auto;border-radius:18px;background:#f1e6d3;}',
    '.capture-action{position:absolute;right:16px;bottom:16px;display:grid;place-items:center;width:42px;height:42px;',
    'border:1px solid rgba(255,255,255,.18);border-radius:999px;background:rgba(28,23,18,.74);color:#fff7ec;',
    'font-size:20px;opacity:0;transform:translateY(6px);transition:opacity 160ms ease,transform 160ms ease,',
    'background 160ms ease;}',
    '.capture-media-link:hover .capture-action,.capture-media-link:focus-visible .capture-action{opacity:1;',
    'transform:translateY(0);}.capture-action:hover{background:rgba(28,23,18,.92);}',
    '.section-step{display:grid;gap:10px;padding:14px 0 2px;border-top:1px solid rgba(145,111,67,.22);',
    'break-inside:avoid;page-break-inside:avoid;}',
    '.section-content{display:grid;gap:10px;}.section-content h2{margin:0;font-size:clamp(28px,4vw,42px);',
    'line-height:1.03;letter-spacing:-.035em;}',
    '.note-step{display:grid;gap:10px;padding:16px 18px 18px;border-radius:20px;background:rgba(255,253,248,.68);',
    'border-left:4px solid transparent;break-inside:avoid;page-break-inside:avoid;}',
    '.note-step[data-tone="info"]{border-left-color:rgba(73,114,150,.55);background:var(--info-bg);}',
    '.note-step[data-tone="warning"]{border-left-color:rgba(180,122,43,.62);background:var(--warning-bg);}',
    '.note-step[data-tone="error"]{border-left-color:rgba(167,74,67,.58);background:var(--error-bg);}',
    '.note-step h3{margin:0;font-size:20px;line-height:1.2;}.note-step p{margin:0;}',
    '.divider-step{height:0;margin:2px 0 6px;border:0;border-top:1px solid rgba(145,111,67,.22);}',
    '.missing-frame{display:grid;place-items:center;min-height:240px;border:1px dashed rgba(111,86,58,.32);',
    'border-radius:20px;background:linear-gradient(135deg,rgba(177,144,104,.08),rgba(255,255,255,.2)),',
    'repeating-linear-gradient(-45deg,rgba(145,111,67,.04),rgba(145,111,67,.04) 12px,transparent 12px,',
    'transparent 24px);color:var(--text-muted);text-align:center;}',
    '.missing-frame strong{display:block;margin-bottom:8px;color:var(--text-soft);font-size:18px;}',
  ];
}
